/*
 * File: app/view/BackOffice/bom/BomCmplNoticeBoardManagementMViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

/*
    모바일 시스템 공통 :: 환경설정 - 컨트롤러

    @author BNK시스템/계장/김정균
    @since 2019.06.13
    @version 1.0
    @see

    << 개정이력(Modification Information) >>

    수정일		  수정자                수정내용
    ----------	------------------   --------------------------
    2019.06.13	BNK시스템/계장/김정균   최초 생성
*/
Ext.define('BNK.view.BackOffice.bom.BomCmplNoticeBoardManagementMViewController', {
    extend: 'BaseViewController',
    alias: 'controller.BomCmplNoticeBoardManagementMViewController',

    config: {
        viewId: 'BomCmplNoticeBoardManagementM'
    },

    openDtl: function(params) {
        var me = this;
        var vm = me.getViewModel();

        var naviView = vm.get('naviView');
        me.PUSH_VIEW(naviView, {
            menuId  : 'BomCmplNoticeBoardManagementDetailM',
            title   : '공지사항 상세보기',
            isSubView : true,
            parentView : naviView,
            records : params.selectedData
        });
    },

    onSearchTap: function(button, e, eOpts) {
        var me = this,
            vm = me.getViewModel(),
            refs = me.getReferences(),
            searchValue = refs.searchField.getValue();

        var params = {
            title : searchValue
        };

        // 공지사항 조건 검색
        var grid = refs.grid;
        grid.getStore().getProxy().extraParams = params;
        grid.getStore().removeAll();
        grid.getStore().loadPage(1);
    },

    onGridSelect: function(dataview, selected, eOpts) {
        var me = this;
        var refs = me.getReferences();
        var vm = me.getViewModel();
        var selectedData = selected[0].data;

        me.openDtl({
            selectedData : selectedData,
        });

        // var naviView = vm.get('naviView');
        // me.PUSH_VIEW(naviView, {
        // //     menuId  : 'BomCmplNoticeBoardManagementDetailM',
        //     menuId  : 'BomCmplHomeM',
        //     title   : '공지사항 상세보기',
        //     isSubView : true,
        //     parentView : naviView,
        //     records : selectedData
        // });

    },

    initialize: function(component, eOpts) {
        var me = this,
            vm = me.getViewModel(),
            refs = me.getReferences(),
            grid = refs.grid;

        vm.set('naviView', component.parentView);

        // Hidden Grid Header
        grid.el.select('.x-headercontainer').setStyle('height',	'0px');

    }

});