/*
 * File: app/view/BackOffice/bom/BomTasSend01MViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

/*
    모바일 :: 알림전송 - 컨트롤러

    @author BNK시스템/파트너/박주혁
    @since 2025.05.30
    @version 1.0
    @see

    << 개정이력(Modification Information) >>

    수정일		  수정자                  수정내용
    ----------	------------------     --------------------------
    2025.05.30	BNK시스템/파트너/박주혁     최초 생성
*/
Ext.define('BNK.view.BackOffice.bom.BomTasSend01MViewController', {
    extend: 'BaseViewController',
    alias: 'controller.BomTasSend01MViewController',

    config: {
        viewId: 'BomTasSend01M'
    },

    onSelect: function() {
        var me = this,
            vm = me.getViewModel(),
            refs = me.getReferences(),
            store = vm.storeInfo.VctStore,
            startDate = DateUtils.getDate(refs.startDate.getValue()),
            endDate = DateUtils.getDate(refs.endDate.getValue()),
            params = {
                startDate : startDate,
                endDate : endDate
            };

        if(startDate > endDate){
            Ext.Msg.alert('확인','시작일이 종료일보다 클 수 없습니다.');
            return false;
        }

        store.getProxy().extraParams = params;
        store.removeAll();
        store.loadPage(1);

    },

    defaut: function() {
        var me = this,
            vm = me.getViewModel(),
            refs = me.getReferences(),
            store = vm.storeInfo.Store;

        store.getProxy().extraParams.page = 1;
        var toolbar = refs.grid.getPlugins()[0];
        toolbar.setCurrentPage(1);


    },

    onBtnSearch: function(button, e, eOpts) {
        this.onSelect();
    },

    /*
        알림 등록 상세 페이지 이동

    */
    onBtnSend: function(button, e, eOpts) {
        var me = this,
            vm = me.getViewModel(),
            refs = me.getReferences();

        var naviView = me.getView().up('navigationview');
        me.PUSH_VIEW(naviView, {
            menuId  : 'BomTasSend02M',
            title   : '알림전송',
            parentView : me.getView(),
            isSubView : true,
            crud : Constants.crudState.CREATE,
            //     records : records
        });

    },

    /* grid Select로 기 등록된 알림 조회 */
    onGridSelect: function(dataview, selected, eOpts) {
        var me = this,
            vm = me.getViewModel(),
            refs = me.getReferences(),
            seletedRecord = selected[0].data;

        seletedRecord.beforePage = 'BomTasSend01M';
        var naviView = me.getView().up('navigationview');
        me.PUSH_VIEW(naviView, {
            menuId : 'BomTasSend02M',
            title  : '알림전송',
            parentView : me.getView(),
            isSubView : true,
            seletedRecord : seletedRecord,
            crud : Constants.crudState.UPDATE,
        });

    },

    /* 화면초기화 */
    initialize: function(component, eOpts) {
        var me = this,
            refs = me.getReferences(),
            grid = refs.grid;

        var dateMinus1 = new Date();
        dateMinus1.setDate(1);
        refs.startDate.setValue(DateUtils.parseDate(dateMinus1));

        dateMinus1.setMonth(dateMinus1.getMonth()+1);
        dateMinus1.setDate(7);
        refs.endDate.setValue(DateUtils.parseDate(dateMinus1));

        grid.el.select('.x-headercontainer').setStyle('height',	'0px');

        // grid SELECT
        me.onSelect();

    },

    /* 페이징 등 스토어가 새로 load 될때 동작하는 이벤트 */
    onJsonstoreLoad: function(store, records, successful, operation, eOpts) {
        var me = this,
            vm = me.getViewModel(),
            refs = me.getReferences(),
            grid = refs.grid;

    }

});