/*
 * File: app/view/BackOffice/bom/BomTasPushDetailItem01M.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

/*
    모바일 푸시 상세팝업 아이템 : 텍스트 & URL - 화면

    @author BNK시스템/파트너/지민영
    @since 2020.11.13
    @version 1.0
    @see

    << 개정이력(Modification Information) >>

    수정일       수정자                  수정내용
    ----------  ------------------     --------------------------
    2020.11.13  BNK시스템/파트너/지민영   최초 생성
*/
Ext.define('BNK.view.BackOffice.bom.BomTasPushDetailItem01M', {
    extend: 'Ext.Container',
    alias: 'widget.BomTasPushDetailItem01M',

    alternateClassName: [
        'BomTasPushDetailItem01M'
    ],
    requires: [
        'BNK.view.BackOffice.bom.BomTasPushDetailItem01MViewModel',
        'BNK.view.BackOffice.bom.BomTasPushDetailItem01MViewController',
        'Ext.Img',
        'Ext.field.Display',
        'Ext.Container',
        'Ext.Button'
    ],

    controller: 'BomTasPushDetailItem01MViewController',
    viewModel: {
        type: 'BomTasPushDetailItem01MViewModel'
    },
    padding: '0 10 0 10',
    scrollable: true,

    layout: {
        type: 'vbox',
        align: 'center'
    },
    items: [
        {
            xtype: 'image',
            height: 13.26,
            width: 84.68,
            margin: '30 0 0 0',
            src: 'resources/images/icon-popup-logo.png'
        },
        {
            xtype: 'displayfield',
            reference: 'title',
            style: 'word-break:break-all;font-size:24px;font-weight:bold;text-align:center;color:black;line-height: 26px;',
            width: '100%',
            html: '제목',
            margin: '30 0 0 0',
            bodyAlign: 'center'
        },
        {
            xtype: 'container',
            reference: 'content',
            style: 'word-break: break-all;',
            width: '100%',
            margin: '40 0 0 0',
            scrollable: true
        },
        {
            xtype: 'button',
            reference: 'btnUrl',
            height: 48,
            hidden: true,
            style: 'border:solid 1px;border-radius:50px;font-size:16px;color:#cb2b11;',
            width: '100%',
            margin: '20 0 0 0',
            text: '자세히 보기',
            listeners: {
                tap: 'onBtnUrl'
            }
        },
        {
            xtype: 'button',
            reference: 'btnInnerUrl',
            height: 48,
            hidden: true,
            style: 'border:solid 1px;border-radius:50px;font-size:16px;color:#cb2b11;',
            width: '100%',
            margin: '20 0 0 0',
            text: '화면 이동',
            listeners: {
                tap: 'onBtnInnerUrl'
            }
        }
    ],
    listeners: {
        initialize: 'onContainerInitialize'
    }

});