/*
 * File: app/view/BackOffice/bom/BomTasSend01M.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

/*
    모바일 :: 알림전송 - 화면

    @author BNK시스템/파트너/박주혁
    @since 2025.05.30
    @version 1.0
    @see

    << 개정이력(Modification Information) >>

    수정일		  수정자                  수정내용
    ----------	------------------     --------------------------
    2025.05.30	BNK시스템/파트너/박주혁     최초 생성
*/
Ext.define('BNK.view.BackOffice.bom.BomTasSend01M', {
    extend: 'Ext.Container',
    alias: 'widget.BomTasSend01M',

    alternateClassName: [
        'BomTasSend01'
    ],
    requires: [
        'BNK.view.BackOffice.bom.BomTasSend01MViewModel',
        'BNK.view.BackOffice.bom.BomTasSend01MViewController',
        'Ext.field.Date',
        'Ext.picker.Date',
        'Ext.Button',
        'Ext.grid.Grid',
        'Ext.grid.column.Column',
        'Ext.grid.plugin.PagingToolbar',
        'Ext.Toolbar'
    ],

    controller: 'BomTasSend01MViewController',
    viewModel: {
        type: 'backoffice.bom.bomtassend01m'
    },
    layout: 'card',

    items: [
        {
            xtype: 'container',
            height: 50,
            width: '100%',
            docked: 'top',
            padding: '0 0 0 10',
            layout: 'hbox',
            items: [
                {
                    xtype: 'datefield',
                    flex: 1,
                    reference: 'startDate',
                    itemId: 'mydate',
                    label: '',
                    dateFormat: 'Y-m-d',
                    picker: {
                        xtype: 'datepicker',
                        hideOnMaskTap: true,
                        header: false,
                        title: '',
                        dayText: '일',
                        monthText: '월',
                        slotOrder: [
                            'year',
                            'month',
                            'day'
                        ],
                        yearText: '년'
                    }
                },
                {
                    xtype: 'datefield',
                    flex: 1,
                    reference: 'endDate',
                    itemId: 'mydate2',
                    name: '',
                    margin: '0 0 0 20',
                    label: '',
                    dateFormat: 'Y-m-d',
                    picker: {
                        xtype: 'datepicker',
                        hideOnMaskTap: true,
                        header: false,
                        title: '',
                        dayText: '일',
                        monthText: '월',
                        slotOrder: [
                            'year',
                            'month',
                            'day'
                        ],
                        yearText: '년'
                    }
                },
                {
                    xtype: 'button',
                    itemId: 'btnSearch1',
                    ui: 'action',
                    docked: 'right',
                    text: '조회',
                    listeners: {
                        tap: 'onBtnSearch'
                    }
                }
            ]
        },
        {
            xtype: 'grid',
            reference: 'grid',
            height: '100%',
            width: '100%',
            bind: {
                store: '{VctStore}'
            },
            columns: [
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, record, dataIndex, cell, column) {
                        var tasDvcd = CodeUtils.getText('TAS001', record.data.tasDvcd);
                        var tasTrsDvcd = CodeUtils.getText('TAS002', record.data.tasTrsDvcd);
                        var trsNm = record.data.trsNm;
                        var trsStcd = CodeUtils.getText('TAS007', record.data.trsStcd);
                        var trsNcnt = record.data.trsNcnt;
                        var trsSusNcnt = record.data.trsSusNcnt;
                        var trsFailNcnt = record.data.trsFailNcnt;
                        var booDt = record.data.booDt;
                        var booTm = record.data.booTm;
                        var booDttm = record.data.booDttm;

                        if(Ext.isEmpty(booDttm)){
                            booDttm = '';
                        }

                        var text1 = '<span style="color:blue;font-weight:bold;">' + tasDvcd + tasTrsDvcd + '</span>';
                        var text2 = '<span>' + trsStcd+ '</span>'; // 전송상태

                        result = '<div><span>'+text1+'</span> <span> ('+text2+') </span></div>';
                        result += '<div style="font-size:15px;font-weight:bold;width:100%;overflow: hidden;white-space:nowrap;text-overflow:ellipsis;display:inline-block;">' + trsNm + '</div>';
                        result += '<br/><div style="font-size:12px;font-weight:bold;color:#000">예약 : '+booDttm+'</div>';

                        cell.setStyle('padding:0px;');
                        return result;
                    },
                    flex: '1.7',
                    height: '',
                    hidden: false,
                    cell: {
                        xtype: 'gridcell',
                        encodeHtml: false
                    },
                    dataIndex: 'trsNcnt',
                    text: '알림내용'
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, record, dataIndex, cell, column) {
                        var trsNcnt = record.data.trsNcnt;
                        var trsSusNcnt = record.data.trsSusNcnt;
                        var trsFailNcnt = record.data.trsFailNcnt;
                        var booDt = record.data.booDt;
                        var booTm = record.data.booTm;
                        var booDttm = record.data.booDttm;
                        // var result = DateUtils.parseDate(record.data.aplDt);

                        result = '<div style="font-size:12px;font-weight:bold;color:#000">전체 : '+trsNcnt+'건</div>';
                        result += '<div style="font-size:12px;font-weight:bold;color:#000">성공 : '+trsSusNcnt+'건</div>';
                        result += '<div style="font-size:12px;font-weight:bold;color:#000">실패 : '+trsFailNcnt+'건</div>';


                        // var aplStcd = record.data.aplStcd; // 신청 상태

                        // var aplStcdText = CodeUtils.getText('INB025', aplStcd);
                        // var aplStcdRender = '<div>' + aplStcdText + '</div>';
                        // result += aplStcdRender;

                        return result;

                    },
                    flex: '1.3',
                    align: 'right',
                    cell: {
                        xtype: 'gridcell',
                        encodeHtml: false
                    },
                    dataIndex: 'trsSusNcnt',
                    text: '알림내역'
                }
            ],
            plugins: [
                {
                    type: 'gridpagingtoolbar'
                }
            ],
            items: [
                {
                    xtype: 'toolbar',
                    docked: 'bottom',
                    items: [
                        {
                            xtype: 'button',
                            flex: 1,
                            ui: 'action',
                            margin: '5 5 10 5',
                            text: '알림 등록',
                            listeners: {
                                tap: 'onBtnSend'
                            }
                        }
                    ]
                }
            ],
            listeners: {
                select: 'onGridSelect'
            }
        }
    ],
    listeners: {
        initialize: 'initialize'
    }

});