/*
 * File: app/view/BackOffice/bom/BomTasPushSettingItemsM.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

/*
    모바일 푸시 알림설정 (item) - 화면

    @author BNK시스템/파트너/지민영
    @since 2020.08.14
    @version 1.0
    @see

    << 개정이력(Modification Information) >>

    수정일       수정자                  수정내용
    ----------  ------------------     --------------------------
    2020.08.14  BNK시스템/파트너/지민영   최초 생성
*/
Ext.define('BNK.view.BackOffice.bom.BomTasPushSettingItemsM', {
    extend: 'Ext.Container',
    alias: 'widget.BomTasPushSettingItemsM',

    alternateClassName: [
        'BomTasPushSettingItemsM'
    ],
    requires: [
        'BNK.view.BackOffice.bom.BomTasPushSettingItemsMViewModel',
        'BNK.view.BackOffice.bom.BomTasPushSettingItemsMViewController',
        'Ext.field.Display',
        'Ext.field.Text',
        'Ext.Spacer',
        'Ext.field.Toggle'
    ],

    controller: 'BomTasPushSettingItemsMViewController',
    viewModel: {
        type: 'BomTasPushSettingItemsMViewModel'
    },
    height: 100,
    style: 'border:solid 1px;',
    padding: 10,

    layout: {
        type: 'hbox',
        align: 'center'
    },
    items: [
        {
            xtype: 'displayfield',
            reference: 'msgDvnm'
        },
        {
            xtype: 'textfield',
            reference: 'msgDvcd',
            hidden: true
        },
        {
            xtype: 'spacer'
        },
        {
            xtype: 'togglefield',
            reference: 'recvYn'
        }
    ],
    listeners: {
        initialize: 'onContainerInitialize'
    }

});