/*
 * File: app/view/BackOffice/bom/BomWekWork02MViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

/*
            주간 업무 : 업무보고 작성 - 팝업 CTL

            @author BNK시스템/파트너/박주혁
            @since 2024.02.13
            @version 1.0
            @see

            << 개정이력(Modification Information) >>

            수정일       수정자                수정내용
            ----------  ------------------   --------------------------
            2024.02.06  BNK시스템/파트너/박주혁   최초 생성

*/
Ext.define('BNK.view.BackOffice.bom.BomWekWork02MViewController', {
    extend: 'BaseViewController',
    alias: 'controller.BackOffice.bom.BomWekWork02MViewController',

    config: {
        viewId: 'BomWekWork02M'
    },

    onValidationCheck: function(formData) {
        var me = this,
            vm = me.getViewModel(),
            refs = me.getReferences();

        var errMsg = '';

        // 필수값 체크 : 사무분담, 업무상태, 제목, 개발수행보고여부
        if(Ext.isEmpty(formData.hrHrocJasRolId)){
            errMsg += '사무분담은 필수값입니다.<br/>';
        }
        if(Ext.isEmpty(formData.weekWorkStcd)){
            errMsg += '업무상태는 필수값입니다.<br/>';
        }
        if(Ext.isEmpty(formData.title)){
            errMsg += '제목은 필수값입니다.<br/>';
        }
        else if(refs.title.getValue().length > refs.title.getMaxLength()){
            errMsg += '제목은 ' + refs.title.getMaxLength() +'자를 넘길 수 없습니다.';
        }
        if(Ext.isEmpty(formData.reprtYn)){
            errMsg += '개발수행보고서는 필수값입니다.<br/>';
        }
        if(formData.weekWorkStcd =='20'){
            if(Ext.isEmpty(formData.pstlyPrgr)){
                errMsg += '상태가 "진행"일경우 진척률은 필수값입니다.<br/>';
            }
        }

        if(formData.reprtYn == '1'){
            if(Ext.isEmpty(refs.strdt.getValue()) || Ext.isEmpty(refs.edt.getValue())){
                errMsg += '개발수행보고서 적용일 경우 작업기간은 필수값입니다.<br/>';
            }
        }
        // 데이터 변경 체크 (사무분담, 프로젝트, 업무상태, 진척률, 시작, 종료, 업무명, 업무내용, 개발수행보고)
        var beforeData = vm.get('popupData.reptData');
        if(!Ext.isEmpty(beforeData)){
            if(	!(
               (beforeData.hrHrocJasRolId != refs.rolCbx.getValue() && refs.rolCbx.getValue() !== '') ||
               (beforeData.boPrjmInfoId   != refs.pjtCbx.getValue() && refs.pjtCbx.getValue() !== '') ||
               (beforeData.weekWorkStcd   != refs.workStcdCbx.getValue() && refs.workStcdCbx.getValue() !== '') ||
                beforeData.pstlyPrgr 	  != refs.prgrField.getValue() ||
                DateUtils.getDate(beforeData.strdt) != DateUtils.getDate(refs.strdt.getValue()) ||
                DateUtils.getDate(beforeData.edt)   != DateUtils.getDate(refs.edt.getValue()) ||
                beforeData.title          != refs.title.getValue() ||
               ( (beforeData.rawCntn 		  != refs.cntn.getValue()) && (refs.cntn.getValue()!==null) )  ||
                beforeData.reprtYn 		  != refs.reprtYn.getValues()['reprtYn'] ||
                beforeData.bizDvnm        != refs.bizCbx.getValue()
             )
          ){
            errMsg += '변경된 내용이 없습니다.<br/>';
          }
        }


        return errMsg;

    },

    onClose: function() {
        var me = this,
            vm = me.getViewModel(),
            refs = me.getReferences();

            me.getView().up().down('BomWekWork01M').controller.onSelectRept();
            vm.getView().up().pop();
    },

    onSave: function(crudState) {
        var me = this,
            vm = me.getViewModel(),
            refs = me.getReferences();

        if(refs.prgrField.getInputValue() > refs.prgrField.getMaxValue() ){
            me.onShowAlert('유효성검증','진행율은 ' + refs.prgrField.getMaxValue() +'%를 넘길 수 없습니다.');
            return false;
        }


        var saveData = refs.inputForm.getValues();
        var errMsg = me.onValidationCheck(saveData);
        if(errMsg.length>0 && crudState != 'D'){
            me.onShowAlert('유효성검증',errMsg);
            return false;
        }

        if(crudState == 'D'){
            saveData.deleteYn = 'Y';
        }
        var popupData = vm.get('popupData');

        saveData.boWekmTmrdId = popupData.boWekmTmrdId;
        saveData.boWekdTmrdEmpId = popupData.boWekdTmrdEmpId;
        saveData.wrtDevc = 2; // 단말기구분 : 모바일
        saveData.strdt = DateUtils.getDate(saveData.strdt);
        saveData.edt = DateUtils.getDate(saveData.edt);
        if(!Ext.isEmpty(saveData.rawCntn)){
            saveData.cntn = saveData.rawCntn.replace(/\n/g,'<br/>');
        }

        if(!Ext.isEmpty(popupData.reptData)){
            saveData.boWekhTmrdEmpReptId = popupData.reptData.boWekhTmrdEmpReptId;
        }

        Ext.Ajax.request({
            headers: {
                viewId : me.getViewId(),
                serviceId : 'BomWekWorkSvc.saveBomWekWorkRept'
            },
            jsonData : saveData,
            scope : me,
            success : function(response) {
                var res = Ext.JSON.decode(response.responseText);

                //         me.getView().fireEvent('complete');
                me.onShowAlert('알림','정상처리되었습니다.');
                //         me.getView().close();
                me.getView().up().down('BomWekWork01M').controller.onSelectRept();
                // 홈으로
                vm.getView().up().pop();
            }
        });
    },

    onShowAlert: function(title, msg) {
        Ext.Msg.show({
                buttons :  {
                    yes : {itemId : Ext.MessageBox.YES, text : '확인'}
                },
                title : title,
                message : msg,
                alwaysOnTop : true,
                fn : function(btn) {
                    return;
                }
            });
    },

    onShowConfirm: function(title, msg, callback) {
        Ext.Msg.show({
                        buttons :  {
                            yes : {itemId : Ext.MessageBox.YES, text : '예'},
                            no  : {itemId : Ext.MessageBox.NO, text : '아니오'}
                        },
                        title : title,
                        message : msg,
                        alwaysOnTop : true,
                        fn : callback
                    });
    },

    onTapBtnClose: function(button, e, eOpts) {
        var me = this,
            vm = me.getViewModel(),
            refs = me.getReferences();

        me.onClose();
    },

    onChangeStrdt: function(datefield, newDate, oldDate, eOpts) {
        var me = this,
            vm = me.getViewModel(),
            refs = me.getReferences();
        var strdt = DateUtils.getDate(newDate);
        var edt = DateUtils.getDate(refs.edt.getValue());
        if(Ext.isEmpty(strdt) || Ext.isEmpty(edt)){
            return false;
        }

        if(strdt > edt){
            refs.strdt.setValue(DateUtils.parseDate(edt));
            me.onShowAlert('알림','시작일자는 종료일자보다 클 수 없습니다.');
        }
    },

    onChangeEdt: function(datefield, newDate, oldDate, eOpts) {
        var me = this,
            vm = me.getViewModel(),
            refs = me.getReferences();
        var strdt = DateUtils.getDate(refs.strdt.getValue());
        var edt = DateUtils.getDate(newDate);
        if(Ext.isEmpty(strdt) || Ext.isEmpty(edt)){
            return false;
        }

        if(strdt > edt){
            refs.edt.setValue(DateUtils.parseDate(strdt));
            me.onShowAlert('알림','종료일자는 시작일자보다 작을 수 없습니다.');
        }

    },

    onWorkStcdChange: function(combobox, newValue, oldValue, eOpts) {
        var me = this,
            vm = me.getViewModel(),
            refs = me.getReferences();
        if(Ext.isEmpty(newValue)&&Ext.isEmpty(oldValue)){
            return false;
        }
        if(newValue == '10'){ // 예정
            refs.prgrField.setValue(0);
            refs.prgrField.setDisabled(true);
        }
        else if(newValue == '90'){ // 완료
            refs.prgrField.setValue(100);
            refs.prgrField.setDisabled(true);
        }
        else if(newValue == '20'){ //진행
            refs.prgrField.setValue(10);
            refs.prgrField.setDisabled(false);
        }
        else{
            refs.prgrField.setValue(null);
            refs.prgrField.setDisabled(true);
        }
    },

    onChangePrgr: function(field, newValue, oldValue, eOpts) {
        var maxValue = field.getMaxValue();
        if(newValue>maxValue){
            field.setValue(null);
        }
    },

    onTapBtnCancel: function(button, e, eOpts) {
        var me = this,
            vm = me.getViewModel(),
            refs = me.getReferences();

        me.onClose();
    },

    onTapBtnDelete: function(button, e, eOpts) {
        var me = this,
            vm = me.getViewModel(),
            refs = me.getReferences();
        var crudState = 'D';

        me.onShowConfirm('알림','정말로 삭제하시겠습니까?',function(btn){
            if(btn == 'yes'){
                me.onSave(crudState);
            }
        });

    },

    onTapBtnConfirm: function(button, e, eOpts) {
        var me = this,
            vm = me.getViewModel(),
            refs = me.getReferences();

        var crudState = 'C';

        me.onSave(crudState);
    },

    onTapBtnUpdate: function(button, e, eOpts) {
        var me = this,
            vm = me.getViewModel(),
            refs = me.getReferences();


        if(vm.get('popupData.reptData.wrtDevc')==1){
            me.onShowConfirm('알림','웹에서 작성한 내용을 모바일에서 수정할 경우 스타일이 전부 사라집니다. 그래도 수정하시겠습니까?',function(btn){
                if(btn == 'yes'){
                    me.onSave();
                }
            });
        }
        else{
            me.onSave();
        }
    },

    /* 초기화 */
    onContainerInitialize: function(component, eOpts) {

        var me = this,
            vm = me.getViewModel(),
            refs = me.getReferences();

        /* 상단 컴포넌트 정보 vm 저장해놓음 */
        var popupData = component.config.popupData;
        vm.set('popupData',popupData);

        var infoMsg = Messages.getMessage('BOM00002');
        refs.infoMsg.setHtml(infoMsg);

        if(Ext.isEmpty(popupData.reptData)){ // 신규작성
            //     refs.closeBtn.setHidden(true);   // 닫기
            refs.cancelBtn.setHidden(false); // 취소
            refs.confirmBtn.setHidden(false);// 확인
            refs.deleteBtn.setHidden(true);  // 삭제
            refs.updateBtn.setHidden(true);  // 수정
            refs.prgrField.setBind();// 진척률 바인딩 제거
        }
        else{ // 주간업무수정
            //     refs.closeBtn.setHidden(false);  // 닫기
            refs.cancelBtn.setHidden(true);  // 취소
            refs.confirmBtn.setHidden(true); // 확인
            refs.deleteBtn.setHidden(false); // 삭제
            refs.updateBtn.setHidden(false); // 수정
            if(popupData.tmrdInfo.wrtrState == 'FALSE'){ // 수정가능여부
                vm.set('disabled',true);
            }
            else{
                vm.set('disabled',false);
                refs.prgrField.setBind(); // 진척률 바인딩 제거
            }
        }


        var rolCbx = [];
        var pjtCbx = [];
        var bizCbx = [];

        for ( var i in popupData.rolList) {
            rolCbx[Number(i)] = popupData.rolList[Number(i)];
        }
        rolCbx.push({text : '기타', value : 0});

        for ( var i in popupData.prjList) {
            pjtCbx[Number(i)] = popupData.prjList[Number(i)];
        }

        for ( var i in popupData.bizList) {
            bizCbx[Number(i)] = popupData.bizList[Number(i)];
        }

        ComboboxUtils.makeCustomCbx(refs.rolCbx, rolCbx);
        ComboboxUtils.makeCustomCbx(refs.pjtCbx, pjtCbx);
        ComboboxUtils.makeCustomCbx(refs.bizCbx, bizCbx);

        // inputForm을 통한 setValues, getValues  활용을 위해 name지정 (view단에서 name지정할경우 duplicate name 에러 발생)
        refs.rolCbx.setName('hrHrocJasRolId');
        refs.pjtCbx.setName('boPrjmInfoId');
        refs.bizCbx.setName('bizDvnm');
        refs.workStcdCbx.setName('weekWorkStcd');
        refs.strdt.setName('strdt');
        refs.edt.setName('edt');

        refs.prgrField.setDisabled(true);
        refs.baseInfo.setHtml('<strong>※기준정보 : ' + DateUtils.parseDate(popupData.tmrdInfo.strdt) + ' / ' + popupData.empInfo.dpnm + '</strong>');

        refs.workStcdCbx.suspendEvents();
        refs.inputForm.setValues(popupData.reptData);


        if(refs.workStcdCbx.getValue() == '10'){ // 예정
            refs.prgrField.setDisabled(true);
        }
        else if(refs.workStcdCbx.getValue() == '90'){ // 완료
            refs.prgrField.setDisabled(true);
        }
        else if(refs.workStcdCbx.getValue() == '20'){ //진행
            refs.prgrField.setDisabled(false);
        }

        refs.workStcdCbx.resumeEvents();

        if(!Ext.isEmpty(vm.get('popupData.reptData.hrHrocJasRolId'))){
            if(!isNaN(refs.rolCbx.getInputValue())){ // 없는 사무분담일 경우 기타로 세팅
                refs.rolCbx.setValue(0);
                me.onShowAlert('알림','기준일자에 해당하는 사무분담이 없습니다.');
            }
        }



        //
    }

});