/*
 * File: app/view/Budget/exp/ExpNteApr02MViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

/*
    모바일 시스템 결재함 :: 결재함 별 결재문서 목록 - 컨트롤러

    @author BNK시스템/차장/손승범
    @since 2019.04.16
    @version 1.0
    @see

    << 개정이력(Modification Information) >>

    수정일		  수정자                수정내용
    ----------	------------------   --------------------------
    2019.04.16	BNK시스템/차장/손승범   최초 생성
    2020.07.09	BNK시스템/계장/지민영   결재문서목록 전부조회, 상세팝업에서 모바일결재여부 제어
    2020.09.16	BNK시스템/계장/지민영   (웹동기화) 연장근무보고 결재팝업(HwmOvtRept71) 추가로 인한 분기삭제
    2020.10.14	BNK시스템/계장/지민영   (웹동기화) 휴일근무보고 결재팝업(HwmHodRept71) 추가로 인한 분기삭제
    2020.10.16  BNK시스템/계장/지민영   bizDvcd 더이상 사용하지 않으므로 별도 분기처리
*/
Ext.define('BNK.view.Budget.exp.ExpNteApr02MViewController', {
    extend: 'BaseViewController',
    alias: 'controller.budget.exp.expnteapr02m',

    config: {
        viewId: 'ExpNteApr02M'
    },

    onSelect: function() {
        var me = this,
            vm = me.getViewModel(),
            store = me.getStore('ApprovalBoxStore'),
            refs = me.getReferences(),
            command = vm.get('command'),
            dpDvcdNm = null,
            selectCnt = vm.get('selectCnt'),
            tglSanMode = refs.tglSanMode;	// 일괄결재 모드 토글

        // 부서완료함일 경우 부서구분명을 추가한다.
        if(command == '97'){
            dpDvcdNm = '부서';
        }

        // 검색조건 설정후 1페이지부터 조회
        store.getProxy().extraParams = {
            command 	: command,
            searchYear 	: vm.get('searchYear'),
            vwId    	: vm.get('vwId'),
            rqprId  	: vm.get('rqprId'),
            docNo   	: vm.get('docNo'),
            dpDvcdNm	: dpDvcdNm
        };
        store.removeAll();
        store.loadPage(1);

        // (일괄결재)선택된 문서 개수 초기화
        vm.set('selectCnt', 0);

        // 미결함, 담당부서함인 경우 일괄결재 모드 툴바 활성화
        if(command == Constants.sanction.PENDING_BOX || command == Constants.sanction.RECEIPT_BOX){
            tglSanMode.setHidden(false);
        }

        // 문서 제목 최대길이 동적 설정
        me.setTitleWidth();
    },

    /* 조회버튼(기존) */
    oldOnBtnSearchTap: function(button, e, eOpts) {
        var me = this,
            searchYear = me.getViewModel().get('searchYear');
            searchVwIdStore = me.getViewModel().storeInfo.SearchVwIdStore; // 검색조건 : 결재문서명 데이터
        // 팝업창 생성 및 데이터전달
        var win = Ext.create('BNK.view.Budget.exp.ExpNteApr03M', {
            searchYear : searchYear,
            searchVwIdStore : searchVwIdStore
        });
        // 팝업창에서 이벤트 호출시 실행되는 함수
        me.mon(win, 'search', function(data, popup) {
            var me = this,
                vm = me.getViewModel(),
                vwNm = '전체문서';

            // 팝업창 닫기
            popup.close();

            // 결재문서명
            if (data.vwId) {
                var items = vm.storeInfo.SearchVwIdStore.getData().items;
                for (var i in items) {
                    var item = items[i].data;
                    if (data.vwId === item.value) {
                        vwNm = item.text;
                        break;
                    }
                }
            }

            vm.set('searchYear', data.searchYear);	// 기준연도
            vm.set('vwId', data.vwId);	   			// 결재문서아이디
            vm.set('vwNm', vwNm);		   			// 결재문서명
            vm.set('rqprId', data.rqprId); 			// 사번

            me.onSelect(); // 조회
        }, me);

        win.show(); // 팝업창표시
    },

    /* 해상도에 맞게 툴바 문서 제목 최대길이 변경하기 */
    setTitleWidth: function() {
        var me = this,
            refs = me.getReferences(),
            tbrLbExpTitle = refs.tbrLbExpTitle;

        // 현재 화면의 해상도 가져오기
        var viewSize = Ext.getBody().getViewSize();
        var width = viewSize.width;
        var rWidth = 0;

        if(width != undefined && width > 0){
            rWidth = width - 120;
        }

        var style = "max-width:" + rWidth + "px;";

        // 제목 스타일 설정
        tbrLbExpTitle.setStyle(style);
    },

    /* 그리드 체크박스(일괄결재를 위한 row 선택) 이벤트 */
    onCbxChange: function(checkcell, rowIndex, checked, record, e, eOpts) {
        var me = this,
            vm = me.getViewModel(),
            cellChecked = checkcell.getValue(),
            selectCnt = vm.get('selectCnt'),
            aprHistId = record.id,
            vwId = record.data.vwId;

        // 모바일 결재여부판단 (mobYn)
        if(record.data.mobYn == 'N') {
            Ext.Msg.alert('알림', '해당 문서는 모바일에서 결재할 수 없습니다.');
            return;
        }

        // 일괄결재 가능한 최대 개수 확인
        if(selectCnt == 10 && !cellChecked == true){
            Ext.Msg.alert('알림', '일괄결재는 최대 10건까지 가능합니다.');
            return;
        }

        // 세금계산서, 여비정산서는 모바일에서 결재불가. 해당 경우 제외하기
        if(vwId == 'BgxNfmAply71'){
            Ext.Ajax.request({
                headers : {
                    serviceId : 'COMAPR0001R04M'
                },
                jsonData:{
                    aprHistId : aprHistId
                },
                success : function(response, scope) {
                    var res = Ext.JSON.decode(Ext.JSON.decode(response.responseText).result);
                    var aplKndCd = res.docData.afterchange.applyInfo.aplKndcd;

                    if(aplKndCd == Constants.aplKndcd.TXINV || aplKndCd == Constants.aplKndcd.XPNS){ // 세금계산서, 여비정산서인 경우
                        Ext.Msg.alert('알림', '해당 문서는 모바일에서 결재할 수 없습니다.');
                        return;
                    }

                    // 체크박스 체크 처리
                    checkcell.setValue(!cellChecked);
                    // 체크된 record 상태값 처리
                    record.set('checked', !cellChecked);

                    // 선택문서 개수 처리
                    if(cellChecked){
                        vm.set('selectCnt', selectCnt - 1);
                    }else{
                        vm.set('selectCnt', selectCnt + 1);
                    }
                },
                failure : function(response){
                    Ext.Msg.alert('오류', '결재 정보를 가져오는데 실패했습니다.');
                    return;
                }
            });
        }else{
            // 체크박스 체크 처리
            checkcell.setValue(!cellChecked);
            // 체크된 record 상태값 처리
            record.set('checked', !cellChecked);

            // 선택문서 개수 처리
            if(cellChecked){
                vm.set('selectCnt', selectCnt - 1);
            }else{
                vm.set('selectCnt', selectCnt + 1);
            }
        }
    },

    /* 일괄결재 모드 토글 이벤트 */
    onTglSanModeChange: function(togglefield, newValue, oldValue, eOpts) {
        debugger;
        var me = this,
            refs = me.getReferences(),
            vm = me.getViewModel(),
            modeSan = vm.get('modeSan');

        if(newValue){ // 일괄결재 모드 ON
            modeSan = true;
        }else{ // 일괄결재 모드 OFF
            modeSan = false;
        }
        vm.set('modeSan', modeSan);
    },

    /* 조회버튼 */
    onBtnSearchTap: function(button, e, eOpts) {
        var me = this,
            searchYear = me.getViewModel().get('searchYear'),
            searchVwIdStore = me.getViewModel().storeInfo.SearchVwIdStore, // 검색조건 : 결재문서명 데이터
            vm = me.getViewModel(),
            command = vm.getData().command,
            data = {
                command : command,
                searchYear : searchYear
            };

        if(command == Constants.sanction.DEPT_COMPLETED_BOX){ // 부서완료함인 경우 부서구분 포함
            data.dpDvcdNm = '부서';
        }

        searchVwIdStore.removeAll();
        Ext.Ajax.request({
            headers : {
                //serviceId : 'ApprovalBoxSvc.findOneEdocCodeList'
                serviceId : 'COMAPR0001R03M'
            },
            jsonData:data,
            success : function(response, scope) {
                //         var code = [ {
                //           code : 'EdocMgnt',
                //           text : Constants.comboBoxText.defaultText,
                //           value : ''
                //         } ];

                /*기존소스 주석*/
                /*var res = JSON.parse(response.responseText);
                for (var i in res.result) {
                var record = {
                //                 code : 'EdocMgnt',
                text : res.result[i].edocNm,
                value : res.result[i].edocCd
            };
            //           code.push(record);
            searchVwIdStore.add(record);
        }*/

        // 결재 조회 조건을 리스트에 있는 것들만으로 전달
        var res = JSON.parse(response.responseText);
        var edocCodeList = res.edocCodeList;

        for (var i in edocCodeList) {
            var record = {
                text : edocCodeList[i].edocNm,
                value : edocCodeList[i].edocCd
            };
            searchVwIdStore.add(record);
        }


        // 팝업창 생성 및 데이터전달
        var win = Ext.create('BNK.view.Budget.exp.ExpNteApr03M', {
            searchYear : searchYear,
            searchVwIdStore : searchVwIdStore,
            command : command
        });

        // 팝업창에서 이벤트 호출시 실행되는 함수
        me.mon(win, 'search', function(data, popup) {
            var me = this,
                vm = me.getViewModel(),
                vwNm = '전체문서';

            // 팝업창 닫기
            popup.close();

            // 결재문서명
            if (data.vwId) {
                var items = vm.storeInfo.SearchVwIdStore.getData().items;
                for (var i in items) {
                    var item = items[i].data;
                    if (data.vwId === item.value) {
                        vwNm = item.text;
                        break;
                    }
                }
            }

            vm.set('searchYear', data.searchYear);  // 기준연도
            vm.set('vwId', data.vwId);	   			// 결재문서아이디
            vm.set('vwNm', vwNm);		   			// 결재문서명
            vm.set('rqprId', data.rqprId); 			// 사번

            me.onSelect(); // 조회
        }, me);

        win.show(); // 팝업창표시
    }
});
    },

    onGridSelect: function(dataview, selected, eOpts) {
        var me = this,
            vm = me.getViewModel(),
            record = selected[0].data;

        var refs = me.getReferences(),
            gridExpNteApr = refs.gridExpNteApr;

        // 선택한 결재선 레코드. 동시성제어에 사용
        vm.set('record', record);

        // 결재이력데이터조회
        Ext.Ajax.request({
            headers : {
                serviceId : 'COMAPR0001R04M',
                viewId : 'ExpNteApr02M'
            },
            scope : me,
            jsonData : {
                aprHistId : record.id // 결재이력아이디
            },
            success : function(response) {
                var me = this,
                    refs = me.getReferences(),
                    vm = me.getViewModel(),
                    command = vm.get('command'),
                    responseJson = Ext.JSON.decode(Ext.JSON.decode(response.responseText).result);

                if (!responseJson) {
                    Ext.Msg.alert('안내', '결재이력데이터가 존재하지 않습니다.');
                    return;
                }

                vm.set('responseJson', responseJson);

                var edocCd = responseJson.edocCd;
                /* 2020.10.16  BNK시스템/계장/지민영   bizDvcd 더이상 사용하지 않음
                if(responseJson.bizDvcd == 'HWM' && edocCd.substring(edocCd.length-2, edocCd.length) == '72'){ */
                if (edocCd.substring(0,3) == 'Hwm' && (edocCd.substring(edocCd.length-2, edocCd.length) == '72'
                || edocCd.substring(edocCd.length-2, edocCd.length) == '74')) {
                    // 연장근무, 휴일근무 보고서를 사용하지 않을 경우에는 73으로 변경
                    edocCd = edocCd.substring(0, edocCd.length-2) + '71'; // TODO: 각 근태취소신청서 화면 따로만들지 않고 처리.. 개선 필요.
                } else if(edocCd == 'ExpNteDoc71'){
                    edocCd = 'ExpNteAply71'; // TODO: 지출결의서 취소신청서는 ExpNteAply71을 보도록 처리함
                    /*             2020.09.16	BNK시스템/계장/지민영   (웹동기화) 연장근무보고 결재팝업(HwmOvtRept71) 추가로 인한 분기삭제
                    } else if(edocCd == 'HwmOvtRept71'){
                    edocCd = 'HwmOvtAply71'; */
                    /*             2020.10.14	BNK시스템/계장/지민영   (웹동기화) 휴일근무보고 결재팝업(HwmHodRept71) 추가로 인한 분기삭제
                    } else if(edocCd == 'HwmHodRept71'){
                    edocCd = 'HwmHodAply71'; */
                }

                var aprViewId = edocCd + 'M';	// 모바일일경우, 화면이름에 M을 붙여처리함
                //         var aprViewId = responseJson.edocCd + 'M';	// 모바일일경우, 화면이름에 M을 붙여처리함

                // 모바일 결재여부판단 (mobYn)
                if(record.mobYn == 'N') {
                    aprViewId = 'ApprovalEmptyPopupM';
                }

                var classname = me.GET_CLASS_NAME(aprViewId);
                if (!classname) {
                    //             Ext.Msg.alert('안내', Ext.String.format('{0}에 해당하는 파일이 존재하지 않습니다.', aprViewId));
                    Ext.Msg.alert('안내', Ext.String.format('{0}에 해당하는 파일이 존재하지 않습니다.', responseJson.docNm));
                    return;
                }

                // 부서완료함(97)과 담당자완료함(98)은 완료함(94)과 동일한 기능을 하도록 설정
                var commandArr = ['97', '98'];
                if(commandArr.includes(command)){
                    command = '94';
                }

                // 과거데이터와 호환성을 위한처리 추가
                var aprHistId = responseJson.aprHistId,
                    docData = responseJson.docData;
                if (!docData) {
                    docData = {};
                    if (responseJson.fieldValues)  docData.fieldValues  = responseJson.fieldValues;
                    if (responseJson.afterchange)  docData.afterchange  = responseJson.afterchange;
                    if (responseJson.beforechange) docData.beforechange = responseJson.beforechange;
                }
                if (!aprHistId) {
                    aprHistId = vm.get('record').id;
                }
                // end of 과거데이터와 호환성을 위한처리 추가

                var win = Ext.create(aprViewId, {
                    command : command,
                    aprHistId : aprHistId,
                    docData : docData,
                    record : vm.get('record')
                });

                me.mon(win, 'complete', function(popup) {
                    popup.close(); //팝업창닫기
                    me.onSelect();
                }, me);

                win.show();
            }
        });


    },

    initialize: function(component, eOpts) {
        var me = this,
            config = component.initialConfig,
            vm = me.getViewModel(),
            searchVwIdStore = me.getViewModel().storeInfo.SearchVwIdStore;

        vm.set('searchYear', new Date().getFullYear());
        vm.set('command', config.command);
        // 일괄결재 모드 초기화
        vm.set('modeSan', false);
        // 선택된 결재 문서 개수 초기화
        vm.set('selectCnt', 0);

        // 조회
        me.onSelect();

        /*
        // 검색조건 : 결재문서명 코드조회
        me.GET_CODELIST({
            codeDvcd : 'EDOC_MGNT'
        }, me).then(function(result) {
            var me = result.scope,
                data = result.data,
                vm = me.getViewModel(),
                searchVwIdStore = vm.storeInfo.SearchVwIdStore;

            searchVwIdStore.removeAll();
            searchVwIdStore.add(data);

            // 조회
            me.onSelect();
        });
        */
    },

    /* 일괄결재 버튼 클릭 이벤트 */
    onBtnSanTap: function(button, e, eOpts) {
        var me = this,
            refs = me.getReferences(),
            vm = me.getViewModel(),
            grid = refs.gridExpNteApr,
            batchType = Constants.sanction.SANCTION,
            command = vm.get('command'),
            selectCnt = vm.get('selectCnt');

        // 선택한 결재가 없는 경우
        if(selectCnt == 0){
            Ext.Msg.alert('알림', '선택한 결재가 없습니다.');
            return;
        }

        // 일괄결재 의사 묻기
        Ext.Msg.confirm('일괄결재', '선택한 ' + selectCnt + '건을 일괄결재 하시겠습니까?', function(btn) {
            if (btn == 'yes') {
                // 결재함에 따른 분류
                if(command == Constants.sanction.PENDING_BOX) { // 미결함
                    command = Constants.sanction.SANCTION;    //결재
                } else if(command == Constants.sanction.RECEIPT_BOX){ // 담당자접수함
                    command = Constants.sanction.DRAFT;       //기안
                }

                // 체크한 결재 리스트 생성하기
                var selectedRowList = [];
                var data = grid.getJsonAllRecords();
                for(var i in data){
                    if(data[i].checked){
                        selectedRowList.push(data[i]);
                    }
                }

                // 일괄결재
                Ext.Ajax.request({
                    headers : {
                        serviceId 	: 'ApprovalBoxSvc.saveComAprHistBatch',
                        viewId 		: 'ExpNteApr02M'
                    },
                    scope : me,
                    jsonData : {
                        aprHistList 	: selectedRowList,	//체크한 결재리스트
                        command 		: command,      	//boxCommand
                        batchType 	: batchType			//일괄결재 or 일괄확인
                    },
                    success : function(response) {
                        var me = this,
                            refs = me.getReferences(),
                            vm = me.getViewModel(),
                            command = vm.get('command'),
                            responseJson = Ext.JSON.decode(response.responseText);

                        if(responseJson.success){
                            Ext.Msg.alert('완료', '일괄결재 처리 완료했습니다.');
                        }
                        me.onSelect();
                    },
                    failure : function(response, opts) {
                        Ext.Msg.alert('오류', '일괄결재 도중 오류가 발생했습니다.');
                    }
                });
            }
        });


    },

    onJsonstoreLoad: function(store, records, successful, operation, eOpts) {
        var me = this;
        var refs = me.getReferences();
        var vm = me.getViewModel();

        if(vm.get('command') == Constants.sanction.PENDING_BOX && records.length <= 0) {
            refs.infoMsg.setHtml('<marquee style="color:red; padding:5px 5px 0px 5px">※해당연도에는 결재건이 없습니다. 미결함 표시가 되어 있다면 이전연도 확인 부탁드립니다.</marquee>');
        }
        else {
            refs.infoMsg.setHtml('');
        }

        // 선택된 문서 개수 초기화
        var selectCnt = vm.get('selectCnt');
        vm.set('selectCnt', 0);
    }

});