/*
 * File: app/view/Budget/exp/ExpNteRcpt01MViewModel.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

/*
    모바일 시스템 경비노트 :: 기타영수증 지출결의서 작성 - 모델

    @author BNK시스템/계장/김정균
    @since 2019.04.22
    @version 1.0
    @see

    << 개정이력(Modification Information) >>

    수정일		  수정자                수정내용
    ----------	------------------   --------------------------
    2019.04.22	BNK시스템/계장/김정균   최초 생성
*/
Ext.define('BNK.view.Budget.exp.ExpNteRcpt01MViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.ExpNteRcpt01MViewModel',

    data: {
        command: null,
        aplTct: 0,
        aplTotSmamt: 0,
        aplTotSmamtRender: 0,
        moneyList: [
            
        ],
        applyLine: null
    }

});