/*
 * File: app/view/Budget/exp/ExpNteRcpt71MItemsViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

/*
    모바일 시스템 경비노트 :: 기타영수증 현황, 결재함 상세보기 depth 3 - 컨트롤러

    @author BNK시스템/계장/김정균
    @since 2019.04.22
    @version 1.0
    @see

    << 개정이력(Modification Information) >>

    수정일		  수정자                수정내용
    ----------	------------------   --------------------------
    2019.04.22	BNK시스템/계장/김정균   최초 생성
*/
Ext.define('BNK.view.Budget.exp.ExpNteRcpt71MItemsViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.ExpNteRcpt71MItemsViewController',

    config: {
        viewId: 'ExpNteRcpt71MItems'
    },

    search: function() {
        //Ext.toast('사원조회 (search함수구현필요)', 1000);
    },

    /* 원화 표시 */
    curr: function(value) {
        if (value) {
            var str = String(value);
            var result = str.replace(/(\d)(?=(?:\d{3})+(?!\d))/g, '$1,');
            result += ' 원';

            return result
        } else {
            return 0;
        }

    },

    /* 폼 renderer */
    formRenderer: function(data) {
        if(data){
            if(data.apvlDt){
                data.apvlDtText = DateUtils.parseDate(String(data.apvlDt));
            }

            data.trnsAmtWcText = this.curr(data.trnsAmtWc);
            data.stxatText = this.curr(data.stxat);
            data.apvlAmtDomText = this.curr(data.apvlAmtDom);

        //     if(data.mcBzno){
            if(data.mcBzno !== null && String(data.mcBzno).length > 0){
                var strMcBzno = String(data.mcBzno);

                if(strMcBzno.length === 10){
                    data.mcBznoText = strMcBzno.substring(0,3) + "-" + strMcBzno.substring(3, 5) + "-" + strMcBzno.substring(5, 10);
                }else if(strMcBzno.length === 13){
                    data.mcBznoText = strMcBzno.substring(0,6) + "-" + strMcBzno.substring(6, 13);
                }else{
                    data.mcBznoText = strMcBzno;
                }
            }

            // 사용분류 text 로 변환
            data.accItemCdText = CodeUtils.getText('NTE011', data.accItemCd);
            // 취소여부 text 로 변환
            data.canYnText = CodeUtils.getText('NTE008', data.canYn);

            // 결제방법
            data.stlmDvcdText = CodeUtils.getText('NTE014', data.stlmDvcd);

        }

    },

    gridRenderer: function(value, record, dataIndex, cell, column) {
        switch(dataIndex) {
            case 'jasPrj': // 사용부문

                var me = this,
                    vm = me.getViewModel(),
                    prjStoreItems = vm.get('prjStore').data.items,
                    userInfoList = vm.get('etcItem.userInfoList'),
                    result = '',
                    i = 0,
                    item = null;

                column.setEditor(false);

                if (!value) {
                    return '';
                } else {
                    result = record.get('jasPrjText');
                }

        //         // 사용부문이 존재하지 않는 경우를 결재처리로 판단하여 렌더링 처리진행함
        //         if (prjStoreItems && prjStoreItems.length > 0) {
        //             for (i in prjStoreItems) {
        //                 item = prjStoreItems[i].data;
        //                 if (value === item.value) {
        //                     result = item.text;
        //                     record.hrHromJasPrjText = item.text;
        //                     break;
        //                 }
        //             }
        //             // 결재처리시 사용부문이력값을 사용하기 위해 jasPrjText 값으로 저장함
        //             for (i in userInfoList) {
        //                 item = userInfoList[i];
        //                 if (record.data.hrHrpmEmpId === item.hrHrpmEmpId) {
        //                     item.jasPrjText = result;
        //                     break;
        //                 }
        //             }
        //         }
        //         else {
        //             // 사용부문이력값을 렌더링값으로 사용
        //             result = record.data.jasPrjText;
        //         }

                return result;
        }
    },

    onConferencePopup1: function(button, e, eOpts) {
        var me = this;
        var vm = me.getViewModel();
        var popupData = {};

        vm.set('data.mtg.conferenceView', true); // 날짜, 시간 displayField hidden

        if(vm.get('data.mtg')){
            popupData = vm.get('data.mtg');
        } else {
            popupData = {};
        }

        // 팝업창 생성 및 데이터전달
        var win = Ext.create('conferencePopupM', popupData);
        // 팝업창에서 이벤트 호출시 실행되는 함수
        me.mon(win, 'selected', function(data, popup) {}, me);

        win.show(); // 팝업창표시
    },

    onFindUser1: function(button, e, eOpts) {
        var me = this;
        var vm = me.getViewModel();
        // 팝업창 생성 및 데이터전달
        var win = Ext.create('FindUserPopupM', {
            accItemCd : vm.get('etcItem.accItemCd'),
            gridData : vm.get('etcItem.gridData')
        });
        // 팝업창에서 이벤트 호출시 실행되는 함수
        me.mon(win, 'selected', function(data, popup) {
            var me = this;

            // 사용자 팝업에서 선택한 사용자들 기억하여 다시 사용자 팝업으로 돌려주기
            var gridData = data.items;
            if(gridData && gridData.length > 0){
                vm.set('etcItem.gridData', []);
                for(var row in gridData){
                    vm.get('etcItem.gridData').push(gridData[row]);
                }
            }


            var result = '';
            var userInfoList = [];

            var hrHromJasPrjId = null;

            if(vm.get('etcItem.hrHromJasPrjId')){ // 사용부문
                hrHromJasPrjId = vm.get('etcItem.hrHromJasPrjId');
            }

            for(var i in data.items){
                userInfoList[i] = data.items[i].data;
                userInfoList[i].hrHromJasPrjId = hrHromJasPrjId;

                result += data.items[i].data.empeNm + '(' + data.items[i].data.dpnm + ')';
                if(i != data.items.length - 1){
                    result += ', ';
                }
            }

            vm.set('etcItem.userInfoList', userInfoList);
            vm.set('etcItem.userOrUseDept', result);

            var jasPrjRefs = this.getView().getReferences().jasPrj;
            var userNotEmpty = vm.get('etcItem.userOrUseDept');
            if(userNotEmpty && userNotEmpty.length > 0){
                jasPrjRefs.setDisabled(false);
            } else if(!userNotEmpty || userNotEmpty === '' || userNotEmpty.length === 0){
                jasPrjRefs.setDisabled(true);
                vm.set('etcItem.hrHromJasPrjId', null);
                vm.set('etcItem.hrHromJasPrjText', null);
                jasPrjRefs.setValue(null);
            }

            // 2019-07-30 손승범 사용자별 사용부문처리를 위해 추가
            var records = [];
            for (i in gridData) {
                data = gridData[i].data;
                // 사용자명 포매팅 추가설정
                data.formattedEmpeNm = Ext.String.format('{0}({1})', data.empeNm, data.dpnm);
                records.push(data);
            }
            vm.get('hrHromJasPrjStore').add(records);
        }, me);

        win.show(); // 팝업창표시
    },

    onBtnSalesCheck: function(button, e, eOpts) {
        var me = this,
            vm = me.getViewModel(),
            records = vm.get('data'),
            win = Ext.create('ExpNteRcpt51M', {
                records : records,
                etcReceipt : true
            });

        // me.mon(win, 'selected', function(data, popup) {

        // }, me);

        win.show();


    },

    /* 화면초기화 */
    initialize: function(component, eOpts) {
        var me = this;
        var vm = me.getViewModel();
        var refs = me.getReferences();

        // 텍스트필드들에 뿌려줄 데이터
        var data = component.getData();
        var userInfoList = data.userInfoList;
        if (userInfoList && userInfoList.length > 0) {
            vm.get('hrHromJasPrjStore').add(userInfoList);
        }
        // 회의비인 경우만 버튼 보이기 & 활성화
        if(data.accItemCd === '06'){ // NTE011
            refs.conference.setHidden(false);
            refs.conference.setDisabled(false);
        } else {
            refs.conference.setHidden(true);
        }

        me.formRenderer(data); // 데이터 형식 render
        vm.set('data', data);

        var imgPhoto = refs.imgPhoto;

        imgPhoto.setSrc(data.imgPhoto);
        if(!imgPhoto.getSrc()){
            imgPhoto.setSize(0, 0);
        } else {
            imgPhoto.setSize("100%", 300);
        }

    }

});