/*
 * File: app/view/Budget/exp/ExpNteRcpt01MViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

/*
    모바일 시스템 경비노트 :: 기타영수증 지출결의서 작성 - 컨트롤러

    @author BNK시스템/계장/김정균
    @since 2019.04.22
    @version 1.0
    @see

    << 개정이력(Modification Information) >>

    수정일		  수정자                수정내용
    ----------	------------------   --------------------------
    2019.04.22	BNK시스템/계장/김정균   최초 생성
    2020.06.24  BNK시스템/계장/지민영   20.07.01 예산오픈으로 인한 분기처리 추가
*/
Ext.define('BNK.view.Budget.exp.ExpNteRcpt01MViewController', {
    extend: 'BaseViewController',
    alias: 'controller.ExpNteRcpt01MViewController',

    config: {
        viewId: 'ExpNteRcpt01M'
    },

    /* 기타영수증 필수값 검증 */
    formValid: function(formData) {
        var me = this,
            vm = me.getViewModel(),
            refs = me.getReferences(),
            reNo = /[^\d]/,
            errMsg = '';

        if(formData.apvlDt){
            if(formData.apvlDt && String(formData.apvlDt).length !== 8){
                errMsg += '승인일자는 숫자 8자리입니다.<br>';
            } else if(Number(formData.apvlDt) >= 20200701) {
                /* 20.07.01 예산오픈으로 인한 분기처리 */
                errMsg += '2020-07-01 부터는 [경비신청]-[결의서 작성] 메뉴를 이용바랍니다.<br>';
            }

            //     if(reNo.test(formData.apvlDt)){
            //         errMsg += '승인일자는 숫자만 입력해주세요.<br>';
            //     }
            if(String(formData.apvlDt).substr(0, 4) < '2000' ||
               String(formData.apvlDt).substr(0, 4) > '2100' ||
               String(formData.apvlDt).substr(4, 2) > '12' ||
               String(formData.apvlDt).substr(6, 2) > '31'){
                errMsg += '승인일자는 날짜형식으로 입력해주세요.<br>';
            }
        } else {
            errMsg += '승인일자를 입력해주세요.<br>';
        }

        if(!formData.aprno){
            errMsg += '승인번호를 입력해주세요.<br>';
        }
        if(formData.aprno && String(formData.aprno).length > 11){
            errMsg += '승인번호는 최대 11자리입니다.<br>'; // 승인번호 : 숫자 + 알파벳
        }
        // if(formData.aprno && reNo.test(formData.aprno)){
        //     errMsg += '승인번호는 숫자만 입력해주세요.<br>';
        // }

        // if(!formData.canYn){
        //     errMsg += '취소여부<br>';
        // }
        if(!formData.mcNm){
            errMsg += '상호명을 입력해주세요.<br>';
        }

        // if(!formData.mcBzno){
        if(formData.mcBzno === null || String(formData.mcBzno).length < 1){
            errMsg += '사업자번호를 입력해주세요.<br>';
        }
        if(formData.mcBzno && String(formData.mcBzno).length > 10){
            errMsg += '사업자번호는 최대 숫자 10자리입니다.<br>';
        }
        // if(formData.mcBzno && reNo.test(formData.mcBzno)){
        //     errMsg += '사업자번호는 숫자만 입력해주세요.<br>';
        // }

        // if(!formData.mcAddr){
        //     errMsg += '주소<br>';
        // }
        if(!formData.trnsAmtWc){
            errMsg += '공급가액을 입력해주세요.<br>';
        }
        if(formData.trnsAmtWc && String(formData.trnsAmtWc).length > 13){
            errMsg += '공급가액은 최대 숫자 13자리입니다.<br>';
        }

        if(formData.stxat === undefined || formData.stxat === null || formData.stxat < 0){
            errMsg += '부가세를 입력해주세요.<br>';
        }
        if(formData.stxat && String(formData.stxat).length > 13){
            errMsg += '부가세는 최대 숫자 13자리입니다.<br>';
        }

        if(!formData.apvlAmtDom){
            errMsg += '승인금액을 입력해주세요.<br>';
        }
        if(formData.apvlAmtDom && String(formData.apvlAmtDom).length > 13){
            errMsg += '승인금액은 최대 숫자 13자리입니다.<br>';
        }
        // if(formData.apvlAmtDom && reNo.test(formData.apvlAmtDom)){
        //     errMsg += '승인금액은 숫자만 입력해주세요.<br>';
        // }

        // if(!formData.hrHromJasPrjId){
        //     errMsg += '사용부문을 입력해주세요.<br>';
        // }
        if(!formData.userOrUseDept){
            errMsg += '사용자를 입력해주세요.<br>';
        }
        var userInfoList = formData.userInfoList;
        for (var i in userInfoList) {
            var record = userInfoList[i];
            // 내부직원(01)이면서 사용부문이 존재하지 않는 경우, 오류메시지표시
            if (record.stfDvcd === '01' && !record.jasPrj) {
                errMsg += '내부직원의 사용부문을 선택해주세요.<br>';
                break;
            } else if (record.stfDvcd !== '01'){
                // 외부직원인 경우, 사용부문이 적용되는 버그가 존재하여 데이터 보정처리함
                record.jasPrj = null;
                record.jasPrjText = null;
            }
        }

        if(!formData.accItemCd){
            errMsg += '사용분류를 입력해주세요.<br>';
        }
        if(!formData.aplRscn){
            errMsg += '적요를 입력해주세요.<br>';
        }
        if(formData.aplRscn){
            if(formData.aplRscn.length > 65){
                errMsg += '적요의 길이를 확인해주세요.<br>';
            }
        }
        if(!formData.hrHrpmDeptId){
            errMsg += '사용부서를 입력해주세요.<br>';
        }
        // if(!formData.userOrUseDept){
        //     errMsg += '사용자를 입력해주세요.<br>';
        // }

        var innerEmp = true;
        for(var i in formData.gridData){
            if(formData.gridData[i].data.stfDvcd === '02'){
                innerEmp = false;
            }
        }
        if(formData.accItemCd !== '09' && !innerEmp){  // && 외부 사용자 있는지 체크
            errMsg += '사용분류가 업무추진비인 경우만 외부직원을 추가할 수 있습니다. 외부직원은 제외해 주시기바랍니다.<br>';
        } else if(formData.accItemCd === '09' && innerEmp){
            errMsg += '사용분류가 업무추진비인 경우, 외부직원 입력은 필수입니다.<br>';
        }

        // 사용분류 === 회의비인 경우 회의록이 필수
        if(formData.accItemCd &&
           formData.accItemCd === '06' &&
           !formData.conferencePopupSuccess){
            errMsg += '사용분류가 회의비인 경우 회의록을 작성해주세요.<br>';
        }


        // + 버튼을 눌렀을때에는 결재선 체크 X
        if(!formData.btnPlus){
            if(!vm.get('applyLine')){
                errMsg += '결재선을 선택해주세요.<br>';
            }
        }

        if(!formData.imgPhoto){
            errMsg += '사진을 등록해 주세요.<br>';
        }

        return errMsg;


    },

    onClickDraft: function() {
                var me               = this,
                    vm               = me.getViewModel(),
                    refs             = me.getReferences(),
                    approvalLineGrid = refs.approvalLineGrid,
                    // 최초기안시 null, 전자문서담당자 기안시 aprHistId 설정
                    aprHistId        = null,
                    docNm = '기타영수증 지출결의서';

                // 결재선 [기안] 처리
                ApprovalBoxSvc.draft({
                    scope                 : me,
                    edocCd                : 'ExpNteRcpt71',				 	 		// 전자문서관리에서 설정된 문서코드: 화면ID를 사용함
                    docNm                 : docNm, 							 		// 문서명
                    bizDvcd               : 'Exp', 							 		// 업무구분코드
                    bizServiceId          : 'ExpNteSvc.saveExpNteAplyEtcReceipt',   // 연관 업무서비스ID
                    aprHistId             : null,						 	 		// 결재이력ID
                    approvalLineRecords   : approvalLineGrid.getJsonAllRecords(), 	// 결재선 그리드 데이터
                    docData               : {								 		// 결재문서 데이터
                        fieldValues       : vm.get('fieldValues'),
                        beforechange      : null,
                        afterchange       : vm.get('afterchange') 			 // 결재문서 필드값
                    }
                });



    },

    onComplete: function() {
        var me = this,
            vm = me.getViewModel(),
            successPopupData = vm.get('successPopupData');

        var win = Ext.create('ExpNteAply51M', successPopupData); // 결과 완료 팝업

        me.mon(win, 'destroy', function() {
            var me = this,
                //home = Ext.getCmp(Property.ROUTE_HOME),
                home = this.getView().up(Property.ROUTE_HOME),
                naviView = home.lookup('NaviView'),
                backButton = naviView.getNavigationBar().getBackButton();

            backButton.onTap();	// 뒤로가기

        }, me);

        win.show();
    },

    /* [목록]버튼선택 */
    onBtnListTap: function(button, e, eOpts) {
        var me = this,
            refs = me.getReferences(),
            form = refs.form;

        form.reset(true);
        me.showView(0);
    },

    /* 결재선 버튼 클릭 이벤트 */
    onBtnAplyLineTap: function(button, e, eOpts) {
        var me = this,
            vm = me.getViewModel(),
            win = Ext.create('BNK.view.common.ApprovalLinePopup', {});



        me.mon(win, 'selected', function(data, popup) {
            var me = this,
                vm = me.getViewModel(),
                refs = me.getReferences(),
                approvalLineGrid = refs.approvalLineGrid;

            // 부장일때 validation 통과해버리는 문제
            if(data.length > 0){
                vm.set('applyLine', data);
            } else {
                return false;
            }

            ApprovalBoxSvc.setApprovalLine({
                scope               : me,
                command             : '01', // 결재선구분자 : 기안(01)
                approvalLineGrid    : approvalLineGrid,   // 결재선 그리드 객체
                approvalLineRecords : data        // 결재선선택 데이터
            });

            popup.close();
        }, me);

        win.show();
    },

    /* 결재 버튼 클릭 이벤트 */
    onBtnAplyTap: function(button, e, eOpts) {
        var me = this,
            vm = me.getViewModel(),
            refs = me.getReferences(),
            items = [],
            k = 0,
            innerItems = this.getView().getReferences().item_container.getReferences().items.innerItems;

        // 입력값 검증 후 작성 데이터 items[] 에 모으기
        for(var i in innerItems){
            var innerVm = innerItems[i].getViewModel();
            var formData = innerVm.get('etcItem');

            // + 버튼이 아님(formValid 에서 필요)
            formData.btnPlus = false;
            if(formData.useYn){
                var errMsg = this.formValid(formData);
                if(errMsg.length > 0){
                    Ext.Msg.alert('입력값을 확인해주세요.', errMsg);
                    return false;
                }
            }

            // 입력받은 데이터
            if(vm.data.moneyList[formData.atomItemIdx] !== null && formData.useYn){
                items[k] = formData;
                items[k].canYn = 'N';
                items[k].mcAddr = ' ';
                items[k].stlmDvcd = '09';

                // 화면에서 입력받지 않지만 not null 인 경우
                items[k].trnsStcd = '02';
                k++;
            }
        }


        // [START] 기안처리 후, 완료팝업에서 데이터 사용을 위해 저장함
        var successPopupData = {
            paymentTitle   : '기타영수증 결재',
            aplTct : vm.get('aplTct'), // 총 건수
            aplTotSmamt : vm.get('aplTotSmamt'), // 합계금액
            aplTotSmamtRender : vm.get('aplTotSmamtRender') // render 합계금액
        };
        vm.set('successPopupData', successPopupData);
        // [END] 기안처리 후, 완료팝업에서 데이터 사용을 위해 저장함

        // 각각 영수증 정보들
        vm.set('items', items);

        // [START] 결재에 필요한 데이터
        var aplTotSmamt = String(vm.get('aplTotSmamt')).replace(/,/gi, '');
        aplTotSmamt = aplTotSmamt.replace(/ 원/gi, '');

        var afterchange = {
            items : items,
            stlmDvcd : '09',
            aplStcd : '10',
            aplTct : vm.get('aplTct'), // 총 건수
            aplTotSmamt : aplTotSmamt, // 합계금액
        };
        vm.set('afterchange', afterchange);
        // [END] 결재에 필요한 데이터

        // 기안
        this.onClickDraft();


    },

    /* 화면초기화 */
    initialize: function(component, eOpts) {
        var me = this;
        var vm = me.getViewModel();

        // 결재문서 초기화 설정
        ApprovalBoxSvc.setup({
            command   : '01',
            viewModel : vm,
            edocCd    : 'ExpNteRcpt71',
            scope     : me
        });

    }

});