/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({

});


Ext.application({
    stores: [
        'MenuStore',
        'CodeStore',
        'MessageStore',
        'PropertyStore'
    ],
    views: [
        'common.Error404',
        'common.ApprovalLinePopup',
        'common.ApprovalLineGrid',
        'common.ApprovalCommentPopUp',
        'common.EdocButtonContainer',
        'Budget.exp.ExpNteApr03M',
        'common.NewMain',
        'Budget.exp.ExpNteApr01M',
        'Budget.exp.ExpNteApr02M',
        'Budget.exp.ExpNteAply02M',
        'Budget.exp.ExpNteDoc01M',
        'Budget.exp.ExpNteAply01M',
        'Budget.exp.ExpNteRcpt71M',
        'Budget.exp.ExpNteRcpt71MContainer',
        'Budget.exp.ExpNteRcpt71MItems',
        'common.VersionInfomationManagementM',
        'HumanResource.hwm.HwmOutAply01M',
        'HumanResource.hwm.HwmOutAply02M',
        'HumanResource.hwm.HwmOvtAply11M',
        'HumanResource.hwm.HwmVctAply01M',
        'HumanResource.hwm.HwmVctAply02M',
        'HumanResource.hrp.HrpOgiDept51M',
        'HumanResource.hwm.HwmMthEmpe01M',
        'HumanResource.hwm.HwmYthEmpe01M',
        'HumanResource.hwm.HwmHodAply11M',
        'HumanResource.hwm.HwmHodAply12M',
        'HumanResource.hwm.HwmDayAply01M',
        'HumanResource.hwm.HwmDayAply02M',
        'HumanResource.hwm.HwmDayAply51M',
        'common.NoticeBoardManagementM',
        'common.NoticeBoardManagementDetailM',
        'common.FastLoginManagementM',
        'HumanResource.hwm.HwmOvtAply12M',
        'HumanResource.hwm.HwmElvAply01M',
        'HumanResource.hwm.HwmElvAply02M',
        'HumanResource.hwm.HwmOvtAply81M',
        'HumanResource.hwm.HwmOutAply71M',
        'HumanResource.hwm.HwmHodAply81M',
        'HumanResource.hwm.HwmElvAply71M',
        'common.Base',
        'HumanResource.hwm.HwmVctEmpe01M',
        'common.ReloadCash',
        'HumanResource.hwm.HwmVctAply03M',
        'common.NativeTestView',
        'common.ResetPassword',
        'common.ChangePassword',
        'Budget.exp.ExpNteDoc71M',
        'HumanResource.hwm.HwmOvtAply01M',
        'HumanResource.hwm.HwmWplAply02M',
        'common.FindUserPopup01M',
        'HumanResource.hwm.HwmWplMngr51M',
        'common.InfoPopupM',
        'HumanResource.hwm.HwmWplAply71M',
        'HumanResource.hwm.HwmCrtAply03M',
        'HumanResource.hwm.HwmCrtAply04M',
        'HumanResource.hwm.HwmCrtAply73M',
        'Budget.bgx.BgxNfmAply71MItem02',
        'common.NoticeBoardManagementDetailPopupM',
        'HumanResource.hwm.HwmOvtRept01M',
        'HumanResource.hwm.HwmOvtAply02M',
        'HumanResource.hwm.HwmOvtAply71M',
        'HumanResource.hwm.HwmHodAply71M',
        'Budget.bgx.com.BgxItmCpnt33M',
        'Budget.bgx.BgxNfmAply57M',
        'Budget.bgx.BgxNfmAply57MItems',
        'HumanResource.hwm.HwmOvtChck01M',
        'HumanResource.hwm.HwmOvtAply03M',
        'HumanResource.hwm.HwmOvtAply73M',
        'HumanResource.hwm.HwmHodAply03M',
        'HumanResource.hwm.HwmHodAply73M',
        'HumanResource.hwm.HwmHodAply01M',
        'HumanResource.hwm.HwmCrtAply01M',
        'HumanResource.hwm.HwmCrtAply02M',
        'HumanResource.hwm.HwmCrtAply71M',
        'HumanResource.hwm.HwmVctAply04M',
        'HumanResource.hwm.HwmVctAply71M',
        'HumanResource.hwm.HwmVctAply71MContainer',
        'HumanResource.hwm.HwmVctAply05M',
        'BackOffice.bom.BomCmplSic01M',
        'BackOffice.bom.BomMtgBoo04M',
        'BackOffice.bom.BomCmplNoticeBoardManagementM',
        'BackOffice.bom.BomCmplNoticeBoardManagementDetailM',
        'BackOffice.bom.BomMtgBoo51M',
        'BackOffice.bom.BomCmplHomeM',
        'BackOffice.bom.BomMtgBoo01M',
        'BackOffice.bom.HroSalSpec01M',
        'BackOffice.bom.HroCtrInfo01M',
        'BackOffice.bom.HroCtrInfo02M',
        'BackOffice.bom.HroSalSpec02M',
        'test.Knowledge',
        'test.BomKlsNews01',
        'test.BomKlsNews51',
        'test.BomKlsMgz',
        'test.BomKlsDict',
        'test.BomKlsMean',
        'test.BomKlsView',
        'test.BomKlsSearch',
        'HumanResource.hrd.HrdScyAply01M',
        'HumanResource.hrd.HrdScyAply02M',
        'HumanResource.hwm.HwmBtrAply71M',
        'HumanResource.hwm.HwmBtrAply71MContainer',
        'HumanResource.hwm.HwmBtrRept71M',
        'BackOffice.bom.BomWekWork01M',
        'BackOffice.bom.BomWekWork02M',
        'HumanResource.hwm.HwmVctAply73M',
        'HumanResource.hwm.HwmVctAply06M',
        'HumanResource.hwm.HwmBtrAply72M',
        'HumanResource.hwm.HwmBtrRept72M',
        'common.AuthPopupM'
    ],
    name: 'BNK',

    requires: [
        'BNK.*',
        'Ext.calendar.*'
    ],

    launch: function() {
        Ext.create('BNK.view.common.LoginV1', {fullscreen: true});
        //전역변수 설정
        this.imageCache = new Map();
        this.loadingQueue = [];
        this.maxConcurrentLoads = 3;
        this.currentLoads =  0;
        this.retryAttempts = new Map();
        this.maxRetries= 2;

        if(window.device){
            console.log('[디바이스접속고유정보]UUID : ' + device.uuid);
        }

        if (this.isIOSPlatform()) {
            // User-Agent 인터셉터 초기화 (가장 먼저 실행)
            this.initUserAgentInterceptor();
        }

        // Ext.create('BNK.view.common.LoginV1', {fullscreen: true});
        // 플랫폼 확인 및 설정
        this.checkPlatformAndSetup();
        // 푸시
        document.addEventListener('deviceready', this.onDeviceReady.bind(this), false);

        // 팝업
        Ext.Msg.defaultAllowedConfig.hideAnimation = false;

        // 요청전 Ajax Interceptor
        Ext.Ajax.on('beforerequest', function(conn, options) {

            if(!options.headers.hasOwnProperty('enableMask') || options.headers.enableMask){
                Ext.Viewport.setMasked({
                    xtype: 'loadmask',
                    message: '',
                    indicator: false,
                    html : '<img src="resources/images/loading-bar.gif"></img>',
                    zIndex : 9999999
                });
            }

            var principal = SecurityUtils.getPrincipal(), // 사용자정보
                jwtToken = localStorage.getItem(Property.JWT_TOKEN_NAME);

            // User-Agent 설정 (iOS 플랫폼용)
            var customUserAgent = null;
            if (this.isIOSPlatform()) {
                var baseUA = this.getSafeUserAgent();
                customUserAgent = baseUA;

                if (baseUA.indexOf('onebiz_bnksys') === -1) {
                    customUserAgent = baseUA + ' onebiz_bnksys';
                }

                // User-Agent 길이 체크
                if (customUserAgent.length > 500) {
                    console.warn('⚠️ Ajax User-Agent 길이 초과, 단축 버전 사용');
                    customUserAgent = 'Mozilla/5.0 Mobile onebiz_bnksys';
                }

                console.log('🏷️ Ajax User-Agent 설정:', customUserAgent);
            }

            options.method = 'POST'; // POST만 지원함
            options.headers = {
                'X-Requested-With' : 'XMLHttpRequest',
                'Authorization'    : !jwtToken ? '' : 'Bearer ' + jwtToken,
                'cmgrpCd'          : Property.CMGRP_CD,
                'sysCd'            : Property.SYS_CD,
                'profile'          : Property.PROFILE,
                'device'           : Property.DEVICE,
                'protocol'         : Property.PROTOCOL,
                'dataType'         : Property.DATA_TYPE,
                'cmgrpId'          : principal && principal.hasOwnProperty('comCmmCmgrpId') ? principal.comCmmCmgrpId : null,
                'sysId'            : principal && principal.hasOwnProperty('comCmmSystemId') ? principal.comCmmSystemId : null,
                'serviceId'        : options.headers.serviceId || null,
                'viewId'           : options.headers.viewId || null
            };

            // iOS인 경우 User-Agent 헤더 추가
            if (customUserAgent) {
                options.headers['User-Agent'] = customUserAgent;
            }

            options.url = Property.API_URL;
            if ('F' === Property.PROFILE) {
                options.url = Ext.String.format('./testdata/{0}.json', options.headers.serviceId);
            } else if (options.isUpload) {
                options.url = Property.BASE_URL + Property.FILE_URL;
                options.params = options.headers;
            }

            // PROXY 페이징정보 보정 page: 페이지, size: 한페이지에 보여질 내용건 수
            if (options.hasOwnProperty('params')) {
                var page = null,
                    size = null;

                if (options.params.hasOwnProperty('limit')) size = options.params.limit; delete options.params.limit; // default limit 10
                if (options.params.hasOwnProperty('start'))                              delete options.params.start;
                if (options.params.hasOwnProperty('page'))  page = options.params.page;

                if (!size) {
                    options.params.size = Property.DEFAULT_PAGE_SIZE;
                }
                else {
                    options.params.size = size;
                }

                if (!page) {
                    options.params.page = 1;
                }
            }

            if (Property.IS_DEBUG) {
                var params = options.jsonData || options.params;
                console.log('>>> ', options.method, options.headers.serviceId, params);
                if (customUserAgent) {
                    console.log('>>> User-Agent:', customUserAgent);
                }
            }
        }.bind(this)); // 중요: this 바인딩 추가

        // 요청완료 - 새로고침/조회 후 이미지 재처리 추가
        Ext.Ajax.on('requestcomplete', function(conn, response, options) {
            Ext.Viewport.setMasked(false);
            if (Property.IS_DEBUG) {
                if (response) {
                    console.log('<<< ', response);
                }
            }

            // 응답값에서 토큰갱신
            if (options.isUpload) {
                // 파일처리
            } else if (response && response.getResponseHeader('Authorization')) {
                localStorage.setItem(Property.JWT_TOKEN_NAME, response.getResponseHeader('Authorization').replace('Bearer ', ''));
            }

            // 새로고침/조회 후 이미지 재처리
            var me = this;
            setTimeout(function() {
                if (me.isIOSPlatform()) {
                    me.reprocessImagesAfterRefresh();
                }
            }, 100);

            var status = response.status;
            switch (status) {
                case 0:
                    Ext.Msg.alert(Property.SYSTEM_NAME, '서버와 연결이 원활하지 않습니다.<br />인터넷 연결 상태를 확인하고 다시 시도해주시길 바랍니다.');
                    break;
                default :
                    break;
            }
        }.bind(this));

        // 요청오류
        Ext.Ajax.on('requestexception', function (conn, response, options) {
            Ext.Viewport.setMasked(false);

            // 응답값에서 토큰갱신
            if (options.isUpload) {
                // 파일처리
            } else if (response && response.getResponseHeader('Authorization')) {
                localStorage.setItem(Property.JWT_TOKEN_NAME, response.getResponseHeader('Authorization').replace('Bearer ', ''));
            }

            // 메소드에 failure 를 설정하지 않았을 경우에만 공통처리 실행됨
            // failure 를 설정하였다고 하는건 자체실패처리를 하겠다라는 의미로 판단
            if (!options.hasOwnProperty('failure')) {
                var error = response.status + ' - ' + response.statusText,
                    status = response.status,
                    responseJson = null,
                    errCode = null,
                    errTitle = null,
                    errMsg = null,
                    message = null,
                    moreInfo = null;

                if (Property.IS_DEBUG) {
                    console.log('서버요청오류 : ', response);
                }

                switch (status) {
                    case 0: // 서버 접속이 안될경우, 0 또는 404 가 반환되어 대응처리함
                    case 404:
                        Ext.create(Property.ROUTE_LOGIN, {fullscreen: true});
                        Ext.Msg.alert(Property.SYSTEM_NAME, '서버와 연결이 원활하지 않습니다.<br />인터넷 연결 상태를 확인하고 다시 시도해주시길 바랍니다.');
                        break;
                    case 400:
                        errCode = 'E5000';
                        errTitle = '입력값검증에러';
                        errMsg = '입력값 검증처리중 에러가 발생하였습니다.';

                        if (response.hasOwnProperty('responseText') && response.responseText.length > 0) {
                            responseJson = Ext.JSON.decode(response.responseText);
                            if (responseJson.hasOwnProperty('code'))     errCode = responseJson.code;
                            if (responseJson.hasOwnProperty('errTitle')) errTitle = responseJson.errTitle;
                            if (responseJson.hasOwnProperty('errMsg'))   errMsg = responseJson.errMsg;
                            if (responseJson.hasOwnProperty('moreInfo')) moreInfo = responseJson.moreInfo; if (Property.profile !== 'P' && Property.IS_DEBUG) console.log('오류상세내역: ', responseJson.moreInfo);
                        }

                        if (errCode.startsWith('E9')) {
                            Ext.create(Property.ROUTE_LOGIN, {fullscreen: true});
                        }

                        Ext.Msg.alert(Property.SYSTEM_NAME, Ext.String.format('<strong>{0} [{1}]</strong><br /><br />{2}', errTitle, errCode, errMsg));
                        break;
                    case 401:
                        errCode = 'E9500';
                        errTitle = '인증오류';
                        errMsg = '인증 처리중 에러가 발생하였습니다.';

                        try {
                            var existResponseJson = false;
                            if (response.hasOwnProperty('responseJson') && JsonUtils.isJson(response.responseJson)) {
                                responseJson = response.responseJson;
                                existResponseJson = true;
                            }
                            else if (response.hasOwnProperty('responseText') && response.responseText.length > 0) {
                                responseJson = Ext.JSON.decode(response.responseText);
                                existResponseJson = true;
                            }

                            if (existResponseJson) {
                                if (responseJson.hasOwnProperty('code'))     errCode = responseJson.code;
                                if (responseJson.hasOwnProperty('errTitle')) errTitle = responseJson.errTitle;
                                if (responseJson.hasOwnProperty('errMsg'))   errMsg = responseJson.errMsg;
                                if (responseJson.hasOwnProperty('moreInfo')) moreInfo = responseJson.moreInfo; if (Property.profile !== 'P' && Property.IS_DEBUG) console.log('오류상세내역: ', responseJson.moreInfo);

                                //세션시간만료일 경우 세션시간을 확인하여 시간을 표시하도록 로직 추가해줌 MS202107121327
                                if (errCode == 'E9514') {
                                    var iat = SecurityUtils.getJwt().iat; //세션시작
                                    var exp = parseInt(SecurityUtils.getJwt().exp + '000'); //세션종료
                                    var min = Math.floor((exp - iat)/(1000*60)) + 1;
                                    var sec = Math.ceil((exp - iat)/(1000)); //초

                                    errMsg = (min < 1) ? "" :  min + "분 ";
                                    errMsg += "동안 서비스 이용이 없어<br>안전한 개인정보 보호를 위해 로그아웃 되었습니다.";
                                }
                            }

                        }
                        catch(e) {
                            if (response.responseText && response.responseText.length > 0) errMsg = response.responseText;
                        }

                        Ext.create(Property.ROUTE_LOGIN, {fullscreen: true});
                        Ext.Msg.alert(Property.SYSTEM_NAME, Ext.String.format('<strong>{0} [{1}]</strong><br /><br />{2}', errTitle, errCode, errMsg));
                        break;
                    case 500:
                        errCode = 'E9000';
                        errTitle = '시스템오류';
                        errMsg = '이용에 불편을 드려 죄송합니다.';

                        if (response.hasOwnProperty('responseText') && response.responseText.length > 0) {
                            responseJson = Ext.JSON.decode(response.responseText);
                            if (responseJson.hasOwnProperty('code'))     errCode = responseJson.code;
                            if (responseJson.hasOwnProperty('errTitle')) errTitle = responseJson.errTitle;
                            if (responseJson.hasOwnProperty('errMsg'))   errMsg = responseJson.errMsg;
                            if (responseJson.hasOwnProperty('moreInfo')) moreInfo = responseJson.moreInfo; if (Property.profile !== 'P' && Property.IS_DEBUG) console.log('오류상세내역: ', responseJson.moreInfo);
                        }

                        if (errCode.startsWith('E9')) {
                            Ext.create(Property.ROUTE_LOGIN, {fullscreen: true});
                        }

                        Ext.Msg.alert(Property.SYSTEM_NAME, Ext.String.format('<strong>{0} [{1}]</strong><br /><br />{2}', errTitle, errCode, errMsg));
                        break;
                    case -1:
                        if (response.statusText) {
                            var errorData = response.statusText;
                            console.log('Ajax request Error: ', response.status);
                            console.log('ajax req error: ', errorData);
                        }
                        break;
                    default:
                        if (response.statusText) {
                            if (response.status != 200) {
                                var errorData = Ext.JSON.decode(response.responseText);
                                console.log('Ajax request Error: ', response.status);
                                console.log('ajax req error: ', errorData);

                                Ext.create(Property.ROUTE_LOGIN, {fullscreen: true});
                            }
                        }
                        break;
                }
            }
        });

    },

    onDeviceReady: function() {
                // deviceready 후 다시 플랫폼 확인
                if (this.isIOSPlatform()) {
                    console.log('deviceready에서 iOS 확인 - User-Agent 재설정');
                    setTimeout(function() {
                        this.setupAjaxUserAgent();
                    }.bind(this), 1000);
                }

                this.receivedEvent('deviceready');
    },

    receivedEvent: function(id) {
                var me = this;
                debugger;
                console.log('Received Event: ' + id);

                // 푸시 환경설정 init
                var push = PushNotification.init({
                    android : {
                        senderID : "415174156496",
                        forceShow : true
                    },
                    ios : {
                        alert : "true",
                        badge : "true",
                        sound : "true"
                    }
                });

                // 클라이언트 디바이스 토큰 값 생성시 호출.
                push.on('registration', function(data) {
                    // 해당 토큰값을 사원테이블에 insert. (with deviceType)
                    console.log('device token: ' + data.registrationId);

                    var token = data.registrationId;
                    if(token){
                        Property.PUSH_TOKEN = data.registrationId;
                    }
                });

                /** 클라이언트 notification 클릭시 호출.
                 data 내 parameter는 URL을 참조.
                 https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/API.md#callback-parameters-3
                 */
                push.on('notification', function(data) {
                    console.log('notification message: ' + data.message);

                    /**
                     < 파라미터 정의 >
                     (1) boTasmTrsId : 후선업무_통합알림_기본ID
                     (2) msgChkActDvcd : 액션구분
                     */
                    var param = data.additionalData.param,
                        userAgent = window.navigator.userAgent,
                        startIdx = userAgent.indexOf("("),
                        endIdx = userAgent.indexOf(")"),
                        mobileModelName = userAgent.substring(startIdx + 1, endIdx);

                    if (param && mobileModelName) {
                        var boTasmTrsId = ((mobileModelName.indexOf("iPhone") !== -1) ? Ext.JSON.decode(param.toString()).boTasmTrsId : param.boTasmTrsId).replace('[','').replace(']','');
                        var msgChkActDvcd = ((mobileModelName.indexOf("iPhone") !== -1) ? Ext.JSON.decode(param.toString()).msgChkActDvcd : param.msgChkActDvcd).replace('[','').replace(']','');
                        if (boTasmTrsId && msgChkActDvcd) {
                            // 로그인 여부
                            if (Property.IS_LOGIN) {
                                if (msgChkActDvcd == Constants.msgChkActDvcd.NORMAL) {
                                    // 상세팝업 호출 (공지, 설문, 경조사)
                                    Ext.create('BomTasPushDetailPopupM', {boTasmTrsId : boTasmTrsId}).show();
                                } else if (msgChkActDvcd == Constants.msgChkActDvcd.APPROVAL) {
                                    // 결재
                                    Ext.create('BomTasPushDetailPopupM', {boTasmTrsId : boTasmTrsId}).show();
                                }
                            } else {
                                // 로그인 후 처리
                                Property.BO_TASM_TRS_ID = boTasmTrsId;
                                Property.MSG_CHK_ACT_DVCD = msgChkActDvcd;
                            }
                        }
                    }
                });

                // 푸시발송 실패 시 호출.
                push.on('error', function(error) {
                    console.log(error.message);
                });

    },

    onRedirectPage: function(view) {
                var me = this;
                var mainV1 = me.getView().down('MainV1');
                var naviView = me.getView().down('navigationview');

                if(!Ext.isEmpty(mainV1) && !Ext.isEmpty(naviView)){
                    mainV1.PUSH_VIEW(naviView,{
                        menuId : view.viewId
                    });
                }
    },

    initCustomUserAgent: function() {
                var originalUA = navigator.userAgent;
                var customUA = originalUA;

                if (customUA.indexOf('onebiz_bnksys') === -1) {
                    customUA = originalUA + ' onebiz_bnksys';
                }

                window.CUSTOM_USER_AGENT = customUA;
                console.log('🚀 User-Agent 초기화:');
                console.log('   원본:', originalUA);
                console.log('   결과:', customUA);
                return customUA;
    },

    getSafeUserAgent: function() {
                if (window.CUSTOM_USER_AGENT) {
                    return this.cleanupUserAgent(window.CUSTOM_USER_AGENT);
                }
                return this.initCustomUserAgent();
    },

    cleanupUserAgent: function(userAgent) {

                if (!userAgent) return userAgent;

                if (userAgent.includes(',')) {
                    var firstPart = userAgent.split(',')[0].trim();
                    console.log('🧹 콤마로 분리된 User-Agent 정리:', userAgent, '->', firstPart);
                    return firstPart;
                }

                var parts = userAgent.split(' onebiz_bnksys');
                if (parts.length > 2) {
                    var cleanUA = parts[0] + ' onebiz_bnksys';
                    console.log('🧹 중복 onebiz_bnksys 제거:', userAgent, '->', cleanUA);
                    return cleanUA;
                }

                return userAgent;
    },

    isBnkDownloadImage: function(src) {
                if (!src || typeof src !== 'string') return false;
                return src.indexOf('/down/') === 0 ||
                    (src.indexOf('bnksys.co.kr') !== -1 && src.indexOf('/down/') !== -1);
    },

    isBnkImage: function(src) {
                if (!src || typeof src !== 'string') return false;
                return src.indexOf('bnksys.co.kr') !== -1 ||
                    src.indexOf('/down/') === 0 ||
                    src.indexOf('/file/') === 0 ||
                    src.indexOf('/image/') === 0 ||
                    src.indexOf('/upload/') === 0;
    },

    getBnkAbsoluteUrl: function(src) {
                if (!src) return src;
                if (src.startsWith('http://') || src.startsWith('https://')) {
                    return src;
                }
                var baseUrl = Property.BASE_URL || window.location.origin;
                if (baseUrl.endsWith('/')) {
                    baseUrl = baseUrl.slice(0, -1);
                }
                if (!src.startsWith('/')) {
                    src = '/' + src;
                }
                return baseUrl + src;
    },

    isIOSPlatform: function() {
                if (this._isIOSCached !== undefined) {
                    return this._isIOSCached;
                }
                this._isIOSCached = Ext.os.is.iOS ||
                    (typeof device !== 'undefined' && device.platform === 'iOS') ||
                    /iPhone|iPad|iPod/i.test(navigator.userAgent) ||
                    (typeof window.device !== 'undefined' && window.device.platform === 'iOS');
                return this._isIOSCached;
    },

    isExtJSBackgroundImageComponent: function(element) {
                if (!element || !element.className) return false;
                var classList = element.className;
                return classList.includes('x-img') &&
                    classList.includes('x-img-background') &&
                    classList.includes('x-component');
    },

    getImageUrlFromExtJSComponent: function(element) {
                if (element.style && element.style.backgroundImage) {
                    var match = element.style.backgroundImage.match(/url\(["']?([^"')]+)["']?\)/);
                    if (match) return match[1];
                }
                var computedStyle = window.getComputedStyle(element);
                if (computedStyle.backgroundImage && computedStyle.backgroundImage !== 'none') {
                    var match = computedStyle.backgroundImage.match(/url\(["']?([^"')]+)["']?\)/);
                    if (match) return match[1];
                }
                var componentId = element.getAttribute('data-componentid') || element.id;
                if (componentId) {
                    var component = Ext.getCmp(componentId);
                    if (component && component.getSrc) {
                        return component.getSrc();
                    }
                }
                return null;
    },

    loadImageWithUserAgent: function(originalUrl, element, isExtJSComponent) {
                if (!originalUrl || !this.isBnkImage(originalUrl)) {
                    return false;
                }

                var absoluteUrl = this.getBnkAbsoluteUrl(originalUrl);

                // 캐시 확인
                if (this.imageCache.has(absoluteUrl)) {
                    console.log('📦 캐시에서 로드:', absoluteUrl);
                    this.applyImageToElement(element, this.imageCache.get(absoluteUrl), isExtJSComponent);
                    return true;
                }

                // 동시 로딩 제한
                if (this.currentLoads >= this.maxConcurrentLoads) {
                    this.loadingQueue.push({
                        url: absoluteUrl,
                        element: element,
                        isExtJSComponent: isExtJSComponent,
                        originalUrl: originalUrl
                    });
                    return true;
                }

                this.executeImageLoad(absoluteUrl, element, isExtJSComponent, originalUrl);
                return true;
    },

    executeImageLoad: function(absoluteUrl, element, isExtJSComponent, originalUrl) {
                var me = this;
                this.currentLoads++;

                console.log('🔽 이미지 로드 시작:', absoluteUrl);

                // 재시도 횟수 확인
                var retries = this.retryAttempts.get(absoluteUrl) || 0;
                if (retries > this.maxRetries) {
                    console.error('❌ 최대 재시도 횟수 초과:', absoluteUrl);
                    this.fallbackToOriginalSrc(element, absoluteUrl, isExtJSComponent);
                    this.completeLoad();
                    return;
                }

                var xhr = new XMLHttpRequest();
                xhr.open('GET', absoluteUrl, true);
                xhr.responseType = 'blob';
                xhr.timeout = 10000;

                // User-Agent 설정 (길이 제한 및 안전성 강화)
                try {
                    var baseUA = this.getSafeUserAgent();
                    var customUA = baseUA;

                    // onebiz_bnksys가 이미 있는지 확인
                    if (baseUA.indexOf('onebiz_bnksys') === -1) {
                        customUA = baseUA + ' onebiz_bnksys';
                    }

                    // User-Agent 길이 체크 (일반적으로 512자 제한)
                    if (customUA.length > 500) {
                        console.warn('⚠️ User-Agent 길이 초과 (' + customUA.length + '), 단축 버전 사용');
                        customUA = 'Mozilla/5.0 Mobile onebiz_bnksys';
                    }

                    xhr.setRequestHeader('User-Agent', customUA);
                    xhr.setRequestHeader('Accept', 'image/*,*/*;q=0.8');

                    console.log('✅ User-Agent 설정 (길이: ' + customUA.length + '):');
                    console.log('   전체:', customUA);
                    console.log('   앞부분:', customUA.substring(0, 50) + '...');
                    console.log('   뒷부분:', '...' + customUA.substring(customUA.length - 20));

                } catch(e) {
                    console.error('❌ User-Agent 설정 실패:', e.message);
                    // 실패시 최소한의 식별자만 사용
                    try {
                        xhr.setRequestHeader('User-Agent', 'Mozilla/5.0 onebiz_bnksys');
                        console.log('📌 최소 User-Agent 설정 성공');
                    } catch(e2) {
                        console.error('❌ 최소 User-Agent도 실패:', e2.message);
                        // 마지막 수단: 커스텀 헤더 사용
                        try {
                            xhr.setRequestHeader('X-Client-Type', 'onebiz_bnksys');
                            xhr.setRequestHeader('X-Mobile-App', 'BNK');
                            console.log('📌 대체 헤더 설정 성공');
                        } catch(e3) {
                            console.error('❌ 모든 헤더 설정 실패:', e3.message);
                        }
                    }
                }

                xhr.onload = function() {
                    if (xhr.status === 200 && xhr.response && xhr.response.size > 0) {
                        var objectURL = URL.createObjectURL(xhr.response);
                        me.imageCache.set(absoluteUrl, objectURL);
                        me.applyImageToElement(element, objectURL, isExtJSComponent);
                        console.log('✅ 이미지 로드 성공:', absoluteUrl);
                        me.retryAttempts.delete(absoluteUrl);
                    } else {
                        console.error('❌ 잘못된 응답:', xhr.status, absoluteUrl);
                        me.handleLoadError(absoluteUrl, element, isExtJSComponent, originalUrl);
                    }
                    me.completeLoad();
                };

                xhr.onerror = function() {
                    console.error('❌ 네트워크 오류:', absoluteUrl);
                    me.handleLoadError(absoluteUrl, element, isExtJSComponent, originalUrl);
                    me.completeLoad();
                };

                xhr.ontimeout = function() {
                    console.error('⏰ 타임아웃:', absoluteUrl);
                    me.handleLoadError(absoluteUrl, element, isExtJSComponent, originalUrl);
                    me.completeLoad();
                };

                xhr.send();
    },

    handleLoadError: function(absoluteUrl, element, isExtJSComponent, originalUrl) {
                var retries = this.retryAttempts.get(absoluteUrl) || 0;
                retries++;
                this.retryAttempts.set(absoluteUrl, retries);

                if (retries <= this.maxRetries) {
                    console.log('🔄 재시도 (' + retries + '/' + this.maxRetries + '):', absoluteUrl);
                    setTimeout(function() {
                        this.loadingQueue.unshift({
                            url: absoluteUrl,
                            element: element,
                            isExtJSComponent: isExtJSComponent,
                            originalUrl: originalUrl
                        });
                        this.processQueue();
                    }.bind(this), 1000 * retries);
                } else {
                    console.error('💥 최종 실패:', absoluteUrl);
                    this.fallbackToOriginalSrc(element, absoluteUrl, isExtJSComponent);
                }
    },

    completeLoad: function() {
                this.currentLoads--;
                this.processQueue();
    },

    processQueue: function() {
                while (this.loadingQueue.length > 0 && this.currentLoads < this.maxConcurrentLoads) {
                    var item = this.loadingQueue.shift();
                    this.executeImageLoad(item.url, item.element, item.isExtJSComponent, item.originalUrl);
                }
    },

    applyImageToElement: function(element, objectURL, isExtJSComponent) {
         if (!element || !objectURL) return;

                if (isExtJSComponent) {
                    element.style.backgroundImage = 'url(' + objectURL + ')';
                    element.style.backgroundSize = 'cover';
                    element.style.backgroundPosition = 'center';
                    element.style.backgroundRepeat = 'no-repeat';
                } else {
                    element.src = objectURL;
                }

                element.style.backgroundColor = '';
                element.style.border = '';
    },

    fallbackToOriginalSrc: function(element, originalUrl, isExtJSComponent) {
            console.log('🔄 폴백 처리:', originalUrl);

                if (isExtJSComponent) {
                    element.style.backgroundImage = 'url(' + originalUrl + ')';
                    element.style.backgroundSize = 'cover';
                    element.style.backgroundPosition = 'center';
                    element.style.backgroundRepeat = 'no-repeat';
                } else {
                    element.src = originalUrl;
                }

                element.style.backgroundColor = '';
                element.style.border = '';
    },

    setupImageInterception: function() {
                var me = this;

                // 1. 더 이른 시점에서 차단 - createElement 레벨
                var originalCreateElement = document.createElement;
                document.createElement = function(tagName) {
                    var element = originalCreateElement.call(this, tagName);

                    if (tagName.toLowerCase() === 'img') {
                        // IMG 태그 생성 즉시 src 설정 차단 준비
                        me.prepareImageElementForInterception(element);
                    }

                    return element;
                };

                // 2. setAttribute 오버라이드 강화
                var originalSetAttribute = Element.prototype.setAttribute;
                Element.prototype.setAttribute = function(name, value) {
                    if (name === 'src' && this.tagName === 'IMG' && me.isBnkDownloadImage(value)) {
                        console.log('🚫 setAttribute /down/ 차단:', value);
                        // 절대 src 설정하지 않고 바로 처리
                        this.setAttribute('data-original-src', value);
                        me.interceptImageElement(this);
                        return; // 중요: 실제 src 설정 방지
                    }
                    return originalSetAttribute.call(this, name, value);
                };

                // 3. src 프로퍼티 오버라이드 강화
                var originalSrcDescriptor = Object.getOwnPropertyDescriptor(HTMLImageElement.prototype, 'src');
                if (originalSrcDescriptor && originalSrcDescriptor.configurable) {
                    Object.defineProperty(HTMLImageElement.prototype, 'src', {
                        get: function() {
                            var originalSrc = this.getAttribute('data-original-src');
                            if (originalSrc && me.isBnkDownloadImage(originalSrc)) {
                                return originalSrc;
                            }
                            return originalSrcDescriptor.get.call(this);
                        },
                        set: function(value) {
                            if (value && me.isBnkDownloadImage(value)) {
                                console.log('🚫 src property /down/ 차단:', value);
                                // 절대 실제 src 설정하지 않음
                                this.setAttribute('data-original-src', value);
                                me.interceptImageElement(this);
                                return; // 중요: 실제 src 설정 방지
                            }
                            return originalSrcDescriptor.set.call(this, value);
                        },
                        configurable: true
                    });
                }

                // 4. innerHTML 사전 처리로 HTML에서도 차단
                var originalInnerHTMLDescriptor = Object.getOwnPropertyDescriptor(Element.prototype, 'innerHTML');
                if (originalInnerHTMLDescriptor && originalInnerHTMLDescriptor.configurable) {
                    Object.defineProperty(Element.prototype, 'innerHTML', {
                        get: originalInnerHTMLDescriptor.get,
                        set: function(value) {
                            if (typeof value === 'string' && value.includes('<img') && value.includes('/down/')) {
                                // /down/ 경로가 포함된 img 태그의 src를 사전에 제거
                                value = me.preprocessImageHTML(value);
                                console.log('🚫 innerHTML /down/ 이미지 사전 처리 완료');
                            }

                            var result = originalInnerHTMLDescriptor.set.call(this, value);

                            // 새로 추가된 IMG 태그들 즉시 처리
                            setTimeout(function() {
                                var newImages = this.querySelectorAll('img');
                                for (var i = 0; i < newImages.length; i++) {
                                    me.interceptImageElement(newImages[i]);
                                }
                            }.bind(this), 0);

                            return result;
                        },
                        configurable: true
                    });
                }

                // 5. MutationObserver로 실시간 감시
                var observer = new MutationObserver(function(mutations) {
                    var elementsToProcess = [];

                    mutations.forEach(function(mutation) {
                        if (mutation.type === 'childList') {
                            mutation.addedNodes.forEach(function(node) {
                                if (node.nodeType === Node.ELEMENT_NODE) {
                                    if (node.tagName === 'IMG') {
                                        // IMG 태그 즉시 차단 처리
                                        me.immediatelyBlockBnkDownloadImage(node);
                                        elementsToProcess.push(node);
                                    } else if (me.isExtJSBackgroundImageComponent(node)) {
                                        elementsToProcess.push(node);
                                    }

                                    if (node.querySelectorAll) {
                                        var images = node.querySelectorAll('img');
                                        for (var i = 0; i < images.length; i++) {
                                            me.immediatelyBlockBnkDownloadImage(images[i]);
                                            elementsToProcess.push(images[i]);
                                        }

                                        var bgImages = node.querySelectorAll('.x-img.x-img-background');
                                        for (var j = 0; j < bgImages.length; j++) {
                                            elementsToProcess.push(bgImages[j]);
                                        }
                                    }
                                }
                            });
                        } else if (mutation.type === 'attributes') {
                            if (mutation.attributeName === 'src' && mutation.target.tagName === 'IMG') {
                                var src = mutation.target.getAttribute('src');
                                if (src && me.isBnkDownloadImage(src)) {
                                    console.log('🚫 MutationObserver 실시간 /down/ 차단:', src);
                                    // 즉시 src 제거
                                    mutation.target.removeAttribute('src');
                                    mutation.target.setAttribute('data-original-src', src);
                                    elementsToProcess.push(mutation.target);
                                }
                            }
                        }
                    });

                    // 배치 처리
                    setTimeout(function() {
                        elementsToProcess.forEach(function(element) {
                            me.interceptImageElement(element);
                        });
                    }, 0);
                });

                observer.observe(document, {
                    childList: true,
                    subtree: true,
                    attributes: true,
                    attributeFilter: ['src']
                });

                // 6. 기존 요소들 즉시 차단 처리
                this.blockExistingBnkDownloadImages();

                console.log('✅ 강화된 이미지 인터셉션 설정 완료 (403 오류 방지)');

    },

    prepareImageElementForInterception: function(imgElement) {
         var me = this;

                // 개별 IMG 요소에 대한 src 프로퍼티 오버라이드
                Object.defineProperty(imgElement, 'src', {
                    get: function() {
                        var originalSrc = this.getAttribute('data-original-src');
                        if (originalSrc && me.isBnkDownloadImage(originalSrc)) {
                            return originalSrc;
                        }
                        return this.getAttribute('src') || '';
                    },
                    set: function(value) {
                        if (value && me.isBnkDownloadImage(value)) {
                            console.log('🚫 개별 IMG src 설정 차단:', value);
                            this.setAttribute('data-original-src', value);
                            me.interceptImageElement(this);
                            return;
                        }
                        this.setAttribute('src', value);
                    },
                    configurable: true
                });
    },

    blockExistingBnkDownloadImages: function() {
         var existingImages = document.querySelectorAll('img');
                var blockedCount = 0;

                console.log('🔍 기존 /down/ 이미지 차단 처리 시작:', existingImages.length, '개 검사');

                for (var i = 0; i < existingImages.length; i++) {
                    var img = existingImages[i];
                    var currentSrc = img.src || img.getAttribute('src');

                    if (currentSrc && this.isBnkDownloadImage(currentSrc)) {
                        console.log('🚫 기존 /down/ 이미지 즉시 차단:', currentSrc);

                        // 즉시 src 제거
                        img.removeAttribute('src');
                        img.src = '';
                        img.setAttribute('data-original-src', currentSrc);

                        // 이벤트 핸들러도 제거
                        img.onload = null;
                        img.onerror = null;
                        img.onabort = null;

                        blockedCount++;
                    }

                    // 모든 이미지 처리
                    this.interceptImageElement(img);
                }

                // ExtJS 컴포넌트도 처리
                var bgImages = document.querySelectorAll('.x-img.x-img-background');
                for (var j = 0; j < bgImages.length; j++) {
                    this.interceptImageElement(bgImages[j]);
                }

                console.log('✅ /down/ 이미지 차단 완료:', blockedCount, '개 차단됨');
    },

    immediatelyBlockBnkDownloadImage: function(imgElement) {

                if (imgElement.tagName !== 'IMG') return;

                var currentSrc = imgElement.src || imgElement.getAttribute('src');
                if (currentSrc && this.isBnkDownloadImage(currentSrc)) {
                    console.log('🚫 새 IMG /down/ 즉시 차단:', currentSrc);

                    // 즉시 차단
                    imgElement.removeAttribute('src');
                    imgElement.src = '';
                    imgElement.setAttribute('data-original-src', currentSrc);
                    imgElement.onload = null;
                    imgElement.onerror = null;
                    imgElement.onabort = null;
                }
    },

    preprocessImageHTML: function(htmlString) {
                return htmlString.replace(/<img([^>]*?)src=["']([^"']*\/down\/[^"']*)["']([^>]*?)>/gi, function(match, before, src, after) {
                    console.log('🚫 HTML 문자열 /down/ 이미지 사전 제거:', src);
                    return '<img' + before + 'data-original-src="' + src + '"' + after + '>';
                });
    },

    interceptImageElement: function(element) {

                if (element._bnkProcessed) return;

                var imageUrl = null;
                var isExtJSComponent = false;
                var isDownloadImage = false;

                // 이미지 URL 추출
                if (element.tagName === 'IMG') {
                    var existingSrc = element.src || element.getAttribute('src');
                    var originalSrc = element.getAttribute('data-original-src');
                    imageUrl = originalSrc || existingSrc;
                    isExtJSComponent = false;
                    isDownloadImage = this.isBnkDownloadImage(imageUrl);
                } else if (this.isExtJSBackgroundImageComponent(element)) {
                    imageUrl = this.getImageUrlFromExtJSComponent(element);
                    isExtJSComponent = true;
                    isDownloadImage = this.isBnkDownloadImage(imageUrl);
                } else {
                    imageUrl = element.getAttribute('src');
                    if (imageUrl) {
                        isExtJSComponent = true;
                        isDownloadImage = this.isBnkDownloadImage(imageUrl);
                    }
                }

                // BNK 이미지가 아니면 처리하지 않음
                if (!this.isBnkImage(imageUrl)) {
                    return;
                }

                console.log('🔍 BNK 이미지 감지:', imageUrl, isDownloadImage ? '(/down/ 차단)' : '(일반)');
                element._bnkProcessed = true;

                // /down/ 경로에 대해서만 기본 요청 차단
                if (isDownloadImage && !isExtJSComponent) {
                    if (element.src && this.isBnkDownloadImage(element.src)) {
                        element.removeAttribute('src');
                        element.src = '';
                    }
                    element.setAttribute('data-original-src', imageUrl);
                    element.onload = null;
                    element.onerror = null;
                    element.style.backgroundColor = '#f8f9fa';
                    element.style.border = '1px solid #e9ecef';
                }

                // 모든 BNK 이미지에 User-Agent 요청 실행
                this.loadImageWithUserAgent(imageUrl, element, isExtJSComponent);
    },

    reprocessImagesAfterRefresh: function() {
         console.log('🔄 새로고침/조회 후 이미지 재처리 시작...');

                // 모든 이미지 요소의 처리 상태 초기화
                var allImages = document.querySelectorAll('img');
                for (var i = 0; i < allImages.length; i++) {
                    var img = allImages[i];
                    // 처리 상태 초기화 후 다시 처리
                    img._bnkProcessed = false;
                    this.interceptImageElement(img);
                }

                // ExtJS 배경 이미지도 재처리
                var bgImages = document.querySelectorAll('.x-img.x-img-background');
                for (var j = 0; j < bgImages.length; j++) {
                    var bgImg = bgImages[j];
                    bgImg._bnkProcessed = false;
                    this.interceptImageElement(bgImg);
                }

                console.log('✅ 새로고침/조회 후 이미지 재처리 완료');
    },

    setupXHRInterceptor: function() {
         if (!window.XMLHttpRequest) return;

                var me = this;
                var OriginalXHR = window.XMLHttpRequest;
                var originalOpen = OriginalXHR.prototype.open;
                var originalSend = OriginalXHR.prototype.send;

                OriginalXHR.prototype.open = function(method, url, async, user, password) {
                    this._method = method;
                    this._url = url;
                    this._async = async;

                    var isGetRequest = method && method.toUpperCase() === 'GET';
                    var isBnkRequest = url && me.isBnkImage(url);

                    if (isGetRequest && isBnkRequest) {
                        this._shouldAddUserAgent = true;
                    }

                    return originalOpen.apply(this, arguments);
                };

                OriginalXHR.prototype.send = function(data) {
                    if (this._shouldAddUserAgent) {
                        try {
                            var baseUA = navigator.userAgent;
                            var customUA = baseUA;

                            // onebiz_bnksys가 없으면 추가
                            if (baseUA.indexOf('onebiz_bnksys') === -1) {
                                customUA = baseUA + ' onebiz_bnksys';
                            }

                            // User-Agent 길이 체크
                            if (customUA.length > 500) {
                                console.warn('⚠️ XHR User-Agent 길이 초과, 단축 버전 사용');
                                customUA = 'Mozilla/5.0 Mobile onebiz_bnksys';
                            }

                            this.setRequestHeader('User-Agent', customUA);

                            console.log('✅ XHR User-Agent 설정 (길이: ' + customUA.length + '):');
                            console.log('   요약:', customUA.substring(0, 30) + '...' + customUA.substring(customUA.length - 15));

                        } catch(e) {
                            console.error('❌ XHR User-Agent 설정 실패:', e.message);
                            // 단계적 폴백
                            try {
                                this.setRequestHeader('User-Agent', 'Mozilla/5.0 onebiz_bnksys');
                                console.log('📌 XHR 최소 User-Agent 설정');
                            } catch(e2) {
                                try {
                                    this.setRequestHeader('X-Client-Type', 'onebiz_bnksys');
                                    this.setRequestHeader('X-Mobile-App', 'BNK');
                                    console.log('📌 XHR 대체 헤더 설정');
                                } catch(e3) {
                                    console.error('❌ XHR 모든 헤더 설정 실패:', e3.message);
                                }
                            }
                        }
                    }
                    return originalSend.apply(this, arguments);
                };

                console.log('✅ 안전한 XMLHttpRequest 인터셉터 설정 완료');
    },

    setupExtJSImageOverride: function() {

                var me = this;

                if (Ext.Img) {
                    Ext.override(Ext.Img, {
                        setSrc: function(src) {
                            if (me.isBnkImage(src)) {
                                var imgEl = this.imageEl || this.el;
                                if (imgEl && imgEl.dom) {
                                    me.loadImageWithUserAgent(src, imgEl.dom, true);
                                    return this;
                                }
                            }
                            return this.callParent(arguments);
                        }
                    });
                }

                console.log('✅ ExtJS 이미지 컴포넌트 오버라이드 설정 완료');
    },

    setupAjaxUserAgent: function() {

                if (!this.isIOSPlatform()) return;

                var me = this;
                var baseUA = this.getSafeUserAgent();
                var customUA = baseUA;

                if (baseUA.indexOf('onebiz_bnksys') === -1) {
                    customUA = baseUA + ' onebiz_bnksys';
                }

                // User-Agent 길이 체크
                if (customUA.length > 500) {
                    console.warn('⚠️ iOS Ajax User-Agent 길이 초과, 단축 버전 사용');
                    customUA = 'Mozilla/5.0 Mobile onebiz_bnksys';
                }

                console.log('🏷️ iOS Ajax User-Agent 설정 (길이: ' + customUA.length + '):', customUA);

                // ExtJS Ajax 기본 헤더 설정
                Ext.Ajax.defaultHeaders = Ext.Ajax.defaultHeaders || {};
                Ext.Ajax.defaultHeaders['User-Agent'] = customUA;

                // 추가 보장: beforerequest 이벤트에서도 설정
                Ext.Ajax.on('beforerequest', function(conn, options) {
                    if (!options.headers) options.headers = {};

                    // User-Agent가 없거나 onebiz_bnksys가 없으면 설정
                    if (!options.headers['User-Agent'] ||
                        options.headers['User-Agent'].indexOf('onebiz_bnksys') === -1) {
                        options.headers['User-Agent'] = customUA;
                        console.log('🔧 User-Agent 보정:', customUA);
                    }
                });

                console.log('✅ iOS Ajax User-Agent 설정 완료');
    },

    initUserAgentInterceptor: function() {
                console.log('🚀 User-Agent 인터셉터 초기화 시작');

                this.getSafeUserAgent();
                this.setupXHRInterceptor();
                this.setupImageInterception();
                this.setupExtJSImageOverride();

                console.log('✅ User-Agent 인터셉터 초기화 완료');
    },

    getCurrentPlatform: function() {
              if (Ext.os.is.iOS) return 'iOS (ExtJS)';
                if (Ext.os.is.Android) return 'Android (ExtJS)';
                if (typeof device !== 'undefined') return device.platform + ' (Cordova)';
                if (/iPhone|iPad|iPod/i.test(navigator.userAgent)) return 'iOS (UserAgent)';
                if (/Android/i.test(navigator.userAgent)) return 'Android (UserAgent)';
                return 'Unknown';
    },

    clearImageCache: function() {
                this.imageCache.forEach(function(objectURL) {
                    URL.revokeObjectURL(objectURL);
                });
                this.imageCache.clear();
                console.log('🗑️ 이미지 캐시 클리어 완료');
    },

    getImageCacheStats: function() {
                return {
                    cacheSize: this.imageCache.size,
                    queueLength: this.loadingQueue.length,
                    currentLoads: this.currentLoads,
                    maxConcurrentLoads: this.maxConcurrentLoads
                };
    },

    resetUserAgent: function() {
                // 원본 User-Agent로 리셋
                var baseUA = this.getSafeUserAgent();
                if (baseUA.indexOf('onebiz_bnksys') === -1) {
                    window.CUSTOM_USER_AGENT = baseUA + ' onebiz_bnksys';
                } else {
                    window.CUSTOM_USER_AGENT = baseUA;
                }
                console.log('🔄 User-Agent 리셋 완료:', window.CUSTOM_USER_AGENT);
    },

    checkPlatformAndSetup: function() {
                console.log('플랫폼 확인 중...');
                console.log('Ext.os.is.iOS:', Ext.os.is.iOS);
                console.log('Ext.os.is.Android:', Ext.os.is.Android);
                console.log('device.platform:', typeof device !== 'undefined' ? device.platform : 'undefined');
                console.log('navigator.userAgent:', navigator.userAgent);
                console.log('Custom User-Agent:', window.CUSTOM_USER_AGENT);

                // iOS인 경우에만 Ajax User-Agent 설정
                if (this.isIOSPlatform()) {
                    console.log('✅ iOS 플랫폼 감지 - Ajax User-Agent 설정 실행');
                    this.setupAjaxUserAgent();
                } else {
                    console.log('ℹ️ iOS가 아닌 플랫폼 - Ajax User-Agent 설정 스킵');
                    console.log('현재 플랫폼:', this.getCurrentPlatform());
                }
    }

});
