/*
 * File: app/view/Budget/bgx/BgxNfmAply71MItem04ViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

/*
    모바일 예산 : 결의서 [결재함 / 기타영수증] - 컨트롤러

    @author BNK시스템/계장/지민영
    @since 2020.05.26
    @version 1.0
    @see

    << 개정이력(Modification Information) >>

    수정일       수정자                수정내용
    ----------  ------------------   --------------------------
    2020.05.26  BNK시스템/계장/지민영   최초 생성
    2020.09.21  BNK시스템/계장/지민영   사업연도 추가
*/
Ext.define('BNK.view.Budget.bgx.BgxNfmAply71MItem04ViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.BgxNfmAply71MItem04ViewController',

    config: {
        viewId: 'BgxNfmAply71MItem04'
    },

    fnSetSummaryUserLabel: function() {
        var me = this,
            vm = me.getViewModel(),
            refs = me.getReferences(),
            expItemData = Ext.clone(vm.get('expItemData')),
            userRecords = expItemData.expItemUserInfo,
            trnsAmt = expItemData.trnsAmt,  //공급가액
            innerEmpeCnt = 0,
            outerEmpeCnt = 0,
            rtnStr = '',
            defaultStr = '승인금액',
            xpnitKeyCd = expItemData.xpnitKeyCd,
            xpnitKeyNm = expItemData.xpnitKeyNm;

        if (userRecords) {
            for (var i = 0; i < userRecords.length; i++) {
                var record = userRecords[i];
                if (record.stfDvcd == Constants.stfDvcd.IN) {
                    innerEmpeCnt++;
                } else {
                    outerEmpeCnt++;
                }
            }
            var amtByUser = (innerEmpeCnt == 0 ? 0 : Math.round(trnsAmt / innerEmpeCnt));

            rtnStr = Ext.String.format('<span style = "line-height : 20px;">집행대상 ( 총 <span style ="color : red;">{0}</span>명 ) <br>'
                                       + '[ 내부직원 {1} 명 / 외부직원 {2} 명 ] <br>'
                                       + '<span style = "color :gray;" >[{3} 기준 1인당 {4}원]</span></span>',
                                       userRecords.length, innerEmpeCnt, outerEmpeCnt, defaultStr ,
                                       amtByUser.toString().replace(/\B(?=(\d{3})+(?!\d))/g,","));

        }
        vm.set('expItemData.summaryUserLabel', rtnStr);

        var cmm = refs.common_input_container,
            cmmRefs = cmm.refs;
        cmmRefs.dgDsbEmpId.setValue(vm.get('applyInfo.dgDsgInfo.bcncSeq'));	// 지급정보
    },

    /* 영수증 팝업 */
    openEvidImgFilePopUp: function(button, e, eOpts) {
        var me = this;
        var vm = me.getViewModel();

        Ext.create('BgxItmCpnt52M', {
            param : vm.get('expItemData.evidImgFileId')
        }).show();
    },

    onContainerInitialize: function(component, eOpts) {
        var me = this,
            vm = me.getViewModel(),
            refs = me.getReferences(),
            config = component.config;

        if (config) {
            vm.set('codeList', config.codeList);
            vm.set('applyInfo', config.applyInfo);
            vm.set('readOnlyFlag', config.readOnlyFlag);
            var expItemData = config.expItemData;
            vm.set('expItemData', expItemData);
            vm.set('expItemData.bsnsYy', config.applyInfo.bsnsYy);		// 2020.09.21 사업연도 추가
            vm.set('expItemInputData', expItemData);
            vm.set('expItemData.trnsYy', expItemData.trnsDt.substr(0,4));
            vm.set('infoText', config.infoText);			// 안내문구
            var command = config.command,
                aprHistId = config.aprHistId,
                edocCd = config.edocCd;

            // 결재문서 초기화 설정
            ApprovalBoxSvc.setup({
                command   : command,
                viewModel : vm,
                aprHistId : aprHistId,
                edocCd    : 'BgxNfmAply71',
                scope     : me
            });

            // 포매팅
            if(expItemData) {
                refs.trnsDt.setValue(DateUtils.parseDate(expItemData.trnsDt) + ' ' + expItemData.trnsHr.substr(0,2) + ':' + expItemData.trnsHr.substr(2,2) + ':' + expItemData.trnsHr.substr(4,2));
                refs.trnsAmt.setValue(FormatUtils.moneyFormat(expItemData.trnsAmt)+'원');
            }
        }

        // BgxItmCpnt31M
        var cmm = refs.common_input_container,
            cmmRefs = cmm.getReferences();
        refs.cardEvidImg.setHidden(false);	// 영수증 버튼

        me.fnSetSummaryUserLabel();			// 집행대상라벨
        // 계정과목
        cmmRefs.xpnitKeyNm.setValue(vm.get('expItemData.xpnitKeyNm'));
        cmmRefs.xpnitKeyNm.setHidden(false);
        cmmRefs.xpnitKeyCd.setHidden(true);

        // 지급정보
        var dgDsbInfo = vm.get('applyInfo.dgDsbInfo');
        if (dgDsbInfo) {
            var bcncSeq = dgDsbInfo.bcncSeq,		// 사번
            bcncDpwnm = dgDsbInfo.bcncDpwnm;	// 이름
            cmmRefs.dgDsbInfoGrid.setHidden(true);
            cmmRefs.dgDsbInfoCont.setHidden(false);
            cmmRefs.dgDsbInfoLabel.setHtml(bcncSeq + ' / ' + bcncDpwnm);
        }
        cmmRefs.imgPanel.setHidden(true);	// 사진
    }

});