/*
 * File: app/view/test/BomKlsNews51.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BNK.view.test.BomKlsNews51', {
    extend: 'Ext.window.Window',
    alias: 'widget.BomKlsNews51',

    alternateClassName: [
        'BomKlsNews51'
    ],
    requires: [
        'BNK.view.test.BomKlsNews51ViewModel',
        'BNK.view.test.BomKlsNews51ViewController',
        'Ext.field.Display',
        'Ext.field.Text',
        'Ext.Button',
        'Ext.field.Checkbox',
        'Ext.form.Panel'
    ],

    controller: 'test.bomklsnews51',
    viewModel: {
        type: 'test.bomklsnews51'
    },
    height: '90%',
    width: '90%',

    items: [
        {
            xtype: 'container',
            height: '100%',
            layout: 'vbox',
            items: [
                {
                    xtype: 'displayfield',
                    html: '키워드설정'
                },
                {
                    xtype: 'container',
                    flex: 1,
                    margin: '5 10 5 10',
                    layout: 'vbox',
                    items: [
                        {
                            xtype: 'container',
                            layout: 'hbox',
                            items: [
                                {
                                    xtype: 'container',
                                    flex: 1
                                },
                                {
                                    xtype: 'textfield',
                                    flex: 2,
                                    placeholder: 'add keyword'
                                },
                                {
                                    xtype: 'button',
                                    flex: 1,
                                    text: '추가'
                                },
                                {
                                    xtype: 'container',
                                    flex: 1
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            layout: 'hbox',
                            items: [
                                {
                                    xtype: 'container',
                                    flex: 1
                                },
                                {
                                    xtype: 'checkbox',
                                    flex: 2,
                                    reference: 'all',
                                    width: '50%',
                                    label: '전체 선택',
                                    labelAlign: 'right',
                                    labelWidth: '80%',
                                    listeners: {
                                        change: 'onCheckboxChange1'
                                    }
                                },
                                {
                                    xtype: 'container',
                                    flex: 1
                                }
                            ]
                        },
                        {
                            xtype: 'formpanel',
                            flex: 1,
                            reference: 'form',
                            padding: 0,
                            header: false,
                            title: 'My Form',
                            items: [
                                {
                                    xtype: 'container',
                                    reference: 'keyCtn',
                                    height: '100%',
                                    width: '100%',
                                    scrollable: 'vertical',
                                    layout: 'vbox'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            layout: {
                                type: 'vbox',
                                align: 'center'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    ui: 'action',
                                    width: '30%',
                                    text: '학인',
                                    listeners: {
                                        tap: 'onButtonTapClose'
                                    }
                                }
                            ]
                        }
                    ]
                }
            ],
            listeners: {
                painted: 'onContainerPainted'
            }
        }
    ]

});