/*
 * File: app/view/test/BomKlsFinc.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BNK.view.test.BomKlsFinc', {
    extend: 'Ext.Container',
    alias: 'widget.BomKlsFinc',

    alternateClassName: [
        'BomKlsFinc'
    ],
    requires: [
        'BNK.view.test.BomKlsFincViewModel4',
        'BNK.view.test.BomKlsFincViewController4',
        'Ext.field.Text',
        'Ext.Button',
        'Ext.grid.Grid',
        'Ext.grid.column.Number'
    ],

    controller: 'test.bomklsfinc',
    viewModel: {
        type: 'test.bomklsfinc'
    },

    items: [
        {
            xtype: 'container',
            height: '100%',
            layout: 'vbox',
            items: [
                {
                    xtype: 'container',
                    layout: 'hbox',
                    items: [
                        {
                            xtype: 'textfield',
                            flex: 1,
                            label: 'Field'
                        },
                        {
                            xtype: 'button',
                            iconCls: 'x-fa fa-search'
                        }
                    ]
                },
                {
                    xtype: 'grid',
                    height: '100%',
                    width: '100%',
                    hideHeaders: true,
                    columns: [
                        {
                            xtype: 'numbercolumn',
                            width: 89,
                            dataIndex: 'number',
                            text: 'Number'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 70,
                            dataIndex: 'string',
                            text: 'String'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 70,
                            dataIndex: 'string',
                            text: 'String'
                        }
                    ]
                }
            ]
        }
    ]

});