/*
 * File: app/view/common/ApprovalLineGrid.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

/*
    공통 / 결재선 View

    @author BNK시스템/팀장/손승범
    @since 2019.06.17.
    @version 1.0
    @see

    << 개정이력(Modification Information) >>

      수정일         수정자                      수정내용
     ------------   ---------                 --------------------------
      2019.06.17.   BNK시스템/팀장/손승범         최초 생성
*/
Ext.define('BNK.view.common.ApprovalLineGrid', {
    extend: 'Ext.grid.Grid',
    alias: 'widget.common.approvallinegrid',

    alternateClassName: [
        'ApprovalLineGrid'
    ],
    requires: [
        'BNK.view.common.ApprovalLineGridViewModel',
        'BNK.view.common.ApprovalLineGridViewController',
        'Ext.grid.column.Number'
    ],

    controller: 'common.approvallinegrid',
    viewModel: {
        type: 'common.approvallinegrid'
    },
    reference: 'approvalLineGrid',
    height: '100%',
    width: '100%',
    itemConfig: {
        xtype: 'gridrow',
        body: {
            tpl: '<div>'+'<span style="font-weight:bold;font-size:15px;padding-right:10px;">{aprStcdNm}</span>'+'<span style="font-weight:bold;font-size:15px;">{aprvr}</span>'+'</div>'+'<tpl if="!(!dlvDtti && !aprDtti)">'+'<div>'+'<span style="color: red;">'+'<tpl if="!!aprDtti">결재 {aprDtti}</tpl>'+'</span>'+'</div>'+'<div>'+'<span style="color: green;padding-right:10px;">'+'<tpl if="!!dlvDtti">수신 {dlvDtti}</tpl>'+'</span>'+'</div>'+'</tpl>'+'<tpl if="!!aprComment">'+'<div>의견 {aprComment}</div>'+'</tpl>'
        }
    },
    title: '결재선',

    columns: [
        {
            xtype: 'numbercolumn',
            hidden: true,
            dataIndex: 'id',
            text: 'ID'
        },
        {
            xtype: 'gridcolumn',
            hidden: true,
            dataIndex: 'aprStcdNm',
            menuDisabled: true,
            sortable: false,
            text: '결재상태명'
        },
        {
            xtype: 'gridcolumn',
            hidden: true,
            dataIndex: 'aprKndcdNm',
            menuDisabled: true,
            sortable: false,
            text: '결재종류명'
        },
        {
            xtype: 'gridcolumn',
            hidden: true,
            dataIndex: 'aprvr',
            menuDisabled: true,
            sortable: false,
            text: '기안자'
        },
        {
            xtype: 'gridcolumn',
            hidden: true,
            dataIndex: 'sno',
            text: '순번'
        },
        {
            xtype: 'gridcolumn',
            hidden: true,
            dataIndex: 'aprvrNm',
            text: '성명'
        },
        {
            xtype: 'gridcolumn',
            hidden: true,
            dataIndex: 'aprvrPsinm',
            text: '직위'
        },
        {
            xtype: 'gridcolumn',
            hidden: true,
            dataIndex: 'aprStcd',
            menuDisabled: true,
            renderer: 'gridRenderer',
            sortable: false,
            text: '결재상태'
        },
        {
            xtype: 'gridcolumn',
            hidden: true,
            dataIndex: 'aprKndcd',
            renderer: 'gridRenderer',
            text: '결재종류'
        },
        {
            xtype: 'gridcolumn',
            hidden: true,
            dataIndex: 'aprvrDpnm',
            text: '부서'
        },
        {
            xtype: 'gridcolumn',
            hidden: true,
            dataIndex: 'dlvDtti',
            menuDisabled: true,
            sortable: false,
            text: '받은일자'
        },
        {
            xtype: 'gridcolumn',
            hidden: true,
            dataIndex: 'aprDtti',
            menuDisabled: true,
            sortable: false,
            text: '결재일자'
        },
        {
            xtype: 'gridcolumn',
            hidden: true,
            dataIndex: 'aprvrId',
            text: '사번'
        },
        {
            xtype: 'gridcolumn',
            hidden: true,
            dataIndex: 'aprvrDeptCd',
            text: '부서코드'
        },
        {
            xtype: 'gridcolumn',
            hidden: true,
            dataIndex: 'aprComment',
            text: '결재의견'
        }
    ]

});