/*
 * File: app/view/common/ApprovalCommentPopUp.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

/*
    공통 / 결재선의견팝업 View

    @author BNK시스템/팀장/손승범
    @since 2019.06.17.
    @version 1.0
    @see

    << 개정이력(Modification Information) >>

      수정일         수정자                      수정내용
     ------------   ---------                 --------------------------
      2019.06.17.   BNK시스템/팀장/손승범         최초 생성
*/
Ext.define('BNK.view.common.ApprovalCommentPopUp', {
    extend: 'Ext.window.Window',
    alias: 'widget.common.approvalcommentpopup',

    requires: [
        'BNK.view.common.ApprovalCommentPopUpViewModel',
        'BNK.view.common.ApprovalCommentPopUpViewController',
        'Ext.field.TextArea',
        'Ext.Toolbar',
        'Ext.Button'
    ],

    controller: 'common.approvalcommentpopup',
    viewModel: {
        type: 'common.approvalcommentpopup'
    },
    alwaysOnTop: true,
    height: 250,
    width: '80%',
    modal: true,
    autoSize: false,
    layout: 'vbox',
    title: '의견',

    items: [
        {
            xtype: 'textareafield',
            height: '100%',
            padding: 10,
            bind: {
                value: '{aprComment}'
            }
        },
        {
            xtype: 'toolbar',
            docked: 'bottom',
            items: [
                {
                    xtype: 'button',
                    flex: 1,
                    text: '확인',
                    listeners: {
                        tap: 'onBtnOkTap'
                    }
                },
                {
                    xtype: 'button',
                    flex: 1,
                    text: '취소',
                    listeners: {
                        tap: 'onBtnCancelTap'
                    }
                }
            ]
        }
    ],
    listeners: {
        initialize: 'init'
    }

});