/*
 * File: app/view/common/ApprovalCommentPopUpViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

/*
    공통 / 결재선의견팝업 Controller

    @author BNK시스템/팀장/손승범
    @since 2019.06.17.
    @version 1.0
    @see

    << 개정이력(Modification Information) >>

      수정일         수정자                      수정내용
     ------------   ---------                 --------------------------
      2019.06.17.   BNK시스템/팀장/손승범         최초 생성
*/
Ext.define('BNK.view.common.ApprovalCommentPopUpViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.common.approvalcommentpopup',

    config: {
        viewId: 'ApprovalCommentPopUp'
    },

    onBtnOkTap: function(button, e, eOpts) {
        var me = this,
            vm = me.getViewModel(),
            aprComment = vm.get('aprComment');

        me.getView().fireEvent('ok', aprComment, me.getView());
    },

    onBtnCancelTap: function(button, e, eOpts) {
        this.getView().close();
    },

    init: function(component, eOpts) {
        if (component.config.title) {
            this.getView().setTitle(component.config.title);
        }
    }

});