/*
 * File: app/view/common/ChangePasswordViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BNK.view.common.ChangePasswordViewController', {
    extend: 'BaseViewController',
    alias: 'controller.common.changepassword',

    config: {
        viewId: 'ChangePassword'
    },

    init: function(component) {
        var me = this,
            initialConfig = component.initialConfig;

        // 비밀번호만료가 되어서 온 경우, 타이틀을 설정한다.
        if (initialConfig.title) {
            me.lookup('form').setTitle(initialConfig.title);
        }
    },

    onReset: function(button, e, eOpts) {
        this.lookup('form').reset();
    },

    onChangePassword: function(button, e, eOpts) {
        var me = this,
            refs = me.getReferences(),
            form = refs.form,
            values = form.getValues();

        if (!form.isValid()) {
            return;
        }

        if (values.newPassword != values.newPasswordConfirm) {
            Ext.Msg.alert('비밀번호변경오류', '신규비밀번호와 신규비밀번호확인값이 일치하지 않습니다.');
            return;
        }

        SecurityUtils.encrypt(me, {
            currentPassword    : values.currentPassword,
            newPassword        : values.newPassword,
            newPasswordConfirm : values.newPasswordConfirm
        }).then(function(result){
            Ext.Ajax.request({
                headers : {
                    serviceId : 'COMAPP0002U01M',
                    viewId : 'ChangePassword'
                },
                jsonData : result,
                scope: me,
                success : function(res) {
                    Ext.Msg.alert('비밀번호변경안내', '비밀번호가 정상적으로 변경되었습니다.<br />로그인 화면으로 이동하여 재로그인 해주시길 바랍니다.', function(answer) {
                        if (answer) {
                            // 				this.REDIRECT('Login', {});
                            this.REDIRECT('LoginV1', {});
                        }
                    }, this);
                },
                failure: function(res) {
                    var me = this,
                        responseJson = Ext.JSON.decode(res.responseText);
                    Ext.Msg.alert('비밀번호변경안내', Ext.String.format('[{0}] {1}', responseJson.code, responseJson.errMsg));

                    //me.onReset();
                }
            });
        })
        .catch(function(res){
            // failure 를 직접구현하는 경우, 공통 실패응답처리 메소드를 호출한다.
            me.HANDLE_RESPONSE_FAILURE(res);
        });

    }

});