/*
 * File: app/view/common/Error404.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

/*
    메인 / 404 View

    @author BNK시스템/팀장/손승범
    @since 2019.06.17.
    @version 1.0
    @see

    << 개정이력(Modification Information) >>

      수정일         수정자                      수정내용
     ------------   ---------                 --------------------------
      2019.06.17.   BNK시스템/팀장/손승범         최초 생성
*/
Ext.define('BNK.view.common.Error404', {
    extend: 'Ext.Container',
    alias: 'widget.Error404',

    alternateClassName: [
        'Error404'
    ],
    requires: [
        'BNK.view.common.Error404ViewModel',
        'BNK.view.common.Error404ViewController',
        'Ext.Label'
    ],

    controller: 'common.error404',
    viewModel: {
        type: 'Error404ViewModel'
    },
    style: 'background-color: #FFF;',
    padding: 20,
    layout: 'center',

    items: [
        {
            xtype: 'label',
            reference: 'message',
            style: 'font-size : 14px; font-weight: bold',
            html: '페이지를 찾을 수 없습니다.<br /><br />요청하신 페이지가 제거되었거나, <br />이름이 변경되었거나,<br /> 일시적으로 사용이 중단되었습니다.<br /><br />관련 문의사항은 관리자에게<br />알려주시면 친절하게 안내해 드리겠습니다.'
        }
    ]

});