/*
 * File: app/view/common/FastLoginManagementMViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BNK.view.common.FastLoginManagementMViewController', {
    extend: 'BaseViewController',
    alias: 'controller.common.fastloginmanagementm',

    config: {
        viewId: 'FastLoginManagement'
    },

    validateForm: function() {
        var me = this,
            refs = me.getReferences(),
            btnSave = refs.btnSave,
            form = refs.form,
            values = form.getValues(),
            currPassword = values.currPassword,
            fastPassword = values.fastPassword,
            fastPasswordCheck = values.fastPasswordCheck;

        // 현재비밀번호 입력
        // 빠른로그인 비밀번호 입력 과 확인 비밀번호 동일
        // 빠른로그인 비밀번호 입력 숫자6자리
        // 빠른로그인 비밀번호 확인 숫자6자리
        if (currPassword && ( fastPassword === fastPasswordCheck) && /^\d{6}$/g.test(fastPassword) && /^\d{6}$/g.test(fastPasswordCheck)) {
            btnSave.setDisabled(false);
        }
        else {
            btnSave.setDisabled(true);
        }
    },

    onCurrPasswordKeyup: function(textfield, e, eOpts) {
        this.validateForm();
    },

    onFastPasswordKeyup: function(textfield, e, eOpts) {
        this.validateForm();
    },

    onFastPasswordCheckKeyup: function(textfield, e, eOpts) {
        this.validateForm();
    },

    onReset: function(button, e, eOpts) {
        var me = this,
            refs = me.getReferences(),
            form = refs.form;

        form.reset();
    },

    onSave: function(button, e, eOpts) {
        var me = this,
            refs = me.getReferences(),
            btnSave = refs.btnSave,
            form = refs.form,
            values = form.getValues(),
            currPassword = values.currPassword,
            fastPassword = values.fastPassword,
            fastPasswordCheck = values.fastPasswordCheck;

        SecurityUtils.encrypt(me, {
            currPassword	  : currPassword,
            fastPassword	  : fastPassword,
            fastPasswordCheck : fastPasswordCheck
        }).then(function(result){

            Ext.Ajax.request({
                headers: {
                    viewId: 'FastLoginManagementM',
                    serviceId: 'ComEnvSvc.saveFastLoginM'
                },
                jsonData: result,
                scope : me,
                success: function(response) {
                    var me = this,
                        responseJson = Ext.JSON.decode(response.responseText);

                    // 로그아웃
                    Ext.Msg.confirm('안내', '<p>빠른 로그인 비밀번호가 변경되었습니다.<br/>재로그인하시겠습니까?</p>', function(buttonId) {
                        var me = this;

                        if ('yes' === buttonId) {
                            // 토큰삭제
                            sessionStorage.removeItem(Property.JWT_TOKEN_NAME);
                            WebUtils.setCookie(Property.JWT_TOKEN_NAME, null, -1);

                            // 서버로그아웃
                            Ext.Ajax.request({
                                headers: {
                                    viewId: 'FastLoginManagementM',
                                    serviceId: 'COMAPP0002R02M'
                                },
                                scope : me,
                                success : function(res) {
                                    if (Property.IS_DEBUG) console.log('로그아웃 성공');
                                },
                                failure: function(response, opts) {
                                    if (Property.IS_DEBUG) console.log('로그아웃 실패');
                                }
                            });

                            // 메인화면제거 및 로그인화면 표시
                            // 메인화면 표시
                            Ext.create(Property.ROUTE_LOGIN, {fullscreen: true});
                        }
                    }, me);

                },
                failure: function(response) {
                    var me = this,
                        refs = me.getReferences(),
                        currPassword = refs.currPassword,
                        fastPassword = refs.fastPassword,
                        fastPasswordCheck = refs.fastPasswordCheck;

                    if (response.status === 500) {
                        var responseJson = Ext.JSON.decode(response.responseText);
                        currPassword.setValue(null);
                        fastPassword.setValue(null);
                        fastPasswordCheck.setValue(null);

                        Ext.Msg.alert('빠른로그인 저장오류', Ext.String.format('<p>{0}</p>', responseJson.errMsg));
                    }
                }
            });
        })
        .catch(function(response){
            me.HANDLE_RESPONSE_FAILURE(response);
        });

    }

});