/*
 * File: app/view/common/LoginViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

/*
    메인 / 로그인 Controller

    @author BNK시스템/팀장/손승범
    @since 2019.06.17.
    @version 1.0
    @see

    << 개정이력(Modification Information) >>

      수정일         수정자                      수정내용
     ------------   ---------                 --------------------------
      2019.06.17.   BNK시스템/팀장/손승범         최초 생성
*/
Ext.define('BNK.view.common.LoginViewController', {
    extend: 'BaseViewController',
    alias: 'controller.common.login',

    config: {
        viewId: 'Login',
        viewId1: 'ExpNteAply01M'
    },

    initApplication: function() {
        var D = new Ext.Deferred();

        var me = this,
            principal = SecurityUtils.getPrincipal(), // 사용자정보
            jwtToken = WebUtils.getCookie(Property.JWT_TOKEN_NAME) || sessionStorage.getItem(Property.JWT_TOKEN_NAME),
            csrfToken = WebUtils.getCookie(Property.XSRF_TOKEN_NAME) || sessionStorage.getItem(Property.XSRF_TOKEN_NAME),
            url = Property.API_URL;

            if ('F' === Property.PROFILE) {
                url = './testdata/COMAPP0002R03.json';
            }

        // TODO 자동로그인 처리할 것!
        Ext.Ajax.request({
            headers: {
                viewId: 'Login',
                serviceId: 'COMAPP0002R03M',
                'X-Requested-With' : 'XMLHttpRequest',
                'Authorization'    : 'Bearer ' + jwtToken,
                'X-XSRF-TOKEN'     : csrfToken,
                'cmgrpCd'          : Property.CMGRP_CD,
                'sysCd'            : Property.SYS_CD,
                'profile'          : Property.PROFILE,
                'device'           : Property.DEVICE,
                'protocol'         : Property.PROTOCOL,
                'dataType'         : Property.DATA_TYPE,
                'cmgrpId'          : principal && principal.hasOwnProperty('comCmmCmgrpId') ? principal.comCmmCmgrpId : null,
                'sysId'            : principal && principal.hasOwnProperty('comCmmSystemId') ? principal.comCmmSystemId : null
            },
            url : url,
            method : 'POST',
            scope : me,
            success : function(res) {
                var me = this,
                    result = Ext.JSON.decode(res.responseText);

                if (Property.IS_DEBUG) console.log('로그인결과: ', result);

                // 파일처리인경우, 쿠키를 저장하는 처리 추가함
                if ('F' === Property.PROFILE) {
                    if (result.hasOwnProperty(Property.JWT_TOKEN_NAME)) {
                        WebUtils.setCookie(Property.JWT_TOKEN_NAME, result[Property.JWT_TOKEN_NAME]);
                    }
                }

                // 어플리케이션 데이터 초기화
                me.INIT_APPLICATION_DATA(result);

                D.resolve(true);
            },
            failure : function(response, opts) {

                if (response.status === 0) {
                    Ext.Msg.alert(Property.SYSTEM_NAME, '서버와 연결이 원활하지 않습니다.<br />인터넷 연결 상태를 확인하고 다시 시도해주시길 바랍니다.');
                }

                var me = this,
                    refs = me.getReferences(),
                    loadingView = refs.loadingView,
                    loginForm = refs.loginForm;

                loadingView.setHidden(true);
                loginForm.setHidden(false);

                D.reject(false);
            }
        });

        return D.promise;
    },

    /* 그리드조회 */
    search1: function(params) {
        var me = this,
            vm = me.getViewModel(),
            refs = me.getReferences(),
            params = params || {},
            store = vm.storeInfo.ApvlStore;

        if(params.cdno == '99')
        {
            params.cdno = '';
            params.hrHrpmEmpId = SecurityUtils.getPrincipal().hrHrpmEmpId;
        }

        store.getProxy().extraParams = params;
        store.removeAll();
        store.loadPage(1);

        //debugger // 스크롤 보정 (상단으로 이동)

    },

    showView1: function(itemId) {
                var me = this;
                me.getView().setActiveItem(itemId);
    },

    setGridTotal1: function() {
        var me = this;
        var refs = me.getReferences();
        var grid = refs.grid;
        var lblTotalCnt = refs.lblTotalCnt;
        var records = grid.getStore().data.items;
        var totalAmt = 0;
        var totalCnt = 0;

        for (var i in records) {
            var record = records[i].data;
            if (record.selected === true) {
                if(record.canYn === 'N'){ // 정상건
                    record.apvlAmtDom = String(record.apvlAmtDom).replace(/,/gi, '').replace(/ 원/gi, '').replace(/-/gi, '');
                    totalAmt += Number(record.apvlAmtDom);
                    totalCnt++;
                } else { // 취소건인 경우
                    var cancelApvlAmtDom = String(record.apvlAmtDom).replace(/,/gi, '').replace(/ 원/gi, '').replace(/-/gi, '');
                    totalAmt -= Number(cancelApvlAmtDom);
                    totalCnt++;
                }
            }
        }

        var strAmt = String(totalAmt);
        var moneyAmt = strAmt.replace(/(\d)(?=(?:\d{3})+(?!\d))/g, '$1,');
        lblTotalCnt.setValue('<div style="width:100%;font-size:14px;"><span style="display:inline-block;text-align:left;width:20%">총</span><span style="display:inline-block;text-align:right;width:80%">' + totalCnt + '건</span></div><div style="width:100%;font-size:14px;">합계 <span style="text-align:right">' + moneyAmt + '<span>원</div>');


    },

    /* 취소건이 없는 경우 지출결의서 작성 진행 */
    onMakeProgress1: function(trueRecords) {
        var me = this,
            vm = me.getViewModel(),
            refs = me.getReferences();

        if(trueRecords.length <= 0 && cancelRecords <= 0){
            Ext.Msg.alert('알림', '법인카드 승인내역을 선택하십시오.');
            return;
        } else {
            var naviView = me.getView().up('navigationview');
            me.PUSH_VIEW(naviView, {
                menuId  : 'ExpNteAply02M',
                title   : '지출결의서 작성',
                isSubView : true,
                records : trueRecords,
            });
        }
    },

    init: function(component, eOpts) {
        // Application launch 영역보다 먼저 실행되어 Ajax headers 설정을 함
        var me = this,
            vm = me.getViewModel(),
            refs = me.getReferences(),
            loginType = refs.loginType,
            loadingView = refs.loadingView,
            rememberUserId = refs.rememberUserId,
            fastRememberUserId = refs.fastRememberUserId,
            loginForm = refs.loginForm,
            userId = refs.userId,
            loginTypeCard = refs.loginTypeCard,
            loginUserId = localStorage.getItem('loginUserId'),
            loginTypeValue = localStorage.getItem('loginType'),
            initialConfig = component.initialConfig;

        // 로컬스토리지의 사용자아이디가 존재하는 경우, 아이디 필드에 설정
        if (loginUserId) {
            vm.set('loginUserId', loginUserId);
            rememberUserId.setChecked(true);
            userId.setValue(loginUserId);
        }
        else if (initialConfig.hasOwnProperty('userId')) {
            rememberUserId.setChecked(true);
            userId.setValue(initialConfig.userId);
        }
        // 로그인타입선택
        if (!loginTypeValue) {
            loginType.setValue(0);
        }
        else {
            loginType.setValue(1);
            loginTypeCard.setActiveItem(1);
        }

        // JWT 토큰 쿠키가 존재하는 경우에만 실행
        if (WebUtils.getCookie(Property.JWT_TOKEN_NAME)) {
            console.log('Cookie OK!');
            me.initApplication().then(function(isInit) {
                // 어플리케이션 데이터가 정상처리 되었으면 HOME화면으로 이동
                if (isInit) {
                    me.REDIRECT(Property.ROUTE_HOME);
                }
            });
        }
        else {
            //loadingView.setHidden(true);
            // loginForm.setHidden(false);
        }

        // 프로퍼티 표시
        var profileText = '';
        if (Property.PROFILE === 'T') {
            profileText = '개발환경';
            refs.password.setValue('aa12345^');
        }
        else if (Property.PROFILE === 'L') {
            profileText = '로컬환경';
            refs.password.setValue('aa12345^');
        }
        refs.profile.setHtml(Ext.String.format('<h1 style="color:red;">{0}</h1>', profileText));

    },

    onIdLogin: function(button, e, eOpts) {
        var me = this,
            refs = me.getReferences(),
            loginTypeCard = refs.loginTypeCard;

        loginTypeCard.setActiveItem(0);
    },

    onPatternLogin: function(button, e, eOpts) {
        var me = this,
            refs = me.getReferences(),
            loginTypeCard = refs.loginTypeCard;

        loginTypeCard.setActiveItem(1);
        me.lookup('fastPassword').focus(true);
    },

    onResetPassword: function(button, e, eOpts) {
        var me = this,
            refs = me.getReferences(),
            userId = refs.userId,
            fastUserId = refs.fastUserId,
            userIdValue = null;

        if (userId.getValue()) {
            userIdValue = userId.getValue();
        }
        else if (fastUserId.getValue()) {
            userIdValue = fastUserId.getValue();
        }

        this.REDIRECT('ResetPassword', {
            userId : userIdValue,
            closable : true
        });
    },

    /* 로그인 */
    onLoginTap: function(button, e, eOpts) {
        var me = this,
            vm = me.getViewModel(),
            refs = me.getReferences(),
            loginType = refs.loginType.getValue(),
            loginform = refs.loginform,
            fastLoginform = refs.fastLoginform,
            idErrMsg = refs.idErrMsg,
            fastErrMsg = refs.fastErrMsg,
            values = null,
            data = {},
            isProcessLogin = vm.get('isProcessLogin');

        // 연타입력으로 인한 이벤트 중복호출 방어코드 추가
        if (!isProcessLogin) {
            vm.set('isProcessLogin', true);
        }

        // ID로그인
        if (loginType === 0) {
            values = loginform.getValues();
            data = {
                loginType: 'ID',
                cmgrpCd : Property.CMGRP_CD,
                userId : values.userId,
                password : values.password
            };
        }
        else {
            values = fastLoginform.getValues();
            data = {
                loginType: 'PASSCODE',
                cmgrpCd : Property.CMGRP_CD,
                userId : values.userId,
                password : values.password
            };
        }

        // 오류메시지제거
        idErrMsg.setHtml(null);
        fastErrMsg.setHtml(null);

        // [START] Device 모델명 (iOS, Android, etc)
        var userAgent = window.navigator.userAgent,
            startIdx = userAgent.indexOf("("),
            endIdx = userAgent.indexOf(")"),
            mobileModelName = userAgent.substring(startIdx + 1, endIdx),
            modelNameList = null,
            modelName = null;
        // Apple
        if (mobileModelName.indexOf("iPhone") > -1 || mobileModelName.indexOf("iPad") > -1 || mobileModelName.indexOf("Mac OS X") > -1) {
            //     if (mobileModelName.indexOf(";") > -1) {
            //         modelNameList = mobileModelName.split("; ");
            //         if (modelNameList.length > 0) {
            //             modelName = modelNameList[0].length > 50 ? modelNameList[0].substring(0, 50) : modelNameList[0];
            //         }
            //     }
            //     else {
            //         modelName = mobileModelName.length > 50 ? mobileModelName.substring(0, 50) : mobileModelName;
            //     }
            modelName = 'iPhone';
        }
        // Android
        else if (mobileModelName.indexOf("Android") > -1) {
            //     if (mobileModelName.indexOf(";") > -1) {
            //         modelNameList = mobileModelName.split("; "); // SM-G900P Build/LRX21T : ANDROID Galaxy S5
            //         if (modelNameList.length > 2) {
            //             modelName = modelNameList[2].length > 50 ? modelNameList[2].substring(0, 50) : modelNameList[2]; // SM-G900P Build/LRX21
            //         }
            //     }
            //     else {
            //         modelName = mobileModelName.length > 50 ? mobileModelName.substring(0, 50) : mobileModelName;
            //     }
            modelName = 'Android';
        }
        else {
            modelName = mobileModelName.length > 50 ? mobileModelName.substring(0, 50) : mobileModelName;
        }
        // [END] Device 모델명

        // 푸시
        if (Property.PUSH_TOKEN && modelName) {
            console.log('token: ' + Property.PUSH_TOKEN + '\n model: ' + modelName);
            data.pushCtfKeyVal = Property.PUSH_TOKEN;	// 푸시토큰
            data.pushDvcOsNm = modelName;				// 모바일디바이스
        }

        // 로그인거래
        Ext.Viewport.setMasked({
            xtype: 'loadmask',
            message: '',
            indicator: false,
            html : '<img src="resources/images/loading-bar.gif"></img>'
        });


        // 패스워드 암호화 후 로그인 서비스 실행
        SecurityUtils.encrypt(me, data.password)
        .then(function(encryptPassword){
            data.password = encryptPassword;

            Ext.Ajax.request({
                headers: {
                    viewId: 'Login',
                    serviceId: 'COMAPP0002R01M'
                },
                jsonData : data,
                scope : me,
                success : function(res) {
                    Ext.Viewport.setMasked(false);
                    var me = this,
                        vm = me.getViewModel(),
                        refs = me.getReferences(),
                        loginType = refs.loginType,
                        loginform = refs.loginform,
                        fastLoginform = refs.fastLoginform,
                        rememberUserId = refs.rememberUserId,
                        values = loginform.getValues(),
                        result = Ext.JSON.decode(res.responseText);

                    vm.set('isProcessLogin', false);
                    if (Property.IS_DEBUG) console.log('로그인결과: ', result);

                    // 비밀번호만료된 경우, 비밀번호 변경화면으로 전환
                    if (result && result.hasOwnProperty('principal') && result.principal
                    && result.principal.hasOwnProperty('pwExpiredYn') && result.principal.pwExpiredYn
                    && result.principal.pwExpiredYn ==='Y') {
                        me.REDIRECT('ChangePassword', {
                            title : '비밀번호변경'
                        });
                        return;
                    }

                    // 파일처리인경우, 쿠키를 저장하는 처리 추가함
                    if ('F' === Property.PROFILE) {
                        if (result.hasOwnProperty(Property.JWT_TOKEN_NAME)) {
                            var jwtToken = result[Property.JWT_TOKEN_NAME];
                            WebUtils.setCookie(Property.JWT_TOKEN_NAME, jwtToken);
                            localStorage.setItem(Property.JWT_TOKEN_NAME, jwtToken);
                        }
                    }

                    // 사용자아이디 로컬스토리지에 저장
                    if (loginType.getValue() === 0) {
                        if (rememberUserId.getChecked()) {
                            localStorage.setItem('loginUserId', values.userId);
                        }
                        else {
                            localStorage.removeItem('loginUserId');
                        }
                        localStorage.removeItem('loginType');
                    }
                    else {
                        localStorage.setItem('loginType', 'PASSCODE');
                    }

                    // 어플리케이션 데이터 초기화
                    me.INIT_APPLICATION_DATA(result);
                    // 메인화면 표시
                    me.REDIRECT(Property.ROUTE_HOME);
                },
                failure: function(response, opts) {
                    Ext.Viewport.setMasked(false);
                    var me = this,
                        vm = me.getViewModel(),
                        refs = me.getReferences(),
                        loginType = refs.loginType,
                        password = refs.password,
                        fastPassword = refs.fastPassword,
                        idErrMsg = refs.idErrMsg,
                        fastErrMsg = refs.fastErrMsg;

                    vm.set('isProcessLogin', false);
                    password.setValue(null); // 입력된 비밀번호제거
                    fastPassword.setValue(null);

                    if (loginType.getValue() === 0 ) {
                        password.focus(true);
                    }
                    else {
                        fastPassword.focus(true);
                    }

                    // 권한오류인 경우, 오류메시지 표시하고 별도의 예외처리하지 않음
                    if (response && response.status === 401) {
                        var errMsg = '아이디 또는 비밀번호를 다시 확인하세요.<br />등록되지 않은 아이디이거나, 아이디 또는 비밀번호를 잘못 입력하셨습니다.';

                        if (response.hasOwnProperty('responseText')) {
                            var responseJson = Ext.JSON.decode(response.responseText);
                            if (responseJson.hasOwnProperty('moreInfo')) {
                                var moreInfo = responseJson.moreInfo;
                                for (var key in moreInfo) {
                                    var msg = moreInfo[key];
                                    if (msg) {
                                        errMsg = msg;
                                    }
                                    break;
                                }
                            }
                        }

                        if (loginType.getValue() === 0) {
                            idErrMsg.setHtml(errMsg);
                        }
                        else {
                            fastErrMsg.setHtml(errMsg);
                        }
                        return;
                    }

                    // failure 를 직접구현하는 경우, 공통 실패응답처리 메소드를 호출한다.
                    me.HANDLE_RESPONSE_FAILURE(response, opts);
                }
            });

        })
        .catch(function(res){

            vm.set('isProcessLogin', false);

            if(res.status == 0 || res.status == 404){
                Ext.Msg.alert(Property.SYSTEM_NAME, '서버와 연결이 원활하지 않습니다.<br />인터넷 연결 상태를 확인하고 다시 시도해주시길 바랍니다.');
            }
        });


    },

    onPasswordfieldKeyup: function(textfield, e, eOpts) {
        var me = this,
            vm = me.getViewModel(),
            value = textfield.getValue(),
            isProcessLogin = vm.get('isProcessLogin');

        if (!value || isProcessLogin) {
            return;
        }

        var strVal = value + '';
        if (strVal.length >= 6) {
            me.onLoginTap();
        }
    }

});