/*
 * File: app/view/common/NativeTestView.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BNK.view.common.NativeTestView', {
    extend: 'Ext.Panel',
    alias: 'widget.NativeTestView',

    requires: [
        'BNK.view.common.NativeTestViewViewModel',
        'BNK.view.common.NativeTestViewViewController',
        'Ext.form.Panel',
        'Ext.field.Text',
        'Ext.Img',
        'Ext.Button'
    ],

    controller: 'common.nativetestview',
    viewModel: {
        type: 'common.nativetestview'
    },
    scrollable: true,
    title: 'Native Test View',

    items: [
        {
            xtype: 'formpanel',
            defaults: {
                disabled: true,
                clearable: false
            },
            title: 'Device',
            items: [
                {
                    xtype: 'textfield',
                    reference: 'txtUuid',
                    label: 'UUID'
                },
                {
                    xtype: 'textfield',
                    reference: 'txtModel',
                    label: 'MODEL'
                },
                {
                    xtype: 'textfield',
                    reference: 'txtPlatform',
                    label: 'PLATFORM'
                },
                {
                    xtype: 'textfield',
                    reference: 'txtVersion',
                    label: 'VERSION'
                },
                {
                    xtype: 'textfield',
                    reference: 'txtSerial',
                    label: 'SERIAL'
                }
            ]
        },
        {
            xtype: 'formpanel',
            reference: 'formCamera',
            title: 'CAMERA',
            items: [
                {
                    xtype: 'image',
                    reference: 'imgPhoto',
                    height: 200,
                    name: 'image'
                },
                {
                    xtype: 'container',
                    layout: 'hbox',
                    items: [
                        {
                            xtype: 'button',
                            flex: '1',
                            ui: 'action',
                            text: '사진촬영',
                            listeners: {
                                tap: 'onButtonTap'
                            }
                        },
                        {
                            xtype: 'button',
                            flex: '1',
                            ui: 'action',
                            text: '불러오기',
                            listeners: {
                                tap: 'onBtnLoadPhotoTap'
                            }
                        },
                        {
                            xtype: 'button',
                            flex: '1',
                            ui: 'action',
                            text: '서버전송',
                            listeners: {
                                tap: 'onBtnSubmitTap'
                            }
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'formpanel',
            title: 'GPS',
            items: [
                {
                    xtype: 'textfield',
                    reference: 'latitude',
                    label: 'latitude'
                },
                {
                    xtype: 'textfield',
                    reference: 'longitude',
                    label: 'longitude'
                },
                {
                    xtype: 'textfield',
                    reference: 'altitude',
                    label: 'altitude'
                },
                {
                    xtype: 'textfield',
                    reference: 'accuracy',
                    label: 'accuracy'
                },
                {
                    xtype: 'textfield',
                    reference: 'altitudeAccuracy',
                    label: 'altitudeAccuracy'
                },
                {
                    xtype: 'textfield',
                    reference: 'heading',
                    label: 'heading'
                },
                {
                    xtype: 'textfield',
                    reference: 'speed',
                    label: 'speed'
                },
                {
                    xtype: 'textfield',
                    reference: 'timestamp',
                    label: 'timestamp'
                },
                {
                    xtype: 'button',
                    ui: 'action',
                    width: '100%',
                    text: 'Get GPS',
                    listeners: {
                        tap: 'onBtnGetGPSTap'
                    }
                }
            ]
        },
        {
            xtype: 'formpanel',
            layout: 'hbox',
            title: 'LINK',
            items: [
                {
                    xtype: 'button',
                    flex: 1,
                    ui: 'action',
                    text: '문자',
                    listeners: {
                        tap: 'onSms'
                    }
                },
                {
                    xtype: 'button',
                    flex: 1,
                    ui: 'action',
                    text: '전화',
                    listeners: {
                        tap: 'onTel'
                    }
                },
                {
                    xtype: 'button',
                    flex: 1,
                    ui: 'action',
                    text: '이메일',
                    listeners: {
                        tap: 'onEmail'
                    }
                }
            ]
        }
    ]

});