/*
 * File: app/view/common/NoticeBoardManagementMViewModel.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

/*
    모바일 시스템 공통 :: 환경설정 - 모델

    @author BNK시스템/계장/김정균
    @since 2019.06.13
    @version 1.0
    @see

    << 개정이력(Modification Information) >>

    수정일		  수정자                수정내용
    ----------	------------------   --------------------------
    2019.06.13	BNK시스템/계장/김정균   최초 생성
*/
Ext.define('BNK.view.common.NoticeBoardManagementMViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.common.noticeboardmanagementm',

    requires: [
        'Ext.data.Store',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json',
        'Ext.data.field.Field'
    ],

    stores: {
        noticeStore: {
            pageSize: 10,
            autoLoad: true,
            proxy: {
                type: 'ajax',
                extraParams: {
                    criYy: new Date().getFullYear()
                },
                url: 'api',
                headers: {
                    serviceId: 'ComEnvSvc.findAllNoticeSearch',
                    viewId: 'NoticeBoardManagementM'
                },
                reader: {
                    type: 'json',
                    rootProperty: 'page.content',
                    totalProperty: 'page.total'
                }
            },
            fields: [
                {
                    name: 'id'
                },
                {
                    name: 'title'
                },
                {
                    name: 'content'
                },
                {
                    name: 'regDt'
                },
                {
                    name: 'hit'
                },
                {
                    name: 'popYn'
                },
                {
                    name: 'startDt'
                },
                {
                    name: 'endDt'
                },
                {
                    name: 'screenX'
                },
                {
                    name: 'screenY'
                },
                {
                    name: 'width'
                },
                {
                    name: 'height'
                },
                {
                    name: 'comCmmFileId'
                },
                {
                    name: 'useYn'
                },
                {
                    name: 'dlYn'
                }
            ]
        }
    }

});