/*
 * File: app/view/common/VersionInfomationManagementM.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

/*
    모바일 시스템 공통 :: 버전정보 관리 - 화면

    @author BNK시스템/계장/김정균
    @since 2019.06.13
    @version 1.0
    @see

    << 개정이력(Modification Information) >>

    수정일		  수정자                수정내용
    ----------	------------------   ------------------------------------------------
    2019.06.13	BNK시스템/계장/김정균   ExpNteConf01 -> VersionInformationManagement 변경
*/
Ext.define('BNK.view.common.VersionInfomationManagementM', {
    extend: 'Ext.Container',
    alias: 'widget.VersionInfomationManagementM',

    alternateClassName: [
        'VersionInfomationManagementM'
    ],
    requires: [
        'BNK.view.common.VersionInfomationManagementMViewModel',
        'BNK.view.common.VersionInfomationManagementMViewController',
        'Ext.grid.Grid',
        'Ext.grid.column.Column'
    ],

    controller: 'common.versioninfomationmanagementm',
    viewModel: {
        type: 'common.versioninfomationmanagementm'
    },

    items: [
        {
            xtype: 'grid',
            header: false,
            titleBar: {
                hidden: true
            },
            height: '100%',
            width: '100%',
            hideHeaders: true,
            bind: {
                store: '{ExpNteConf01Store}'
            },
            columns: [
                {
                    xtype: 'gridcolumn',
                    flex: '1',
                    dataIndex: 'text',
                    text: '설정명'
                },
                {
                    xtype: 'gridcolumn',
                    flex: '1',
                    align: 'right',
                    cell: {
                        xtype: 'gridcell',
                        encodeHtml: false
                    },
                    dataIndex: 'value',
                    text: '설정값'
                }
            ],
            listeners: {
                select: 'onGridSelect'
            }
        }
    ],
    listeners: {
        initialize: 'initialize'
    }

});