/*
 * File: app/view/HumanResource/hwm/HwmCrtAply04M.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

/*
    모바일 :: (신)근태정정신청 - 상세화면

    @author BNK시스템/계장/지민영
    @since 2020.04.23
    @version 1.0
    @see

    << 개정이력(Modification Information) >>

    수정일		  수정자                  수정내용
    ----------	------------------     --------------------------
    2020.04.23	BNK시스템/계장/지민영     최초 생성
    2020.08.06	BNK시스템/파트너/지민영   bfrHrWrkmEmpWkplcId 사용안함
*/
Ext.define('BNK.view.HumanResource.hwm.HwmCrtAply04M', {
    extend: 'Ext.Container',
    alias: 'widget.HwmCrtAply04M',

    alternateClassName: [
        'HwmCrtAply04M'
    ],
    requires: [
        'BNK.view.HumanResource.hwm.HwmCrtAply04MViewModel',
        'BNK.view.HumanResource.hwm.HwmCrtAply04MViewController',
        'BNK.view.common.ApprovalLineGrid',
        'Ext.field.Date',
        'Ext.picker.Date',
        'Ext.Label',
        'Ext.Spacer',
        'Ext.field.Time',
        'Ext.field.ComboBox',
        'Ext.field.TextArea',
        'Ext.form.Panel',
        'Ext.grid.Grid',
        'Ext.Toolbar',
        'Ext.Button'
    ],

    config: {
        listeners: {
            complete: function() {
                this.getController().onComplete(arguments);
            }
        }
    },

    controller: 'HwmCrtAply04MViewController',
    viewModel: {
        type: 'HwmCrtAply04MViewModel'
    },
    height: '100%',
    scrollable: 'both',

    items: [
        {
            xtype: 'container',
            height: '',
            scrollable: 'both',
            layout: {
                type: 'vbox',
                pack: 'center'
            },
            items: [
                {
                    xtype: 'textfield',
                    reference: 'rqpr',
                    name: 'rqpr',
                    width: '97%',
                    margin: '0 5 0 5',
                    label: '신청자',
                    readOnly: true,
                    editable: false
                },
                {
                    xtype: 'textfield',
                    reference: 'aplDvcdNm',
                    disabled: true,
                    hidden: true,
                    width: '97%',
                    margin: '0 5 0 5',
                    label: '신청구분',
                    readOnly: true,
                    editable: false
                },
                {
                    xtype: 'textfield',
                    reference: 'aplDvcd',
                    hidden: true,
                    width: '97%',
                    margin: '0 5 0 5',
                    label: '신청구분',
                    readOnly: true,
                    editable: false
                },
                {
                    xtype: 'datefield',
                    reference: 'aplWrkDt',
                    width: '97%',
                    margin: '0 5 0 5',
                    label: '근무일자',
                    editable: false,
                    dateFormat: 'Y-m-d',
                    picker: {
                        xtype: 'datepicker',
                        hideOnMaskTap: true,
                        header: false,
                        title: '',
                        dayText: '일',
                        monthText: '월',
                        slotOrder: [
                            'year',
                            'month',
                            'day'
                        ],
                        yearText: '년'
                    },
                    listeners: {
                        change: 'onDatefieldChange'
                    }
                },
                {
                    xtype: 'textfield',
                    reference: 'aplTm',
                    hidden: true,
                    width: '97%',
                    margin: '0 5 0 5',
                    label: '신청구분',
                    readOnly: true,
                    editable: false
                },
                {
                    xtype: 'textfield',
                    reference: 'aplDt',
                    hidden: true,
                    width: '97%',
                    margin: '0 5 0 5',
                    label: '신청구분',
                    readOnly: true,
                    editable: false
                },
                {
                    xtype: 'textfield',
                    reference: 'hrWrkhEmpDayWkplcId',
                    hidden: true,
                    readOnly: true,
                    editable: false
                },
                {
                    xtype: 'container',
                    margin: '0 5 0 5',
                    items: [
                        {
                            xtype: 'textfield',
                            reference: 'bfrHrWrkmWkplcId',
                            hidden: true,
                            label: '근무지ID',
                            readOnly: true,
                            editable: false
                        },
                        {
                            xtype: 'textfield',
                            reference: 'bfrHrWrkmEmpWkplcId',
                            hidden: true,
                            label: '근무지ID',
                            readOnly: true,
                            editable: false
                        },
                        {
                            xtype: 'textfield',
                            reference: 'bfrWkplcNm',
                            disabled: true,
                            tooltip: '근무지명',
                            label: '정정전 근무지',
                            readOnly: true,
                            editable: false
                        }
                    ]
                },
                {
                    xtype: 'container',
                    height: 82,
                    margin: '0 5 0 5',
                    scrollable: false,
                    layout: {
                        type: 'vbox',
                        align: 'start',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'container',
                            height: 15,
                            width: '100%'
                        },
                        {
                            xtype: 'container',
                            height: '',
                            width: '98%',
                            layout: 'hbox',
                            items: [
                                {
                                    xtype: 'label',
                                    style: 'font-size: 12px; color: rgba(17, 17, 17, 0.38)',
                                    html: '정정전 시작 일시'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            height: 8,
                            width: '100%'
                        },
                        {
                            xtype: 'container',
                            width: '97%',
                            layout: 'hbox',
                            items: [
                                {
                                    xtype: 'datefield',
                                    reference: 'bfrCrrStrdt',
                                    disabled: true,
                                    height: '100%',
                                    width: '50%',
                                    editable: false,
                                    dateFormat: 'Y-m-d',
                                    picker: {
                                        xtype: 'datepicker',
                                        hideOnMaskTap: true,
                                        header: false,
                                        title: '',
                                        dayText: '일',
                                        monthText: '월',
                                        slotOrder: [
                                            'year',
                                            'month',
                                            'day'
                                        ],
                                        yearText: '년'
                                    }
                                },
                                {
                                    xtype: 'spacer',
                                    minWidth: '3%'
                                },
                                {
                                    xtype: 'timefield',
                                    reference: 'bfrCrrStrtm',
                                    disabled: true,
                                    height: '100%',
                                    width: '45%',
                                    format: 'H:i'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    height: 76,
                    margin: '0 5 0 5',
                    scrollable: false,
                    layout: {
                        type: 'vbox',
                        pack: 'end'
                    },
                    items: [
                        {
                            xtype: 'container',
                            height: 10,
                            width: '100%'
                        },
                        {
                            xtype: 'container',
                            width: '98%',
                            layout: 'hbox',
                            items: [
                                {
                                    xtype: 'label',
                                    height: '100%',
                                    style: 'font-size: 12px; color: rgba(17, 17, 17, 0.38)',
                                    width: '100%',
                                    html: '정정전 종료 일시'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            height: 8,
                            width: '100%'
                        },
                        {
                            xtype: 'container',
                            width: '97%',
                            layout: 'hbox',
                            items: [
                                {
                                    xtype: 'datefield',
                                    reference: 'bfrCrrEdt',
                                    disabled: true,
                                    height: '100%',
                                    name: '',
                                    width: '50%',
                                    labelAlign: 'right',
                                    dateFormat: 'Y-m-d',
                                    picker: {
                                        xtype: 'datepicker',
                                        hideOnMaskTap: true,
                                        header: false,
                                        title: '',
                                        dayText: '일',
                                        monthText: '월',
                                        slotOrder: [
                                            'year',
                                            'month',
                                            'day'
                                        ],
                                        yearText: '년'
                                    }
                                },
                                {
                                    xtype: 'spacer',
                                    minWidth: '3%'
                                },
                                {
                                    xtype: 'timefield',
                                    reference: 'bfrCrrEdtm',
                                    disabled: true,
                                    height: '100%',
                                    width: '45%',
                                    format: 'H:i'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    margin: '0 5 0 5',
                    items: [
                        {
                            xtype: 'textfield',
                            reference: 'aplHrWrkmWkplcId',
                            hidden: true,
                            label: '근무지ID',
                            readOnly: true,
                            editable: false
                        },
                        {
                            xtype: 'textfield',
                            reference: 'aplHrWrkmEmpWkplcId',
                            hidden: true,
                            label: '근무지ID',
                            readOnly: true,
                            editable: false
                        },
                        {
                            xtype: 'textfield',
                            reference: 'aplWkplcNm',
                            hidden: true,
                            tooltip: '근무지명',
                            label: '정정후 근무지',
                            readOnly: true,
                            editable: false
                        },
                        {
                            xtype: 'combobox',
                            reference: 'cbxAplWkplcNm',
                            label: '정정후 근무지',
                            labelAlign: 'top',
                            readOnly: true,
                            editable: false,
                            listeners: {
                                select: 'onCbxAplWkplcNmSelect'
                            }
                        },
                        {
                            xtype: 'label',
                            reference: 'aplWkplcNmErrMsg',
                            hidden: true,
                            html: '<span style = "color:red;font-size:10px">등록된 근무지가 없습니다. 근무지를 먼저 등록하시기 바랍니다.</span>'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    height: 76,
                    margin: '0 5 0 5',
                    scrollable: false,
                    layout: {
                        type: 'vbox',
                        pack: 'end'
                    },
                    items: [
                        {
                            xtype: 'container',
                            height: 10,
                            width: '100%'
                        },
                        {
                            xtype: 'container',
                            width: '98%',
                            layout: 'hbox',
                            items: [
                                {
                                    xtype: 'label',
                                    height: '100%',
                                    style: 'font-size: 12px; color: rgba(17, 17, 17, 0.38)',
                                    width: '100%',
                                    html: '정정후 시작 일시'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            height: 8,
                            width: '100%'
                        },
                        {
                            xtype: 'container',
                            width: '97%',
                            layout: 'hbox',
                            items: [
                                {
                                    xtype: 'datefield',
                                    reference: 'aplWrkStrdt',
                                    height: '100%',
                                    name: '',
                                    width: '50%',
                                    labelAlign: 'right',
                                    required: true,
                                    dateFormat: 'Y-m-d',
                                    picker: {
                                        xtype: 'datepicker',
                                        hideOnMaskTap: true,
                                        header: false,
                                        title: '',
                                        dayText: '일',
                                        monthText: '월',
                                        slotOrder: [
                                            'year',
                                            'month',
                                            'day'
                                        ],
                                        yearText: '년'
                                    }
                                },
                                {
                                    xtype: 'spacer',
                                    minWidth: '3%'
                                },
                                {
                                    xtype: 'timefield',
                                    reference: 'aplWrkStrtm',
                                    height: '100%',
                                    width: '45%',
                                    format: 'H:i'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    height: 76,
                    margin: '0 5 0 5',
                    scrollable: false,
                    layout: {
                        type: 'vbox',
                        pack: 'end'
                    },
                    items: [
                        {
                            xtype: 'container',
                            height: 10,
                            width: '100%'
                        },
                        {
                            xtype: 'container',
                            width: '100%',
                            layout: 'hbox',
                            items: [
                                {
                                    xtype: 'label',
                                    height: '100%',
                                    style: 'font-size: 12px; color: rgba(17, 17, 17, 0.38)',
                                    width: '100%',
                                    html: '정정후 종료 일시'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            height: 8,
                            width: '100%'
                        },
                        {
                            xtype: 'container',
                            width: '97%',
                            layout: 'hbox',
                            items: [
                                {
                                    xtype: 'datefield',
                                    reference: 'aplWrkEdt',
                                    height: '100%',
                                    name: '',
                                    width: '50%',
                                    labelAlign: 'right',
                                    required: true,
                                    dateFormat: 'Y-m-d',
                                    picker: {
                                        xtype: 'datepicker',
                                        hideOnMaskTap: true,
                                        header: false,
                                        title: '',
                                        dayText: '일',
                                        monthText: '월',
                                        slotOrder: [
                                            'year',
                                            'month',
                                            'day'
                                        ],
                                        yearText: '년'
                                    }
                                },
                                {
                                    xtype: 'spacer',
                                    minWidth: '3%'
                                },
                                {
                                    xtype: 'timefield',
                                    reference: 'aplWrkEdtm',
                                    height: '100%',
                                    width: '45%',
                                    format: 'H:i'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    height: 150,
                    margin: '0 5 0 5',
                    scrollable: true,
                    items: [
                        {
                            xtype: 'textareafield',
                            reference: 'aplCntn',
                            name: '',
                            width: '97%',
                            margin: '0 5 0 5',
                            label: '사유'
                        }
                    ]
                },
                {
                    xtype: 'formpanel',
                    reference: 'form',
                    width: '100%',
                    items: [
                        {
                            xtype: 'textfield',
                            hidden: true,
                            name: 'version',
                            label: 'version',
                            bind: {
                                value: '{formValues.version}'
                            }
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'common.approvallinegrid',
            reference: 'approvalLineGrid',
            height: 0,
            hidden: true,
            maxHeight: 0
        },
        {
            xtype: 'toolbar',
            reference: 'button',
            width: '100%',
            docked: 'bottom',
            items: [
                {
                    xtype: 'button',
                    flex: 1,
                    text: '결재선',
                    listeners: {
                        tap: 'onBtnAplyLineTap'
                    }
                },
                {
                    xtype: 'button',
                    flex: 1,
                    text: '결재',
                    listeners: {
                        tap: 'onBtnAplyTap'
                    }
                }
            ]
        }
    ],
    listeners: {
        initialize: 'Initialize'
    }

});