/*
 * File: app/view/HumanResource/hwm/HwmCrtAply02MViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

/*
    모바일 :: (신)근태정정신청 - 상세컨트롤러

    @author BNK시스템/계장/지민영
    @since 2020.04.23
    @version 1.0
    @see

    << 개정이력(Modification Information) >>

    수정일		  수정자                수정내용
    ----------	------------------   --------------------------
    2020.04.23	BNK시스템/계장/지민영   최초 생성
    2020.07.06  BNK시스템/계장/지민영   (웹동기화) 근태정정 신청시 근무지없음이 근무지에 뜨지 않도록 수정
    2021.08.18  BNK시스템/파트너/서무성	 휴일일 경우, 정정 신청 못하도록 disable 처리 로직 추가
*/
Ext.define('BNK.view.HumanResource.hwm.HwmCrtAply02MViewController', {
    extend: 'BaseViewController',
    alias: 'controller.HwmCrtAply02MViewController',

    config: {
        parentView: 'null',
        viewId: 'HwmCrtAply02M'
    },

    /* 기타영수증 필수값 검증 */
    formValid: function(formData) {
        var me = this,
            vm = me.getViewModel(),
            refs = me.getReferences(),
            reNo = /[^\d]/,
            errMsg = '';

        if(!formData.aplWrkStrdt){
            errMsg += '정정후 시작일을 입력 하여주세요<br>';
        }
        if(!formData.aplWrkStrtm){
            errMsg += '정정후 시작시간을 입력해주세요.<br>';
        }
        if(!formData.aplWrkEdt){
            errMsg += '정정후 종료일을 입력해주세요.<br>';
        }
        if(!formData.aplWrkEdtm){
            errMsg += '정정후 종료시간을 입력해주세요.<br>';
        }
        if(!formData.aplWkplcNm){
            errMsg += '정정후 근무지를 입력해주세요.<br>';
        }
        if(!formData.aplCntn){
            errMsg += '사유를 입력해주세요.<br>';
        }


        if(!vm.get('applyLine')){
            errMsg += '결재선을 선택해주세요.';
        }

        if(errMsg != ''){
            return errMsg;
        }

        // 날자관련 데이터 변환
        var dateCompoList = ['aplWrkStrdt',
                             'aplWrkEdt'];
        var dateData = new Object();
        for(var key in dateCompoList ){
            var dateObj = refs[dateCompoList[key]];
            var date = dateObj.getValue();
            var tempMonth = date.getMonth()+1 ;
            tempMonth += "";
            tempMonth = (tempMonth.length == 1 ? "0" :"") + tempMonth;
            dateData[dateCompoList[key]] = date.getFullYear() +"" + tempMonth + ""+date.getDate();
        }


        // 시간관련 데이터 변환
        var hourCompoList  = ['aplWrkStrtm',
                              'aplWrkEdtm'];

        for(var key in hourCompoList ){
            var timeObj = refs[hourCompoList[key]].getValue();
            var hh = timeObj.getHours()+"";
            var mi = timeObj.getMinutes()+"";
            hh = (hh.length == 1 ? '0' : "") + hh;
            mi = (mi.length == 1 ? '0' : "") + mi;

            dateData[hourCompoList[key]] = hh + "" + mi +"00";
        }


        var st = dateData.hodStrdt+dateData.hodStrtm;
        var ed =dateData.hodEdt+dateData.hodEdtm;

        st =st*1;
        ed = ed*1;

        if(st > ed){
            errMsg += '시작일시는 종료일 보다 클 수 없습니다. <br>';
        }


        return errMsg;

    },

    approvalLineGridSetData: function() {
        var me = this,
            vm = me.getViewModel(),
            refs = me.getReferences(),
            gridData = vm.get('applyLine');

        //refs.approvalLineGrid.setData(gridData);

    },

    onComplete: function() {
        var me = this,
            vm = me.getViewModel();

        var win = Ext.create('ExpNteAply51M'); // 결과 완료 팝업

        var sumScreen = win.getReferences().sumScreen;
        var message = win.getReferences().message;
        sumScreen.setVisibility(false);
        message.setHtml("근태정정 신청을 완료 하였습니다");
        me.mon(win, 'destroy', function() {
            var me = this,
                //home = Ext.getCmp(Property.ROUTE_HOME),
                home = this.getView().up(Property.ROUTE_HOME),
                naviView = home.lookup('NaviView'),
                backButton = naviView.getNavigationBar().getBackButton();
            me.getParentView().controller.search();
            me.getParentView().controller.defaut();
            backButton.onTap();	// 뒤로가기

        }, me);

        win.show();
    },

    dateFormat: function(date) {

        var month = (date.getMonth()+1) +"";
        month = month.length == 1 ? "0" + month: month;
        var dateDD = date.getDate()+"";
        dateDD = dateDD.length == 1 ? "0" + dateDD: dateDD;
        var toDate = date.getFullYear()  +'-'+ month +'-'+ dateDD;
        return toDate;

    },

    onDatefieldChange: function(datefield, newDate, oldDate, eOpts) {
        var me = this,
            vm = me.getViewModel(),
            refs = me.getReferences(),
            viewId = 'HwmCrtAply02M';

        if(!datefield.validate()){
            refs.bfrCrrStrdt.setValue("");
            refs.bfrCrrStrtm.setValue("");
            refs.bfrCrrEdt.setValue("");
            refs.bfrCrrEdtm.setValue("");
            refs.aplWrkStrdt.setValue("");
            refs.aplWrkStrtm.setValue("");
            refs.aplWrkEdt.setValue("");
            refs.aplWrkEdtm.setValue("");

            refs.aplEmpeInfoForm.setDisabled(true);
            Ext.Msg.alert("안내", "근무일자를 확인 부탁드립니다.");

            return;
        }

        var param = {
            stlmDvcd : '09',
            aplStcd : '11',
            aplTct : 1, // 총 건수
        };


        param.stcd = Constants.stcd.OUTSTANDING;
        param.hrHrpmEmpId = SecurityUtils.getPrincipal().hrHrpmEmpId;
        param.aplWrkDt = me.dateFormat(newDate).replace(/-/g,'');

        if(vm.check == "clicked" ){
            vm.check = '';
            return;
        }

        Ext.Ajax.request({
            headers : {
                serviceId : 'HwmCrtSvc.findAllHwmCrtAply',
                viewId : viewId
            },
            scope : me,
            jsonData :param,
            success : function(response) {
                var ob = JSON.parse(response.responseText);
                var content = ob.page.content;
                var strJson = JSON.stringify(content);

                // 호출한 데이터가 있는지 없는지 확인
                var checkFun = function(data){
                    for(var i in content){
                        var temp = content[i];
                        if(temp.name == data){
                            return temp;
                        }
                    }
                    return null;
                };

                var temp = null;

                var checkData = ["hrWrkiDayCrr", "hrWrkiDay" ,"hrWrkdCri"];
                // 결과값 대상으로 우선순위대로 데이터 호출후 해당 이름 데이터가 있을 화면에 출력
                for(var i in checkData){
                    temp = checkFun(checkData[i]);
                    if(temp != null){
                        break;
                    }
                }

                var message = "";

                var MSG_NOCHULGUN = refs.aplWrkDt.getDisabled() ? "" :"출근 기록이 없습니다.";

                if(temp != null){

                    if(temp.name != "hrWrkdCri"){
                        refs.bfrCrrStrdt.setValue(temp.aplWrkStrdt);
                        refs.bfrCrrStrtm.setValue(temp.aplWrkStrtm);
                        refs.bfrCrrEdt.setValue(temp.aplWrkEdt);
                        refs.bfrCrrEdtm.setValue(temp.aplWrkEdtm);
                        refs.aplWrkEdt.setValue(temp.aplWrkEdt);
                        refs.aplWrkEdtm.setValue(temp.aplWrkEdtm);
                    }else{
                        refs.bfrCrrStrdt.setValue("");
                        refs.bfrCrrStrtm.setValue("");
                        refs.bfrCrrEdt.setValue("");
                        refs.bfrCrrEdtm.setValue("");
                        refs.aplWrkEdt.setValue("");
                        refs.aplWrkEdtm.setValue("");
                        message = MSG_NOCHULGUN;
                    }

                    refs.aplWrkStrdt.setValue(temp.aplWrkStrdt);
                    refs.aplWrkStrtm.setValue('08:50');
                    refs.aplWrkEdt.setValue(temp.aplWrkEdt);
                    refs.aplWrkEdtm.setValue(temp.aplWrkEdtm);
                }else{
                    var date = refs.aplWrkDt.getValue();
                    var tempMonth = date.getMonth()+1 ;
                    tempMonth += "";
                    tempMonth = (tempMonth.length == 1 ? "0" :"") + tempMonth;

                    var dateDD = date.getDate()+"";
                    dateDD = (dateDD.length == 1 ? "0" :"") + dateDD;
                    var resultDt = date.getFullYear() +"-" + tempMonth + "-" + dateDD;

                    refs.bfrCrrStrdt.setValue("");
                    refs.bfrCrrStrtm.setValue("");
                    refs.bfrCrrEdt.setValue("");
                    refs.bfrCrrEdtm.setValue("");
                    refs.aplWrkStrdt.setValue(resultDt);
                    refs.aplWrkStrtm.setValue('08:50');
                    refs.aplWrkEdt.setValue(resultDt);
                    refs.aplWrkEdtm.setValue('18:00');

                    message = MSG_NOCHULGUN;
                }

                if(!Ext.isEmpty(ob.hodHldInfo) && ob.hodHldInfo.hldYn == Constants.yesNo.YES){
                    refs.bfrCrrStrdt.setValue("");
                    refs.bfrCrrStrtm.setValue("");
                    refs.bfrCrrEdt.setValue("");
                    refs.bfrCrrEdtm.setValue("");
                    refs.aplWrkStrdt.setValue("");
                    refs.aplWrkStrtm.setValue("");
                    refs.aplWrkEdt.setValue("");
                    refs.aplWrkEdtm.setValue("");

                    refs.aplEmpeInfoForm.setDisabled(true);
                    Ext.Msg.alert("안내", "휴일인 경우 근태정정이 불가능 합니다.");

                    return;
                }
                else{
                    refs.aplEmpeInfoForm.setDisabled(false);
                }

                // 근무지정보 추가
                var cbxAplWkplc = refs.cbxAplWkplcNm,
                    store = vm.get('WkplcStore'),
                    wkplcInfo = null;

                // findOneHwmCrtAply
                for(var name in content) {
                    if (content[name].name == "wkplcInfo") {
                        wkplcInfo = content[name];
                    }
                }

                store.removeAll();
                cbxAplWkplc.setStore(store);
                cbxAplWkplc.setValue(null);
                if (wkplcInfo == null || wkplcInfo.aplHrWrkmWkplcId == null || wkplcInfo.aplWkplcNm == null) {
                    refs.bfrHrWrkmWkplcId.setValue(null);
                    refs.bfrWkplcNm.setValue(' ');
                } else {
                    refs.bfrHrWrkmWkplcId.setValue(wkplcInfo.aplHrWrkmWkplcId);
                    refs.bfrWkplcNm.setValue(wkplcInfo.aplWkplcNm);
                }
                refs.hrWrkhEmpDayWkplcId.setValue((wkplcInfo == null || wkplcInfo.hrWrkhEmpDayWkplcId == null) ? null : wkplcInfo.hrWrkhEmpDayWkplcId);
                refs.aplHrWrkmWkplcId.setValue(null);
                refs.aplHrWrkmEmpWkplcId.setValue(null);
                refs.aplWkplcNm.setValue(null);

                param = {
                    crtDt : DateUtils.getDate(param.aplWrkDt),
                    hrHrpmEmpId : SecurityUtils.getPrincipal().hrHrpmEmpId,
                    stcd : Constants.stcd.NORMAL,
                    filterHrWrkmWkplcId : Constants.wkplcId.EMPTY_WKPLC //'근무지없음'에 대한 데이터 제외
                };

                Ext.Ajax.request({
                    headers : {
                        serviceId : 'HwmWplSvc.findAllHwmWplInfo',
                        viewId : viewId,
                        scope : me
                    },
                    jsonData : param,
                    success : function(response){
                        var wkplcList = [],
                            cbxAplWkplc = refs.cbxAplWkplcNm,
                            res = JSON.parse(response.responseText);

                        for(var i in res.page){
                            var value = {
                                wkplcNm : res.page[i].wkplcNm,
                                hrWrkmWkplcId : res.page[i].hrWrkmWkplcId,
                                hrWrkmEmpWkplcId : res.page[i].hrWrkmEmpWkplcId,
                            };

                            var item = store.data.items,
                                cnt = 0;
                            for (var j in item) {
                                if (item[j].data.value.hrWrkmWkplcId == value.hrWrkmWkplcId) {
                                    cnt++;
                                    break;
                                }
                            }
                            if (item.length == 0 || cnt == 0) {
                                store.add({ text : res.page[i].wkplcNm, value : value});
                            }
                        }
                        cbxAplWkplc.setStore(store);
                        cbxAplWkplc.setValue((store.getAt(0) != null) ? store.getAt(0).get('value') : null);
                        //               if (!(cbxAplWkplc.getValue())) {
                        //                   refs.aplWkplcNmErrMsg.setHidden(false);
                        //               } else {
                        //                   refs.aplWkplcNmErrMsg.setHidden(true);
                        //               }
                    }
                });

                if(message != ""){
                    Ext.Msg.alert('확인', MSG_NOCHULGUN);
                }
            }
        });

    },

    /* 근무지 선택 */
    onCbxAplWkplcNmSelect: function(combobox, newValue, oldValue, eOpts) {
        var me = this,
            vm = me.getViewModel(),
            refs = me.getReferences();

        if (newValue != null) {
            var data = newValue.data.value;
            refs.aplHrWrkmEmpWkplcId.setValue(data.hrWrkmEmpWkplcId);
            refs.aplHrWrkmWkplcId.setValue(data.hrWrkmWkplcId);
            refs.aplWkplcNm.setValue(data.wkplcNm);
        }

        // 근무지정보 리로드
        var store = vm.get('WkplcStore');
        if (refs.aplWrkDt.getValue() != null) {
            param = {
                crtDt : DateUtils.getDate(refs.aplWrkDt.getValue()),
                hrHrpmEmpId : SecurityUtils.getPrincipal().hrHrpmEmpId,
                stcd : Constants.stcd.NORMAL
            };

            Ext.Ajax.request({
                headers : {
                    serviceId : 'HwmWplSvc.findAllHwmWplInfo',
                    viewId : 'HwmCrtAply02M',
                    scope : me
                },
                jsonData : param,
                success : function(response){
                    var res = JSON.parse(response.responseText);
                    if (store.data != null) {
                        store.removeAll();

                        for(var i in res.page){
                            var value = {
                                wkplcNm : res.page[i].wkplcNm,
                                hrWrkmWkplcId : res.page[i].hrWrkmWkplcId,
                                hrWrkmEmpWkplcId : res.page[i].hrWrkmEmpWkplcId,
                            };

                            var item = store.data.items,
                                cnt = 0;
                            for (var j in item) {
                                if (item[j].data.value.hrWrkmWkplcId == value.hrWrkmWkplcId) {
                                    cnt++;
                                    break;
                                }
                            }
                            if (item.length == 0 || cnt == 0) {
                                store.add({ text : res.page[i].wkplcNm, value : value});
                            }
                        }
                        combobox.setStore(store);
                    }
                }
            });
        }
    },

    Initialize: function(component, eOpts) {
        var me = this;
        var vm = me.getViewModel();
        var refs = me.getReferences();
        var items = component.records;
        var aplTotSmamt = 0;
        me.setParentView(component.parentView);

        var componentList = [
        ,'bfrCrrStrdt'
        ,'bfrCrrStrtm'
        ,'bfrCrrEdt'
        ,'bfrCrrEdtm'
        ,'aplWrkStrdt'
        ,'aplWrkStrtm'
        ,'aplWrkEdt'
        ,'aplWrkEdtm'
        ,'aplCntn'
        ,'aplDvcd'
        ,'aplWrkDt'
        ,'bfrHrWrkmWkplcId'
        ,'bfrWkplcNm'
        ,'aplHrWrkmEmpWkplcId'
        ,'aplHrWrkmWkplcId'
        ,'aplWkplcNm'];

        // aplWrkDt 는 맨마지막에 두어서 자동으로 데이터 입력시 데이터 정정이 되지 않도록 함

        if(items.length == 0){
            var vm = me.getViewModel();
            var principal = SecurityUtils.getPrincipal();
            var ovwUsr = principal.hrHrpmEmpId+" / "+ principal.dpnm + " / " +
            principal.empeNm +" / " + principal.empePsitNm;
            refs.rqpr.setValue(ovwUsr);
            refs.aplDvcd.setValue(Constants.wrkAplDvcd.APPLY );

            refs.aplCntn.setValue('근태 정정 신청하겠습니다.');
            vm.check = "";

            var date = new Date();
            var nHour = date.getHours();
            nHour = nHour  < 10 ? '0'+nHour :  nHour;
            var nMin = date.getMinutes();
            nMin = nMin  < 10 ? '0'+nMin :  nMin;
            var nSec = date.getSeconds();
            nSec = nSec  < 10 ? '0'+nSec :  nSec;
            refs.aplTm.setValue(nHour+""+nMin+""+nSec);
            refs.cbxAplWkplcNm.setHidden(false);
            refs.aplWkplcNm.setHidden(true);
            refs.bfrWkplcNm.setValue(' ');

        }else{
            vm.check = "clicked";
            var data = items[0].data;

            var ovwUsr = data.empeNo +" / "+data.dpnm +" / "+data.empeNm +" / "+data.lv ;
            refs.rqpr.setValue(ovwUsr);
            refs.button.setVisibility(false);
            for(var i in componentList){
                var compNm = componentList[i];
                var temp = refs[compNm];
                temp.setValue(data[compNm]);
                temp.setDisabled(true);
            }

            refs.aplTm.setValue(data.aplTm);
            refs.cbxAplWkplcNm.setHidden(true);
            refs.aplWkplcNm.setHidden(false);

            if (data.bfrWkplcNm == null) {
                refs.bfrWkplcNm.setValue(' ');
            }
            if (data.aplWkplcNm == null) {
                refs.aplWkplcNm.setValue(' ');
            }
        }

        refs.aplWrkStrtm.el.select('.x-error-el').setStyle('margin',	'0px');
        refs.aplWrkEdtm.el.select('.x-error-el').setStyle('margin','0px');

        refs.bfrCrrStrtm.el.select('.x-error-el').setStyle('margin','0px');
        refs.bfrCrrEdtm.el.select('.x-error-el').setStyle('margin',	'0px');

        ApprovalBoxSvc.setup({
            command   : Constants.sanction.DRAFT,
            viewModel : vm,
            edocCd    : 'HwmCrtAply71',
            scope     : me
        });

        refs.aplWrkDt.setMaxDate(DateUtils.addDate(new Date(), -1));

    },

    /* 결재선 버튼 클릭 이벤트 */
    onBtnAplyLineTap: function(button, e, eOpts) {
        var me = this,
            vm = me.getViewModel(),
            refs = me.getReferences(),
            win = Ext.create('BNK.view.common.ApprovalLinePopup', {});

        me.mon(win, 'selected', function(data, popup) {
            popup.close();

            vm.set('applyLine', data);
            var me = this,
                refs = me.getReferences(),
                approvalLineGrid = refs.approvalLineGrid;

            ApprovalBoxSvc.setApprovalLine({
                scope               : me,
                command             : Constants.sanction.DRAFT, // 결재선구분자 : 기안(01)
                approvalLineGrid    : approvalLineGrid,   // 결재선 그리드 객체
                approvalLineRecords : data        // 결재선선택 데이터
            });

        }, me);


        win.show();
    },

    /* 결재 버튼 클릭 이벤트 */
    onBtnAplyTap: function(button, e, eOpts) {
        var me = this,
            vm = me.getViewModel(),
            refs = me.getReferences(),
            docNm = '근태정정 신청서',
            approvalLineGrid = refs.approvalLineGrid,
            aprHistId = null;

        var afterchange = {
            stlmDvcd : '09',
            aplStcd : '11',
            aplTct : 1, // 총 건수
        };

        afterchange.id = Ext.id();
        afterchange.crud = 'C';
        // 사용자가 신청
        afterchange.crrDvcd = '10';
        afterchange.rqpr =refs.rqpr.getValue() ;
        afterchange.aplDvcd =refs.aplDvcd.getValue() ;
        afterchange.stcd = Constants.stcd.OUTSTANDING;

        if(!refs.aplWrkDt.getValue()){
            Ext.Msg.alert('확인','근무일자를 선택해주시기 바랍니다.');
            return;
        } else if(!(refs.aplWrkStrdt.getValue() && refs.aplWrkEdt.getValue() &&
        refs.aplWrkStrtm.getValue() && refs.aplWrkEdtm.getValue() &&
        refs.aplWkplcNm.getValue())){
            Ext.Msg.alert('확인','정정후 값을 모두 입력해주시기 바랍니다. <br> 근무지가 없는경우, 근무지 변경 신청 후 정정 바랍니다.');
            return;
        } else if(!refs.bfrCrrStrdt.getValue() && !refs.bfrCrrEdt.getValue() &&
        !refs.bfrCrrEdtm.getValue() && !refs.bfrCrrEdtm.getValue()) {
        } else if((refs.bfrCrrStrdt.getValue() === null ? 0 : refs.bfrCrrStrdt.getValue().toString() == refs.aplWrkStrdt.getValue().toString()) &&
        (refs.bfrCrrEdt.getValue() === null ? 0 : refs.bfrCrrEdt.getValue().toString() == refs.aplWrkEdt.getValue().toString()) &&
        (refs.bfrCrrStrtm.getValue() === null ? 0 : refs.bfrCrrStrtm.getValue().toString() == refs.aplWrkStrtm.getValue().toString()) &&
        (refs.bfrCrrEdtm.getValue() === null ? 0 : refs.bfrCrrEdtm.getValue().toString() == refs.aplWrkEdtm.getValue().toString()) &&
        (refs.bfrWkplcNm.getValue() == refs.aplWkplcNm.getValue())){
            Ext.Msg.alert('확인','정정 전/후 값이 동일합니다.');
            return;
        }

        // 날자관련 데이터 변환
        var dateCompoList = ['aplWrkDt',
            'aplWrkStrdt',
            'aplWrkEdt',
            'bfrCrrStrdt',
            'bfrCrrEdt'
            ];

        for(var key in dateCompoList ){
            var dateObj = refs[dateCompoList[key]];
            var date = dateObj.getValue();
            if(date != null){
                var tempMonth = date.getMonth()+1 ;
                tempMonth += "";
                tempMonth = (tempMonth.length == 1 ? "0" :"") + tempMonth;

                var dateDD = date.getDate()+"";
                dateDD = (dateDD.length == 1 ? "0" :"") + dateDD;
                afterchange[dateCompoList[key]] = date.getFullYear() +"" + tempMonth + "" + dateDD;
            }else{
                afterchange[dateCompoList[key]] = null;

            }
        }



        // 시간관련 데이터 변환
        var hourCompoList  = [
        'aplWrkStrtm',
        'aplWrkEdtm',
        'bfrCrrStrtm',
        'bfrCrrEdtm'];

        for(var key in hourCompoList ){
            var timeObj = refs[hourCompoList[key]].getValue();

            if(timeObj != null){
                var hh = timeObj.getHours()+"";
                var mi = timeObj.getMinutes()+"";
                hh = (hh.length == 1 ? '0' : "") + hh;
                mi = (mi.length == 1 ? '0' : "") + mi;
                afterchange[hourCompoList[key]] = hh + "" + mi +"00";
            }else{
                afterchange[hourCompoList[key]] = null;
            }

        }


        afterchange.hrHrpmEmpId = SecurityUtils.getPrincipal().hrHrpmEmpId;
        afterchange.aplCntn = refs.aplCntn.getValue();
        var date = new Date();
        var nDt = Ext.Date.format(date, 'Ymd');
        var nHour = date.getHours();
        nHour = nHour  < 10 ? '0'+nHour :  nHour;
        var nMin = date.getMinutes();
        nMin = nMin  < 10 ? '0'+nMin :  nMin;
        var nSec = date.getSeconds();
        nSec = nSec  < 10 ? '0'+nSec :  nSec;
        refs.aplTm.setValue(nHour+""+nMin+""+nSec);
        refs.aplDt.setValue(nDt);

        afterchange.aplTm =nHour+""+nMin+""+nSec;
        afterchange.aplDt =nDt;

        // 근무지 데이터
        var wkplcCompoList = [
        'bfrHrWrkmWkplcId',
        'bfrWkplcNm',
        'aplHrWrkmEmpWkplcId',
        'aplHrWrkmWkplcId',
        'aplWkplcNm',
        'hrWrkhEmpDayWkplcId'
        ];

        for(var key in wkplcCompoList ){
            afterchange[wkplcCompoList[key]] = refs[wkplcCompoList[key]].getValue();
        }

        var formData = afterchange;


        afterchange.upcheck ="chk";
        // 결재이력데이터조회
        Ext.Ajax.request({
            headers : {
                serviceId : 'HwmCrtSvc.findAllHwmCrtAply',
                viewId : 'HwmCrtAply02M'
            },
            scope : me,
            jsonData :afterchange,
            success : function(response) {
                var ob = JSON.parse(response.responseText);

                var row1Cnt = ob.totalCnt;
                var row2Cnt = ob.monthCnt;
                var row3Cnt = ob.crrCnt;

                if(row1Cnt > 0){
                    Ext.Msg.alert('확인','결재중인 문서가 있습니다. <br/>결재를 먼저 취소하고 진행해 주시길 바랍니다. ');
                    return;
                }

                if(row2Cnt > 0){
                    Ext.Msg.alert('확인','월근태 결재 내역이 있습니다. <br/> 결재를 취소한 뒤 신청 부탁드리겠습니다.');
                    return;
                }

                if(row3Cnt === 0){
                    Ext.Msg.alert('확인','보정회차가 존재하지 않습니다. <br/> 관리자에게 문의하십시오.');
                    return;
                }


                // + 버튼이 아님(formValid 에서 필요)
                formData.btnPlus = false;
                var errMsg = this.formValid(formData);
                if(errMsg.length > 0){
                    Ext.Msg.alert('입력값을 확인해주세요.', errMsg);
                    return false;
                }


                ApprovalBoxSvc.draft({
                    scope                 : me,
                    edocCd                : 'HwmCrtAply71',				 	 		// 전자문서관리에서 설정된 문서코드: 화면ID를 사용함
                    docNm                 : docNm, 							 		// 문서명
                    bizDvcd               : 'HWM', 							 		// 업무구분코드
                    bizServiceId          : 'HwmCrtSvc.saveHwmCrtAply',   // 연관 업무서비스ID
                    aprHistId             : null,						 	 		// 결재이력ID
                    approvalLineRecords   : approvalLineGrid.getJsonAllRecords(), 	// 결재선 그리드 데이터
                    docData               : {								 		// 결재문서 데이터
                        fieldValues       : vm.get('fieldValues'),
                        beforechange      : null,
                        afterchange       : afterchange 			 // 결재문서 필드값
                    }
                });



            }
        });

    }

});