/*
 * File: app/view/HumanResource/hwm/HwmCrtAply01MViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

/*
    모바일 :: (신)근태정정신청 - 컨트롤러

    @author BNK시스템/계장/지민영
    @since 2020.04.23
    @version 1.0
    @see

    << 개정이력(Modification Information) >>

    수정일		  수정자                수정내용
    ----------	------------------   --------------------------
    2020.04.23	BNK시스템/계장/지민영   최초 생성
*/
Ext.define('BNK.view.HumanResource.hwm.HwmCrtAply01MViewController', {
    extend: 'BaseViewController',
    alias: 'controller.HwmCrtAply01MViewController',

    config: {
        viewId: 'HwmCrtAply01M'
    },

    search: function(params) {
        var me = this,
            vm = me.getViewModel(),
            refs = me.getReferences(),
            params = params || {},
            store = vm.storeInfo.Store;

        params.hrHrpmEmpId = SecurityUtils.getPrincipal().hrHrpmEmpId;




        var dateCompont = ['startDate',
                           'endDate'
                          ];

        if(refs[dateCompont[0]].getValue() > refs[dateCompont[1]].getValue()){
            Ext.Msg.alert('확인','시작일이 종료일보다 클 수 없습니다.');
            return;

        }

        for(var key in dateCompont ){
            var dateObj = refs[dateCompont[key]];
            var date = dateObj.getValue();
            var tempMonth = date.getMonth()+1 ;
            var tempDate = date.getDate();
            tempMonth += "";
            tempMonth = (tempMonth.length == 1 ? "0" :"") + tempMonth;
            tempDate += "";
            tempDate = (tempDate.length == 1 ? "0" :"") + tempDate;
            params[dateCompont[key]] = date.getFullYear() +"" + tempMonth + ""+tempDate;
        }


        if(params =={}){
            store.getProxy().extraParams.page = 1;
            var toolbar = refs.grid.getPlugins()[0];
            toolbar.setCurrentPage(1);

        }else{
            store.getProxy().extraParams = params;

        }

        store.removeAll();
        store.load();


    },

    defaut: function() {
        var me = this,
            vm = me.getViewModel(),
            refs = me.getReferences(),
            store = vm.storeInfo.Store;

        store.getProxy().extraParams.page = 1;
        var toolbar = refs.grid.getPlugins()[0];
        toolbar.setCurrentPage(1);


    },

    showView: function(itemId) {
                var me = this;
                me.getView().setActiveItem(itemId);
    },

    onMydateChange11: function(datefield, newDate, oldDate, eOpts) {
        // if(oldDate == null){
        //             return;
        //         }
        // this.search();
    },

    onMydate2Change11: function(datefield, newDate, oldDate, eOpts) {
        // if(oldDate == null){
        //             return;
        //         }
        // this.search();
    },

    onBtnSearchTap111: function(button, e, eOpts) {
        this.defaut();
        this.search();
    },

    onBtnWriteTap: function(button, e, eOpts) {
        var me = this;
        var vm = me.getViewModel();
        var refs = me.getReferences();
        var grid = refs.grid;
        var records = grid.getStore().data.items;
        var naviView = me.getView().up('navigationview');
        me.PUSH_VIEW(naviView, {
            menuId  : 'HwmCrtAply02M',
            title   : '근태 정정 신청',
            records : [],
            isSubView : true,
            parentView : me.getView()
        });


    },

    /* Grid Cell Click Event */
    onMygridSelect: function(dataview, selected, eOpts) {
        var me = this;
        var vm = me.getViewModel();
        var refs = me.getReferences();
        var grid = refs.grid;
        var records = grid.getStore().data.items;
        var trueRecords = selected; // 선택한 row 들

        Ext.Ajax.request({
            headers : {
                serviceId : 'COMAPR0001R04M',
                viewId : 'HwmCrtAply01M',
                scope : me
            },
            jsonData : {
                aprHistId : trueRecords[0].data.comAprHistId,
                // 결재이력ID
            },
            success : function(response) {
                var command = Constants.sanction.COMPLETED_BOX, // 아무 동작도 하지 않아야 하므로 완료.
                res = JSON.parse(response.responseText),
                result = JSON.parse(res.result),
                afterchange =result.docData.afterchange;

                // 근무지정보 추가 (웹은 이력화면이 결재함화면(71), 로직 다름)
                trueRecords[0].data.bfrHrWrkmWkplcId = afterchange.bfrHrWrkmWkplcId;
                trueRecords[0].data.bfrHrWrkmEmpWkplcId = afterchange.bfrHrWrkmEmpWkplcId;
                trueRecords[0].data.bfrWkplcNm = afterchange.bfrWkplcNm;
                trueRecords[0].data.aplHrWrkmWkplcId = afterchange.aplHrWrkmWkplcId;
                trueRecords[0].data.aplHrWrkmEmpWkplcId = afterchange.aplHrWrkmEmpWkplcId;
                trueRecords[0].data.aplWkplcNm = afterchange.aplWkplcNm;

                var naviView = me.getView().up('navigationview');
                me.PUSH_VIEW(naviView, {
                    menuId  : 'HwmCrtAply02M',
                    title   : '근태 정정 신청',
                    records : trueRecords,
                    isSubView : true,
                    parentView : me.getView()
                });
            }
        });

    },

    /* 화면초기화 */
    initialize: function(component, eOpts) {
        var me = this,
            refs = me.getReferences(),
            grid = refs.grid,
            stDt = refs.startDate,
            edDt = refs.endDate,
            cbxCardNo = refs.cbxCardNo;


        var dateMinus1 =new Date();
        dateMinus1.setDate(1);
        stDt.setValue(DateUtils.parseDate(dateMinus1));

        dateMinus1.setMonth(dateMinus1.getMonth()+1);
        dateMinus1.setDate(7);
        edDt.setValue(DateUtils.parseDate(dateMinus1));


        grid.el.select('.x-headercontainer').setStyle('height',	'0px');


        this.search();
    },

    onJsonstoreLoad: function(store, records, successful, operation, eOpts) {
        var me = this;
    }

});