/*
 * File: app/view/HumanResource/hwm/HwmDayAply54MViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

/*
    모바일 시스템 근태관리 :: 출퇴근체크 GPS 위치정보 - 컨트롤러

    @author BNK시스템/계장/김정균
    @since 2019.06.10
    @version 1.0
    @see

    << 개정이력(Modification Information) >>

    수정일		  수정자                수정내용
    ----------	------------------   --------------------------
    2019.06.10	BNK시스템/계장/김정균   최초 생성
*/
Ext.define('BNK.view.HumanResource.hwm.HwmDayAply54MViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.HwmDayAply54MViewController',

    config: {
        viewId: 'HwmDayAply54M'
    },

    getErrMsg: function(code) {
        var msg = '';

        if(code == '1'){
            msg = '권한 확인 필요';
        }
        else if(code == '2'){
            msg = '위치 정보 조회 불가';
        }
        else if(code == '3') {
            msg = '시간 초과';
        }
        else{
            msg = '원인 확인 필요';
        }

        return msg;
    },

    getGps: function(cnt) {
        var me = this;
        var refs = me.getReferences();

        try{

            if(cnt > 100){
                return;
            }

            navigator.geolocation.getCurrentPosition(function(position){

                refs.gpsTotalCount.setHtml(cnt);
                refs.gpsSuccessCount.setHtml(parseInt(refs.gpsSuccessCount.getHtml()) + 1);

                refs.gpsInfo.setHtml(refs.gpsInfo.getHtml() + '<br>[ ' + cnt + ' ] 위도 : ' + position.coords.latitude + ' / 경도 : ' + position.coords.longitude);
                setTimeout(function(){
                    me.getGps(cnt + 1);
                }, 3000);

            }, function(position){

                refs.gpsTotalCount.setHtml(cnt);
                refs.gpsInfo.setHtml(refs.gpsInfo.getHtml() + '<br>[ ' + cnt + ' ] not found position : ' + position.code + ' - ' + me.getErrMsg(position.code));
                setTimeout(function(){
                    me.getGps(cnt + 1);
                }, 3000);

            }, {
                enableHighAccuracy: true,
                timeout: 3000,
                maximumAge: 3000
            });

        }
        catch(err){
            console.log('Fail the getGPS method. And can\'t execute inner process. => '+ e);
        }

    },

    onButtonTap: function(button, e, eOpts) {
        var me = this;

        me.getView().close();
    },

    initialize: function(component, eOpts) {

        var me = this,
            vm = me.getViewModel(),
            refs = me.getReferences();

        try{
            if ('geolocation' in navigator) {
                me.getGps(1);
            }
            else {
                refs.gpsInfo.setHtml('not support gps in this browser');
            }
        }
        catch(err){
            Ext.Msg.alert('알림', err);
        }

    }

});