/*
 * File: app/view/HumanResource/hwm/HwmHodAply01M.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

/*
    모바일 :: 휴일근무신청(조회) - 화면

    @author BNK시스템/파트너/지민영
    @since 2020.09.24
    @version 1.0
    @see

    << 개정이력(Modification Information) >>

    수정일		  수정자                    수정내용
    ----------	--------------------     --------------------------
    2020.09.24	BNK시스템/파트너/지민영     최초 생성
*/
Ext.define('BNK.view.HumanResource.hwm.HwmHodAply01M', {
    extend: 'Ext.Container',
    alias: 'widget.HwmHodAply01M',

    alternateClassName: [
        'HwmHodAply01M'
    ],
    requires: [
        'BNK.view.HumanResource.hwm.HwmHodAply01MViewModel',
        'BNK.view.HumanResource.hwm.HwmHodAply01MViewController',
        'Ext.field.Date',
        'Ext.picker.Date',
        'Ext.Button',
        'Ext.Spacer',
        'Ext.grid.Grid',
        'Ext.grid.column.Column',
        'Ext.grid.plugin.PagingToolbar',
        'Ext.Toolbar',
        'Ext.field.Display'
    ],

    controller: 'HwmHodAply01MViewController',
    viewModel: {
        type: 'HwmHodAply01MViewModel'
    },
    height: '100%',
    layout: 'card',

    items: [
        {
            xtype: 'container',
            height: 50,
            width: '100%',
            docked: 'top',
            padding: '0 0 0 10',
            layout: 'hbox',
            items: [
                {
                    xtype: 'datefield',
                    flex: 1,
                    reference: 'startDate',
                    itemId: 'mydate',
                    label: '',
                    dateFormat: 'Y-m-d',
                    picker: {
                        xtype: 'datepicker',
                        hideOnMaskTap: true,
                        header: false,
                        title: '',
                        dayText: '일',
                        monthText: '월',
                        slotOrder: [
                            'year',
                            'month',
                            'day'
                        ],
                        yearText: '년'
                    }
                },
                {
                    xtype: 'datefield',
                    flex: 1,
                    reference: 'endDate',
                    itemId: 'mydate2',
                    name: '',
                    margin: '0 0 0 20',
                    label: '',
                    dateFormat: 'Y-m-d',
                    picker: {
                        xtype: 'datepicker',
                        hideOnMaskTap: true,
                        header: false,
                        title: '',
                        dayText: '일',
                        monthText: '월',
                        slotOrder: [
                            'year',
                            'month',
                            'day'
                        ],
                        yearText: '년'
                    }
                },
                {
                    xtype: 'button',
                    itemId: 'btnSearch',
                    ui: 'action',
                    docked: 'right',
                    text: '조회',
                    listeners: {
                        tap: 'onBtnSearchTap'
                    }
                }
            ]
        },
        {
            xtype: 'container',
            height: 76,
            docked: 'top',
            margin: '0 5 10 5',
            layout: 'hbox',
            items: [
                {
                    xtype: 'textfield',
                    flex: 1,
                    reference: 'totOvtHodMonthDds',
                    hidden: true,
                    label: '금월 (일)',
                    readOnly: true
                },
                {
                    xtype: 'spacer',
                    flex: 0.2,
                    hidden: true,
                    width: 10
                },
                {
                    xtype: 'textfield',
                    flex: 1,
                    reference: 'totOvtHodMonthHr',
                    label: '금월 (시간)',
                    readOnly: true
                },
                {
                    xtype: 'spacer',
                    flex: 0.2,
                    hidden: true,
                    width: 10
                },
                {
                    xtype: 'textfield',
                    flex: 1,
                    reference: 'totOvtHodWeekDds',
                    hidden: true,
                    label: '금주 (일)',
                    readOnly: true
                },
                {
                    xtype: 'spacer',
                    flex: 0.2,
                    width: 10
                },
                {
                    xtype: 'textfield',
                    flex: 1,
                    reference: 'totOvtHodWeekHr',
                    label: '금주 (시간)',
                    readOnly: true
                }
            ]
        },
        {
            xtype: 'grid',
            signTpl1: '<div>{value1}</div><div>{value2}</div><div>{value3}</div>',
            reference: 'grid',
            height: '100%',
            itemId: 'mygrid2',
            width: '100%',
            modelValidation: false,
            deselectOnContainerClick: false,
            hideHeaders: true,
            bind: {
                store: '{Store}'
            },
            columns: [
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, record, dataIndex, cell, column) {
                        // 일자
                        var dtDataTemp = record.data.aplHodDt.replace(/-/g,"");
                        var dateMMdd = dtDataTemp.substr(4,2) + '월 ' +dtDataTemp.substr(6,2) + '일';
                        var dateYyMMdd =dtDataTemp.substr(0,4) + '-' + dtDataTemp.substr(4,2) + '-' +dtDataTemp.substr(6,2);

                        var aplDvcdNm = CodeUtils.getText('HWM009', record.data.aplDvcd); //코드값 -> 코드명 ;
                        aplDvcdNm = (record.data.aplDvcd == Constants.aplDvcd.CANCLE) ? "<font color= 'red'>" +aplDvcdNm+ "</font>" : aplDvcdNm;

                        var result = '<div><span style="font-size:15px;font-weight:bold;width:100%;overflow: hidden;white-space:nowrap;text-overflow:ellipsis;display:inline-block;">'+dateMMdd+' 휴일근무 '+aplDvcdNm+'</span></div>';

                        // 시간
                        var AplHodStrdt = record.data.aplHodStrdt.substr(0,4) + '-' + record.data.aplHodStrdt.substr(4,2) + '-' + record.data.aplHodStrdt.substr(6,2);
                        var AplHodEdt = record.data.aplHodEdt.substr(0,4) + '-' + record.data.aplHodEdt.substr(4,2) + '-' + record.data.aplHodEdt.substr(6,2);
                        var AplHodStrtm = record.data.aplHodStrtm.substr(0,2) + ':' + record.data.aplHodStrtm.substr(2,2);
                        var AplHodEdtm = record.data.aplHodEdtm.substr(0,2) + ':' + record.data.aplHodEdtm.substr(2,2);


                        if(AplHodStrdt != AplHodEdt){
                            result += '<div style="font-size : 10px">'+AplHodStrdt+' '+AplHodStrtm+' ~ '+AplHodEdt + ' '+AplHodEdtm+'</div>';
                        }else{
                            result += '<div>'+AplHodStrdt+' | '+AplHodStrtm+'~'+AplHodEdtm+'</div>';
                        }

                        cell.setStyle('padding:0px;');
                        return result;
                    },
                    flex: '1.7',
                    height: '',
                    hidden: false,
                    width: '70%',
                    docked: 'left',
                    cell: {
                        xtype: 'gridcell',
                        encodeHtml: false
                    },
                    dataIndex: 'id',
                    defaultWidth: 0
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, record, dataIndex, cell, column) {
                        var result ="";
                        var dtDataTemp = record.data.aplDtm.replace(/-/g,"");
                        var dateYyMMdd = dtDataTemp.substr(0,4) + '-' + dtDataTemp.substr(4,2) + '-' + dtDataTemp.substr(6,2);

                        var str = String(result);
                        result = str.replace(/(\d)(?=(?:\d{3})+(?!\d))/g, '$1,');
                        result = '<div style="font-size:15px;font-weight:bold">'+dateYyMMdd+'</div>';

                        var aplStcdNm = CodeUtils.getText('INB031', record.data.aplStcd); //코드값 -> 코드명
                        result += '<div>'+aplStcdNm+'</div>';

                        return result;
                    },
                    flex: '1.3',
                    width: '30%',
                    docked: 'right',
                    align: 'right',
                    cell: {
                        xtype: 'gridcell',
                        encodeHtml: false
                    },
                    dataIndex: 'id'
                }
            ],
            plugins: [
                {
                    type: 'gridpagingtoolbar'
                }
            ],
            items: [
                {
                    xtype: 'toolbar',
                    docked: 'bottom',
                    scrollable: true,
                    layout: {
                        type: 'hbox',
                        pack: 'center'
                    },
                    items: [
                        {
                            xtype: 'displayfield',
                            reference: 'lblTotalCnt',
                            docked: 'left',
                            margin: '5 0 10 10',
                            encodeHtml: false
                        },
                        {
                            xtype: 'button',
                            height: '',
                            itemId: 'btnBatch',
                            ui: 'action',
                            width: '90%',
                            margin: '5 5 10 5',
                            text: '휴일근무 신청',
                            listeners: {
                                tap: 'onApfData'
                            }
                        }
                    ]
                }
            ],
            listeners: {
                select: 'onMygridSelect'
            }
        }
    ],
    listeners: {
        initialize: 'onContainerInitialize',
        destroy: 'onContainerDestroy'
    }

});