/*
 * File: app/view/HumanResource/hwm/HwmHodRept71M.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

/*
    휴일근무보고 결재함 - 화면

    @author BNK시스템/파트너/지민영
    @since 2020.10.13
    @version 1.0
    @see

    << 개정이력(Modification Information) >>

    수정일		  수정자                  수정내용
    ----------	--------------------   --------------------------
    2020.10.13	BNK시스템/파트너/지민영   최초 생성
*/
Ext.define('BNK.view.HumanResource.hwm.HwmHodRept71M', {
    extend: 'Ext.window.Window',
    alias: 'widget.HwmHodRept71M',

    alternateClassName: [
        'HwmHodRept71M'
    ],
    requires: [
        'BNK.view.HumanResource.hwm.HwmHodRept71MViewModel',
        'BNK.view.HumanResource.hwm.HwmHodRept71MViewController',
        'BNK.view.common.ApprovalLineGrid',
        'BNK.view.common.EdocButtonContainer',
        'Ext.Label',
        'Ext.form.Panel',
        'Ext.field.ComboBox',
        'Ext.field.Date',
        'Ext.picker.Date',
        'Ext.Spacer',
        'Ext.field.Time',
        'Ext.field.TextArea',
        'Ext.grid.Grid'
    ],

    controller: 'HwmHodRept71MViewController',
    viewModel: {
        type: 'HwmHodRept71MViewModel'
    },
    height: '98%',
    width: '98%',
    scrollable: 'both',
    layout: 'vbox',

    items: [
        {
            xtype: 'container',
            height: '100%',
            scrollable: 'vertical',
            layout: 'vbox',
            items: [
                {
                    xtype: 'container',
                    flex: 2,
                    docked: 'top',
                    margin: 15,
                    layout: 'vbox',
                    items: [
                        {
                            xtype: 'container',
                            margin: '0 0 7 0',
                            layout: 'hbox',
                            items: [
                                {
                                    xtype: 'label',
                                    style: 'fontSize: 20px;',
                                    docked: 'left',
                                    html: '구분'
                                },
                                {
                                    xtype: 'label',
                                    reference: 'headTitle',
                                    style: 'color:red; fontSize: 20px;',
                                    docked: 'right',
                                    html: '휴일근무보고신청'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            layout: 'hbox',
                            items: [
                                {
                                    xtype: 'label',
                                    style: 'fontSize: 20px;',
                                    docked: 'left',
                                    html: '상신일'
                                },
                                {
                                    xtype: 'label',
                                    reference: 'rgdt',
                                    style: 'fontSize: 20px;',
                                    docked: 'right'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'formpanel',
                    reference: 'frmDetail',
                    width: '100%',
                    padding: 0,
                    items: [
                        {
                            xtype: 'formpanel',
                            reference: 'hodAplyForm',
                            width: '100%',
                            padding: 0,
                            items: [
                                {
                                    xtype: 'textfield',
                                    reference: 'empeNo',
                                    hidden: true,
                                    name: 'empeNo',
                                    label: '사번',
                                    readOnly: true,
                                    editable: false,
                                    bind: {
                                        value: '{detail.empeNo}'
                                    }
                                },
                                {
                                    xtype: 'textfield',
                                    reference: 'empeNm',
                                    hidden: true,
                                    name: 'empeNm',
                                    label: '성명',
                                    readOnly: true,
                                    editable: false,
                                    bind: {
                                        value: '{detail.empeNm}'
                                    }
                                },
                                {
                                    xtype: 'textfield',
                                    reference: 'empePsitNm',
                                    hidden: true,
                                    name: 'empePsitNm',
                                    label: '직위',
                                    readOnly: true,
                                    editable: false,
                                    bind: {
                                        value: '{detail.empePsitNm}'
                                    }
                                },
                                {
                                    xtype: 'textfield',
                                    reference: 'rqpr',
                                    name: 'rqpr',
                                    width: '97%',
                                    margin: '0 5 0 5',
                                    label: '신청자',
                                    readOnly: true,
                                    editable: false,
                                    bind: {
                                        value: '{detail.empeNo} / {detail.dpnm} / {detail.empeNm} / {detail.empePsitNm}'
                                    }
                                },
                                {
                                    xtype: 'textfield',
                                    reference: 'dpnm',
                                    hidden: true,
                                    name: 'dpnm',
                                    label: '소속명',
                                    readOnly: true,
                                    editable: false,
                                    bind: {
                                        value: '{detail.dpnm}'
                                    }
                                },
                                {
                                    xtype: 'textfield',
                                    reference: 'hrWrkmHodApfName',
                                    hidden: true,
                                    name: 'hrWrkmHodApfName',
                                    label: '신청서',
                                    readOnly: true,
                                    editable: false,
                                    bind: {
                                        value: '{hodApfInfo.hrWrkmHodApfName}'
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'formpanel',
                            reference: 'beforeHodInfoForm',
                            width: '100%',
                            padding: 0,
                            items: [
                                {
                                    xtype: 'container',
                                    hidden: true,
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            disabled: true,
                                            name: 'id',
                                            label: 'id',
                                            required: true,
                                            readOnly: true,
                                            editable: false,
                                            bind: {
                                                value: '{detail.id}'
                                            }
                                        },
                                        {
                                            xtype: 'textfield',
                                            disabled: true,
                                            name: 'crud',
                                            label: 'crud',
                                            readOnly: true,
                                            editable: false,
                                            bind: {
                                                value: '{detail.crud}'
                                            }
                                        },
                                        {
                                            xtype: 'combobox',
                                            code: 'INB014',
                                            reference: 'cbxStcd',
                                            disabled: true,
                                            name: 'stcd',
                                            label: '상태코드',
                                            required: true,
                                            readOnly: true,
                                            editable: false,
                                            bind: {
                                                value: '{detail.stcd}'
                                            }
                                        },
                                        {
                                            xtype: 'textfield',
                                            disabled: true,
                                            name: 'hrHrpmCompId',
                                            label: '회사',
                                            required: true,
                                            readOnly: true,
                                            editable: false,
                                            bind: {
                                                value: '{detail.hrHrpmCompId}'
                                            }
                                        },
                                        {
                                            xtype: 'textfield',
                                            disabled: true,
                                            name: 'hrHrpmEmpId',
                                            label: '사번',
                                            required: true,
                                            readOnly: true,
                                            editable: false,
                                            bind: {
                                                value: '{detail.hrHrpmEmpId}'
                                            }
                                        },
                                        {
                                            xtype: 'combobox',
                                            code: 'INB025',
                                            reference: 'aplStcd',
                                            hidden: true,
                                            name: 'aplStcd',
                                            label: '결재상태',
                                            required: true,
                                            readOnly: true,
                                            editable: false,
                                            bind: {
                                                value: '{detail.aplStcd}'
                                            }
                                        },
                                        {
                                            xtype: 'textfield',
                                            reference: 'hrWrkmHodApfId',
                                            disabled: true,
                                            name: 'hrWrkmHodApfId',
                                            label: '신청서ID',
                                            readOnly: true,
                                            editable: false,
                                            bind: {
                                                value: '{hodApfInfo.hrWrkmHodApfId}'
                                            }
                                        },
                                        {
                                            xtype: 'textfield',
                                            reference: 'hrWrkmHodCreptId',
                                            disabled: true,
                                            name: 'hrWrkmHodCreptId',
                                            scrollable: false,
                                            label: '보고서취소ID',
                                            readOnly: true,
                                            editable: false
                                        },
                                        {
                                            xtype: 'textfield',
                                            reference: 'comAprHistApfId',
                                            disabled: true,
                                            name: 'comAprHistApfId',
                                            label: '신청서결재ID',
                                            readOnly: true,
                                            editable: false,
                                            bind: {
                                                value: '{hodApfInfo.comAprHistApfId}'
                                            }
                                        }
                                    ]
                                },
                                {
                                    xtype: 'datefield',
                                    submitFormat: 'Ymd',
                                    reference: 'aplHodDt',
                                    disabled: true,
                                    name: 'aplHodDt',
                                    width: '97%',
                                    margin: '0 5 0 5',
                                    label: '일자',
                                    required: true,
                                    readOnly: true,
                                    editable: false,
                                    dateFormat: 'Y-m-d',
                                    picker: {
                                        xtype: 'datepicker',
                                        hideOnMaskTap: true,
                                        header: false,
                                        title: '',
                                        dayText: '일',
                                        monthText: '월',
                                        slotOrder: [
                                            'year',
                                            'month',
                                            'day'
                                        ],
                                        yearText: '년'
                                    }
                                },
                                {
                                    xtype: 'combobox',
                                    code: 'HWM009',
                                    reference: 'aplDvcd',
                                    disabled: true,
                                    hidden: true,
                                    name: 'aplDvcd',
                                    margin: '0 5 0 5',
                                    label: '신청구분',
                                    required: true,
                                    readOnly: true,
                                    editable: false,
                                    bind: {
                                        value: '{detail.aplDvcd}'
                                    }
                                },
                                {
                                    xtype: 'textfield',
                                    reference: 'aplDvcdNm',
                                    disabled: true,
                                    name: 'aplDvcdNm',
                                    margin: '0 5 0 5',
                                    label: '신청구분',
                                    required: true,
                                    readOnly: true,
                                    editable: false,
                                    bind: {
                                        value: '{detail.aplDvcdNm}'
                                    }
                                },
                                {
                                    xtype: 'container',
                                    height: 82,
                                    width: '97%',
                                    margin: '0 5 0 5',
                                    scrollable: false,
                                    layout: {
                                        type: 'vbox',
                                        align: 'start',
                                        pack: 'center'
                                    },
                                    items: [
                                        {
                                            xtype: 'spacer',
                                            height: 15
                                        },
                                        {
                                            xtype: 'container',
                                            height: '',
                                            width: '98%',
                                            layout: 'hbox',
                                            items: [
                                                {
                                                    xtype: 'label',
                                                    style: 'font-size: 12px; color: rgba(17, 17, 17, 0.38)',
                                                    html: '시작 일시'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'spacer',
                                            height: 8
                                        },
                                        {
                                            xtype: 'container',
                                            hidden: false,
                                            width: '97%',
                                            margin: '0 5 0 5',
                                            layout: 'hbox',
                                            items: [
                                                {
                                                    xtype: 'datefield',
                                                    submitFormat: 'Ymd',
                                                    reference: 'hodStrdt',
                                                    disabled: true,
                                                    height: '100%',
                                                    itemId: 'mydate',
                                                    name: 'hodStrdt',
                                                    width: '50%',
                                                    required: true,
                                                    readOnly: true,
                                                    editable: false,
                                                    dateFormat: 'Y-m-d',
                                                    picker: {
                                                        xtype: 'datepicker',
                                                        disabled: true,
                                                        hideOnMaskTap: true,
                                                        header: false,
                                                        title: '',
                                                        dayText: '일',
                                                        monthText: '월',
                                                        slotOrder: [
                                                            'year',
                                                            'month',
                                                            'day'
                                                        ],
                                                        yearText: '년'
                                                    }
                                                },
                                                {
                                                    xtype: 'spacer',
                                                    minWidth: '3%'
                                                },
                                                {
                                                    xtype: 'timefield',
                                                    submitFormat: 'His',
                                                    reference: 'hodStrtm',
                                                    disabled: true,
                                                    height: '100%',
                                                    name: 'hodStrtm',
                                                    width: '45%',
                                                    required: true,
                                                    readOnly: true,
                                                    editable: false,
                                                    format: 'H:i'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    height: 82,
                                    width: '97%',
                                    margin: '0 5 0 5',
                                    scrollable: false,
                                    layout: {
                                        type: 'vbox',
                                        pack: 'end'
                                    },
                                    items: [
                                        {
                                            xtype: 'spacer',
                                            height: 10
                                        },
                                        {
                                            xtype: 'container',
                                            width: '98%',
                                            layout: 'hbox',
                                            items: [
                                                {
                                                    xtype: 'label',
                                                    height: '100%',
                                                    style: 'font-size: 12px; color: rgba(17, 17, 17, 0.38)',
                                                    width: '20%',
                                                    html: '종료 일시'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'spacer',
                                            height: 8
                                        },
                                        {
                                            xtype: 'container',
                                            width: '97%',
                                            margin: '0 5 0 5',
                                            layout: 'hbox',
                                            items: [
                                                {
                                                    xtype: 'datefield',
                                                    submitFormat: 'Ymd',
                                                    reference: 'hodEdt',
                                                    disabled: true,
                                                    height: '100%',
                                                    name: 'hodEdt',
                                                    width: '50%',
                                                    required: true,
                                                    readOnly: true,
                                                    editable: false,
                                                    dateFormat: 'Y-m-d',
                                                    picker: {
                                                        xtype: 'datepicker',
                                                        disabled: true,
                                                        hideOnMaskTap: true,
                                                        header: false,
                                                        title: '',
                                                        dayText: '일',
                                                        monthText: '월',
                                                        slotOrder: [
                                                            'year',
                                                            'month',
                                                            'day'
                                                        ],
                                                        yearText: '년'
                                                    }
                                                },
                                                {
                                                    xtype: 'spacer',
                                                    minWidth: '3%'
                                                },
                                                {
                                                    xtype: 'timefield',
                                                    submitFormat: 'His',
                                                    reference: 'hodEdtm',
                                                    disabled: true,
                                                    height: '100%',
                                                    name: 'hodEdtm',
                                                    width: '45%',
                                                    required: true,
                                                    readOnly: true,
                                                    editable: false,
                                                    format: 'H:i'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    reference: 'ovtHodInfo',
                                    height: 76,
                                    width: '97%',
                                    margin: '0 5 0 5',
                                    scrollable: false,
                                    layout: {
                                        type: 'hbox',
                                        align: 'start',
                                        pack: 'center'
                                    },
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            flex: 1,
                                            reference: 'totOvtHodMonthDds',
                                            hidden: true,
                                            label: '금월 (일)',
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'spacer',
                                            hidden: true,
                                            width: 10
                                        },
                                        {
                                            xtype: 'textfield',
                                            flex: 1,
                                            reference: 'totOvtHodMonthHr',
                                            name: 'totOvtHodMonthHr',
                                            label: '금월시간외근무 (시간)',
                                            readOnly: true,
                                            editable: false,
                                            bind: {
                                                value: '{hodApfInfo.totOvtHodMonthHr}'
                                            }
                                        },
                                        {
                                            xtype: 'spacer',
                                            width: 10
                                        },
                                        {
                                            xtype: 'textfield',
                                            flex: 1,
                                            reference: 'totOvtHodWeekDds',
                                            hidden: true,
                                            label: '금주 (일)',
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'spacer',
                                            hidden: true,
                                            width: 10
                                        },
                                        {
                                            xtype: 'textfield',
                                            flex: 1,
                                            reference: 'totOvtHodWeekHr',
                                            name: 'totOvtHodWeekHr',
                                            label: '금주시간외근무 (시간)',
                                            readOnly: true,
                                            editable: false,
                                            bind: {
                                                value: '{hodApfInfo.totOvtHodWeekHr}'
                                            }
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    height: 150,
                                    width: '97%',
                                    margin: '0 5 0 5',
                                    scrollable: false,
                                    items: [
                                        {
                                            xtype: 'textareafield',
                                            reference: 'aplCntn',
                                            name: 'aplCntn',
                                            width: '97%',
                                            margin: '0 5 0 5',
                                            label: '사유',
                                            required: true,
                                            readOnly: true,
                                            editable: false,
                                            maxLength: 200,
                                            bind: {
                                                value: '{hodApfInfo.aplCntn}'
                                            }
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'formpanel',
                            reference: 'afterHodInfoForm',
                            width: '100%',
                            padding: 0,
                            items: [
                                {
                                    xtype: 'container',
                                    reference: 'wrkStrdtBox',
                                    height: 82,
                                    width: '97%',
                                    margin: '0 5 0 5',
                                    scrollable: false,
                                    layout: {
                                        type: 'vbox',
                                        align: 'start',
                                        pack: 'center'
                                    },
                                    items: [
                                        {
                                            xtype: 'spacer',
                                            height: 15
                                        },
                                        {
                                            xtype: 'container',
                                            height: '',
                                            width: '98%',
                                            layout: 'hbox',
                                            items: [
                                                {
                                                    xtype: 'label',
                                                    style: 'font-size: 12px; color: rgba(17, 17, 17, 0.38)',
                                                    html: '출근 일시'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'spacer',
                                            height: 8
                                        },
                                        {
                                            xtype: 'container',
                                            width: '97%',
                                            margin: '0 5 0 5',
                                            layout: 'hbox',
                                            items: [
                                                {
                                                    xtype: 'datefield',
                                                    submitFormat: 'Ymd',
                                                    reference: 'wrkStrdt',
                                                    disabled: true,
                                                    height: '100%',
                                                    name: 'wrkStrdt',
                                                    width: '50%',
                                                    required: true,
                                                    readOnly: true,
                                                    editable: false,
                                                    dateFormat: 'Y-m-d',
                                                    picker: {
                                                        xtype: 'datepicker',
                                                        disabled: true,
                                                        hideOnMaskTap: true,
                                                        header: false,
                                                        title: '',
                                                        dayText: '일',
                                                        monthText: '월',
                                                        slotOrder: [
                                                            'year',
                                                            'month',
                                                            'day'
                                                        ],
                                                        yearText: '년'
                                                    },
                                                    listeners: {
                                                        change: 'onChangeWrkStrdt'
                                                    }
                                                },
                                                {
                                                    xtype: 'spacer',
                                                    minWidth: '3%'
                                                },
                                                {
                                                    xtype: 'timefield',
                                                    submitFormat: 'His',
                                                    reference: 'wrkStrtm',
                                                    disabled: true,
                                                    height: '100%',
                                                    name: 'wrkStrtm',
                                                    width: '45%',
                                                    required: true,
                                                    readOnly: true,
                                                    editable: false,
                                                    format: 'H:i:s',
                                                    bind: {
                                                        value: '{wrkInfo.wrkStrtm}'
                                                    }
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    reference: 'wrkEdtBox',
                                    height: 76,
                                    width: '97%',
                                    margin: '0 5 0 5',
                                    scrollable: false,
                                    layout: {
                                        type: 'vbox',
                                        pack: 'end'
                                    },
                                    items: [
                                        {
                                            xtype: 'spacer',
                                            height: 10
                                        },
                                        {
                                            xtype: 'container',
                                            width: '98%',
                                            layout: 'hbox',
                                            items: [
                                                {
                                                    xtype: 'label',
                                                    height: '100%',
                                                    style: 'font-size: 12px; color: rgba(17, 17, 17, 0.38)',
                                                    width: '20%',
                                                    html: '퇴근 일시'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'spacer',
                                            height: 8
                                        },
                                        {
                                            xtype: 'container',
                                            width: '97%',
                                            margin: '0 5 0 5',
                                            layout: 'hbox',
                                            items: [
                                                {
                                                    xtype: 'datefield',
                                                    submitFormat: 'Ymd',
                                                    reference: 'wrkEdt',
                                                    disabled: true,
                                                    height: '100%',
                                                    name: 'wrkEdt',
                                                    width: '50%',
                                                    labelAlign: 'right',
                                                    required: true,
                                                    readOnly: true,
                                                    editable: false,
                                                    dateFormat: 'Y-m-d',
                                                    bind: {
                                                        value: '{wrkInfo.wrkEdt}'
                                                    },
                                                    picker: {
                                                        xtype: 'datepicker',
                                                        disabled: true,
                                                        hideOnMaskTap: true,
                                                        header: false,
                                                        title: '',
                                                        dayText: '일',
                                                        monthText: '월',
                                                        slotOrder: [
                                                            'year',
                                                            'month',
                                                            'day'
                                                        ],
                                                        yearText: '년'
                                                    }
                                                },
                                                {
                                                    xtype: 'spacer',
                                                    minWidth: '3%'
                                                },
                                                {
                                                    xtype: 'timefield',
                                                    submitFormat: 'His',
                                                    reference: 'wrkEdtm',
                                                    disabled: true,
                                                    height: '100%',
                                                    name: 'wrkEdtm',
                                                    width: '45%',
                                                    required: true,
                                                    readOnly: true,
                                                    editable: false,
                                                    format: 'H:i:s',
                                                    bind: {
                                                        value: '{wrkInfo.wrkEdtm}'
                                                    }
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    reference: 'reptCntnBox',
                                    height: 150,
                                    width: '97%',
                                    margin: '0 5 0 5',
                                    scrollable: false,
                                    items: [
                                        {
                                            xtype: 'textareafield',
                                            reference: 'reptCntn',
                                            name: 'reptCntn',
                                            width: '97%',
                                            margin: '0 5 0 5',
                                            label: '보고내용',
                                            required: true,
                                            value: '프로젝트명 : \r\n업무내용 :',
                                            maxLength: 200
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    disabled: true,
                    scrollable: 'both',
                    layout: 'vbox',
                    items: [
                        {
                            xtype: 'common.approvallinegrid',
                            height: 450
                        },
                        {
                            xtype: 'textfield',
                            hidden: true,
                            name: 'version',
                            label: 'version',
                            bind: {
                                value: '{formValues.version}'
                            }
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'common.edocbuttoncontainer',
            docked: 'bottom'
        }
    ],
    listeners: {
        initialize: 'onContainerInitialize'
    }

});