/*
 * File: app/view/HumanResource/hwm/HwmHodRept01MViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

/*
    모바일 :: 휴일근무신청(조회) - 컨트롤러

    @author BNK시스템/파트너/지민영
    @since 2020.09.24
    @version 1.0
    @see

    << 개정이력(Modification Information) >>

    수정일		  수정자                    수정내용
    ----------	--------------------     --------------------------
    2020.09.24	BNK시스템/파트너/지민영     최초 생성
*/
Ext.define('BNK.view.HumanResource.hwm.HwmHodRept01MViewController', {
    extend: 'BaseViewController',
    alias: 'controller.humanresource.hwm.hwmhodrept01m',

    config: {
        viewId: 'HwmHodRept01M'
    },

    onSelect: function() {
        var me = this,
            vm = me.getViewModel(),
            refs = me.getReferences(),
            grid = refs.grid,
            store = vm.storeInfo.Store;

        // VALIDATION AERA
        var dateCompont = ['startDate',
                           'endDate'
                          ];

        if(refs[dateCompont[0]].getValue() > refs[dateCompont[1]].getValue()){
            Ext.Msg.alert('확인','시작일이 종료일보다 클 수 없습니다.');
            return;
        }


        //PARAM SET
        var params = {
            //공통
            hrHrpmCompId : SecurityUtils.getPrincipal().hrHrpmCompId, //회사
            hrHrpmEmpId : SecurityUtils.getPrincipal().hrHrpmEmpId,
            stcd : Constants.stcd.NORMAL,
            apfAplDvcd : Constants.wrkAplDvcd.APPLY, //신청서의 신청구분 (신청만)
            apfAplStcd : Constants.aplStcd.COMPLETED_APPLY, //신청서의 신청상태 (완료만)

            //검색조건
            aplStcd : refs.aplStcd.getValue(),
            startDate : Ext.Date.format(refs[dateCompont[0]].getValue(), 'Ymd'),
            endDate : Ext.Date.format(refs[dateCompont[1]].getValue(), 'Ymd'),
        };

        store.getProxy().extraParams = params;
        store.removeAll();
        store.loadPage(1);


        // 메뉴 추가
        me.menu = Ext.create({
            xtype: 'actionsheet',
            scope : me.getView(),
            displayed: false,
            cover: true,
            side: 'bottom',
            listeners: {
                show : me.onActionSheetShow
            },
            items: [
                {
                    xtype: 'button',
                    disabled: true,
                    itemId: 'btnReApply',
                    ui: 'action',
                    margin: 5,
                    text: '재기안',
                    scope : me,
                    handler : 'onApfData'
                },
                {
                    xtype: 'button',
                    disabled: true,
                    itemId: 'btnCancel',
                    ui: 'action',
                    margin: 5,
                    text: '신청취소',
                    scope : me,
                    handler : 'onApfData'
                },
                {
                    xtype: 'button',
                    disabled: true,
                    itemId: 'btnReptWrite',
                    ui: 'action',
                    margin: '5 5 10 5',
                    text: '보고',
                    scope : me,
                    handler : 'onReptData'
                },
                {
                    xtype: 'button',
                    disabled: true,
                    itemId: 'btnReptCancel',
                    ui: 'action',
                    margin: '5 5 10 5',
                    text: '보고취소',
                    scope : me,
                    handler : 'onReptData'
                },
                {
                    xtype: 'button',
                    disabled: true,
                    itemId: 'actAprHistApfData',
                    ui: 'action',
                    margin: '5 5 10 5',
                    text: '신청서 보기',
                    scope : me,
                    handler : 'onClickActColumn'
                },
                {
                    xtype: 'button',
                    disabled: true,
                    itemId: 'actAprHistReptData',
                    ui: 'action',
                    margin: '5 5 10 5',
                    text: '보고서 보기',
                    scope : me,
                    handler : 'onClickActColumn'
                }
            ]
        });
    },

    defaut: function() {
        var me = this,
            vm = me.getViewModel(),
            refs = me.getReferences(),
            store = vm.storeInfo.Store;

        // 페이지 초기화
        store.getProxy().extraParams.page = 1;
        var toolbar = refs.grid.getPlugins()[0];
        toolbar.setCurrentPage(1);
    },

    /* 메뉴 */
    onActionSheetShow: function(component, eOpts) {

        var me = component.config.scope,
            vm = me.getViewModel(),
            refs = me.getReferences();

        // 열린화면이 휴일근무인지 유효성체크
        var home = Ext.ComponentQuery.query(Property.ROUTE_HOME);
        if (home.length <= 0 || document.getElementsByClassName("x-navigationview-body-el")[0].lastChild.id.indexOf('HwmHodRept01M') == -1) {		// 로그인화면이거나 휴일근무신청화면이 아닌경우
            console.log('휴일근무화면아님');
            Ext.Viewport.removeMenu('bottom', false);
        } else {
            // 신청서가 선택되었는지 체크
            if (refs.grid && refs.grid.getSelection()) {
                // 하나만 선택되었는지 체크
                if (refs.grid.getSelectionCount() > 1) {
                    Ext.Msg.alert('알림', '하나만 선택할 수 있습니다.');
                    component.hide();
                }

                var record = refs.grid.getSelection().data,
                    items = component.getItems(),
                    btnReApply = items.get('btnReApply'),		// 재기안
                    btnCancel = items.get('btnCancel'),			// 신청취소
                    btnReptWrite = items.get('btnReptWrite'),	// 보고
                    btnReptCancel = items.get('btnReptCancel'),	// 보고취소
                    actAprHistApfData = items.get('actAprHistApfData'),		// 신청서보기
                    actAprHistReptData = items.get('actAprHistReptData');	// 보고서보기

                //재기안
                if (record.apfAplDvcd == Constants.wrkAplDvcd.CANCEL) {
                    btnReApply.setDisabled(true);
                } else {
                    btnReApply.setDisabled(false);
                }
                //신청취소
                if (record.apfAplDvcd == Constants.wrkAplDvcd.CANCEL) {
                    btnCancel.setDisabled(true);
                } else if (record.hrWrkmHodReptId && record.reptAplDvcd != Constants.wrkAplDvcd.CANCEL) {
                    btnCancel.setDisabled(true);
                } else if (record.apfAplStcd != Constants.aplStcd.COMPLETED_APPLY) {
                    btnCancel.setDisabled(true);
                } else {
                    btnCancel.setDisabled(false);
                }
                //보고취소
                if (!record.hrWrkmHodReptId) {
                    btnReptCancel.setDisabled(true);
                } else if (record.reptAplDvcd == Constants.wrkAplDvcd.CANCEL) {
                    btnReptCancel.setDisabled(true);
                } else if (record.hrHrpmEmpId != SecurityUtils.getPrincipal().hrHrpmEmpId) {
                    btnReptCancel.setDisabled(true);
                } else if (record.reptAplStcd != Constants.aplStcd.COMPLETED_APPLY) {
                    btnReptCancel.setDisabled(true);
                } else {
                    btnReptCancel.setDisabled(false);
                }
                //보고
                if (record.apfAplDvcd == Constants.wrkAplDvcd.CANCEL) {
                    btnReptWrite.setDisabled(true);
                } else if (record.apfAplStcd != Constants.aplStcd.COMPLETED_APPLY) {
                    btnReptWrite.setDisabled(true);
                } else if (record.hrWrkmHodReptId) {
                    if (record.reptAplDvcd == Constants.wrkAplDvcd.APPLY) {
                        if ((record.reptAplStcd == Constants.aplStcd.COMPLETED_APPLY || record.reptAplStcd == Constants.aplStcd.PROGRESS_APPLY)) {
                            btnReptWrite.setDisabled(true);
                        } else {
                            btnReptWrite.setDisabled(false);
                        }
                    } else {
                        btnReptWrite.setDisabled(false);
                    }
                } else {
                    btnReptWrite.setDisabled(false);
                }
                // 신청서 보기
                if (record.comAprHistApfId && record.comAprHistApfId != -1) {
                    actAprHistApfData.setDisabled(false);
                }
                // 보고서 보기
                if (record.comAprHistReptId && record.comAprHistReptId != -1) {
                    actAprHistReptData.setDisabled(false);
                }
            } else {
                // 행이 선택되지 않았을경우 예외처리
                var items = component.getItems(),
                    btnReApply = items.get('btnReApply'),		// 재기안
                    btnCancel = items.get('btnCancel'),			// 신청취소
                    btnReptWrite = items.get('btnReptWrite'),	// 보고
                    btnReptCancel = items.get('btnReptCancel'),	// 보고취소
                    actAprHistApfData = items.get('actAprHistApfData'),		// 신청서보기
                    actAprHistReptData = items.get('actAprHistReptData');	// 보고서보기

                btnReApply.setDisabled(true);
                btnCancel.setDisabled(true);
                btnReptWrite.setDisabled(true);
                btnReptCancel.setDisabled(true);
                actAprHistApfData.setDisabled(true);
                actAprHistReptData.setDisabled(true);
            }

        }

    },

    /* 신청서 / 보고서 보기 */
    onClickActColumn: function(component) {
        var me = this,
            vm = me.getViewModel(),
            refs = me.getReferences(),
            itemId = component.config.itemId; // 신청서 or 보고서

        var colName, className;
        var record = component.config.scope.view.refs.grid.getSelection().data;
        if (itemId == 'actAprHistApfData') {
            colName = 'comAprHistApfId';
            className = 'HwmHodAply71M';
        } else if (itemId == 'actAprHistReptData') {
            colName = 'comAprHistReptId';
            className = 'HwmHodRept71M';
        } else {
            return false;
        }

        if (!record[colName] || record[colName] == -1) {
            Ext.Msg.alert('확인', Messages.getMessage('E9303', [ '신청/보고서' ]));
            return;
        }

        Ext.Ajax.request({
            headers : {
                serviceId : 'COMAPR0001R04',
                viewId : me.getViewId(),
                scope : me
            },
            jsonData : {
                aprHistId : record[colName]        // 결재이력ID
            },
            success : function(response) {
                var res = Ext.JSON.decode(response.responseText),
                    command = Constants.sanction.COMPLETED_BOX; // 아무 동작도 하지 않아야 하므로 완료.

                me.menu.hide();		//메뉴닫기

                var win = Ext.create(className, {
                    command : command,
                    aprHistId : res.aprHistId,
                    aprHistData : Ext.decode(res.result),
                    record : record
                });
                // 재조회
                me.mon(win, 'close', function(view) {
                    me.onSelect(); // 재조회
                }, me);
                win.show();

            }
        });
    },

    /* 보고 / 보고취소 */
    onReptData: function(button) {
        var me = this,
            vm = me.getViewModel(),
            refs = me.getReferences(),
            grid = refs.grid,
            itemId = button.config.itemId,
            selectedData = grid.getSelection().data,
            naviView = me.getView().up('navigationview');

        /* 유효성 체크 */
        switch (itemId) {
            case 'btnReptCancel':
                /** 보고취소 저장 함수 호출 */
                me.onReptCancelSave();
                break;
            case 'btnReptWrite':
                if (selectedData.apfAplDvcd == Constants.wrkAplDvcd.CANCEL) {
                    Ext.Msg.alert("안내", "정상 신청서만 보고가 가능합니다.");
                    return false;
                }
                if (selectedData.apfAplStcd != Constants.aplStcd.COMPLETED_APPLY) {
                    Ext.Msg.alert("안내", "신청상태가 \'완료(신청)\'인 신청서만 보고서 작성이 가능합니다.");
                    return false;
                }
                if (selectedData.hrWrkmHodReptId) {
                    if (selectedData.reptAplDvcd == Constants.wrkAplDvcd.APPLY) {
                        if ((selectedData.reptAplStcd == Constants.aplStcd.COMPLETED_APPLY || selectedData.reptAplStcd == Constants.aplStcd.PROGRESS_APPLY)) {
                            Ext.Msg.alert("안내", "이미 해당 신청서에 대해서 진행/완료된 보고서가 있습니다.");
                            return false;
                        }
                    }
                }
                /* 화면이동 */
                me.PUSH_VIEW(naviView, {
                    menuId  : 'HwmHodRept02M',
                    title   : '휴일근무보고신청',
                    records : selectedData,
                    isSubView : true,
                    parentView : me.getView()
                });
                break;
        }

        me.menu.hide();		// 메뉴 닫기
    },

    /* 신청취소 저장함수 */
    onApfCancelSave: function() {
        var me = this,
            vm = me.getViewModel(),
            refs = me.getReferences(),
            grid = refs.grid,
            selectedData = grid.getSelection().data;

        //VALIDATION AREA
        if (selectedData.apfAplDvcd == Constants.wrkAplDvcd.CANCEL) {
            Ext.Msg.alert("안내", "정상 신청서만 신청취소이 가능합니다.");
            return false;
        }
        if (selectedData.hrWrkmHodReptId && selectedData.reptAplDvcd != Constants.wrkAplDvcd.CANCEL) {
            Ext.Msg.alert("안내", "해당건에 대해서 휴일근무 보고서가 '진행/완료' 된 신청서가 있습니다. <br> 휴일근무 보고서 회수/취소 후 다시 신청바랍니다.");
            return false;
        }
        if (selectedData.apfAplStcd != Constants.aplStcd.COMPLETED_APPLY) {
            Ext.Msg.alert("안내", "신청상태가 \'완료(신청)\'인 신청서만 신청취소이 가능합니다.<br><br>신청상태가 \'진행(신청)\'인 경우에는 결재함에서 회수 하시기 바랍니다.");
            return false;
        }
        //END VALIDATION AREA

        selectedData.stcd = Constants.stcd.OUTSTANDING; //상태 - 결재로 변경
        selectedData.aplStcd = Constants.aplStcd.COMPLETED_APPLY; //신청상태 - 완료
        selectedData.aplDvcd = Constants.wrkAplDvcd.CANCEL; //신청구분 - 취소

        Ext.Ajax.request({
            headers : {
                serviceId : 'HwmHodSvc.findAllHwmHodAply',
                viewId : me.getViewId(),
                scope : me
            },
            jsonData : selectedData,
            success : function(res) {
                if (res.errMsg) {
                    Ext.Msg.alert("안내", res.errMsg);
                    return;
                }

                Ext.Msg.confirm('알림', '<b>※유의사항<br> 신청취소시 결재 없이 바로 취소 됩니다.</b> <br><br> 정말로 취소하시겠습니까? <br>', function(btn) {
                    if (btn == 'yes') {
                        var result = {
                            newRecords : [],
                            modifiedRecords : [],
                            removedRecords : []
                        };
                        result.newRecords.push(selectedData);

                        //SERVICE 호출
                        Ext.Ajax.request({
                            headers : {
                                serviceId : 'HwmHodSvc.saveHwmHodAply',
                                viewId : me.getViewId()
                            },
                            jsonData : result,
                            success : function(res) {
                                Ext.Msg.alert('알림', Messages.getMessage('I0000'));
                                me.onBtnSearchTap();
                            }
                        });
                    } else {
                        return false;
                    }
                });
            }
        });

    },

    /* 보고취소 저장함수 */
    onReptCancelSave: function() {
        var me = this,
            vm = me.getViewModel(),
            refs = me.getReferences(),
            grid = refs.grid,
            selectedData = grid.getSelection().data;

        //VALIDATION AREA
        if (!selectedData.hrWrkmHodReptId) {
            Ext.Msg.alert("안내", "취소할 보고서가 없습니다.");
            return false;
        }
        if (selectedData.reptAplDvcd == Constants.wrkAplDvcd.CANCEL) {
            Ext.Msg.alert("안내", "정상 보고서만 보고취소가 가능합니다.");
            return false;
        }
        if (selectedData.hrHrpmEmpId != SecurityUtils.getPrincipal().hrHrpmEmpId) {
            Ext.Msg.alert("안내", "본인의 보고서만 보고취소가 가능합니다.");
            return false;
        }
        if (selectedData.reptAplStcd != Constants.aplStcd.COMPLETED_APPLY) {
            Ext.Msg.alert("안내", "보고상태가 \'완료(신청)\'인 보고서만 보고취소가 가능합니다.<br><br>보고상태가 \'진행(신청)\'인 경우에는 결재함에서 회수 하시기 바랍니다.");
            return false;
        }
        //add by jihyun
        if (selectedData.existBgBtrYn == Constants.exYesNo.YES.LETTER ) {
            Ext.Msg.alert("안내", "해당 건에 대해서 예산_여비정산서신청이 '진행/완료'된 신청서가 있습니다.<br> 신청 회수/취소 후 다시 신청바랍니다. ");
            return false;
        }
        //END VALIDATION AREA

        selectedData.stcd = Constants.stcd.OUTSTANDING; //상태 - 결재로 변경
        selectedData.aplStcd = Constants.aplStcd.COMPLETED_APPLY; //신청상태 - 완료
        selectedData.aplDvcd = Constants.wrkAplDvcd.CANCEL; //신청구분 - 취소

        Ext.Ajax.request({
            headers : {
                serviceId : 'HwmHodSvc.findAllHwmHodRept',
                viewId : me.getViewId(),
                scope : me
            },
            jsonData : selectedData,
            success : function(response) {
                var res = Ext.JSON.decode(response.responseText);
                if (res.errMsg) {
                    Ext.Msg.alert("안내", res.errMsg);
                    return;
                }
                Ext.Msg.confirm('알림', '※<b>유의사항 <br> 휴일근무보고 취소시 휴일근무취소는 따로 신청취소를 해야되며, <br> 보고취소는 결재 없이 바로 취소 됩니다. </b><br><br> 정말로 취소하시겠습니까? <br> ', function(btn) {
                    if (btn == 'yes') {
                        var result = {
                            newRecords : [],
                            modifiedRecords : [],
                            removedRecords : []
                        };
                        result.newRecords.push(selectedData);

                        //SERVICE 호출
                        Ext.Ajax.request({
                            headers : {
                                serviceId : 'HwmHodSvc.saveHwmHodRept',
                                viewId : me.getViewId()
                            },
                            jsonData : result,
                            success : function(response) {
                                var res = Ext.JSON.decode(response.responseText);
                                Ext.Msg.alert('알림', Messages.getMessage('I0000'));
                                me.onBtnSearchTap();
                            }
                        });
                    } else {
                        return false;
                    }
                });
            }
        });
    },

    /* 조회 버튼 */
    onBtnSearchTap: function(button, e, eOpts) {
        this.defaut();
        this.onSelect();
    },

    /* 신청 버튼 / 재기안 / 신청취소 */
    onApfData: function(button, e, eOpts) {
        var me = this,
            vm = me.getViewModel(),
            refs = me.getReferences(),
            grid = refs.grid,
            naviView = me.getView().up('navigationview'),
            itemId = button.config.itemId;

        switch (itemId) {
            case 'btnReApply' :						// 재기안 (정상신청이 X 면 신청 불가)
            console.log('재기안');
            var data = grid.getSelection().data;
            if (data.apfAplDvcd == Constants.wrkAplDvcd.CANCEL) {
                Ext.Msg.alert("안내", "정상 신청서만 재기안이 가능합니다.");
                return false;
            } else {
                me.PUSH_VIEW(naviView, {
                    menuId  : 'HwmHodAply02M',
                    title   : '휴일근무신청',
                    records : data,
                    isSubView : true,
                    parentView : me.getView(),
                    btnReApply : Constants.exYesNo.YES.LETTER		// 재기안 flag
                });
            }
            break;
            case 'btnBatch' :						// 신청
            console.log('신청');
            me.PUSH_VIEW(naviView, {
                menuId  : 'HwmHodAply02M',
                title   : '휴일근무신청',
                isSubView : true,
                parentView : me.getView()
            });
            break;
            case 'btnCancel' :						// 신청취소 (보고서 O or 정상 신청서 X 신청 불가)
            console.log('신청취소');
            me.onApfCancelSave();
            break;

        }

        me.menu.hide();		// 메뉴닫기
    },

    /* Grid Cell Click Event */
    onMygridSelect: function(dataview, selected, eOpts) {
        var me = this;
        var vm = me.getViewModel();
        var refs = me.getReferences();
        var grid = refs.grid;
        var records = grid.getStore().data.items;
        var trueRecords = selected; // 선택한 row 들

        // 하나만 선택되었는지 체크
        if(trueRecords.length > 1){
            Ext.Msg.alert('알림', '하나만 선택할 수 있습니다.');
            return;
        }

        me.menu.setDisplayed(true);
    },

    /* 초기화 */
    onContainerInitialize: function(component, eOpts) {
        var me = this,
            vm = me.getViewModel(),
            refs = me.getReferences(),
            grid = refs.grid,
            stDt = refs.startDate,
            edDt = refs.endDate;

        var dateMinus1 =new Date();
        dateMinus1.setDate(1);
        stDt.setValue(DateUtils.parseDate(dateMinus1));

        dateMinus1.setMonth(dateMinus1.getMonth()+1);
        dateMinus1.setDate(7);
        edDt.setValue(DateUtils.parseDate(dateMinus1));

        //보고서상태 - 콤보박스
        var cbxReptStcd = [ {
            text : '미작성',
            value : '01'
        }, {
            text : '작성',
            value : '02'
        } ];

        ComboboxUtils.makeCustomCbx(refs.aplStcd, cbxReptStcd, null);
        ComboboxUtils.setSelectFirstItem(refs.aplStcd);

        grid.el.select('.x-headercontainer').setStyle('height',	'0px');

        me.onSelect();
    },

    onContainerDestroy: function(eOpts) {
        // 메뉴 제거
        this.menu = Ext.destroy(this.menu);
    },

    onJsonstoreLoad: function(store, records, successful, operation, eOpts) {
        var me = this,
            refs = me.getReferences(),
            response = operation.getResponse();

        if(response){
            var result = response.responseJson,
                totAdmtOvtHod = result.totAdmtOvtHod;

            refs.totOvtHodMonthDds.setValue(totAdmtOvtHod.totOvtHodMonthDds);	// 금월(일)
            refs.totOvtHodMonthHr.setValue(totAdmtOvtHod.totOvtHodMonthHr);		// 금월(시)
            refs.totOvtHodWeekDds.setValue(totAdmtOvtHod.totOvtHodWeekDds);		// 금주(일)
            refs.totOvtHodWeekHr.setValue(totAdmtOvtHod.totOvtHodWeekHr);		// 금주(시)
        }
    }

});