/*
 * File: app/view/HumanResource/hwm/HwmMthEmpe01M.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

/*
    모바일 :: 월별근태 - 항목

    @author BNK시스템/기타/이상근
    @since 2019.06.14
    @version 1.0
    @see

    << 개정이력(Modification Information) >>

    수정일		  수정자                수정내용
    ----------	------------------   --------------------------
    2019.06.14	BNK시스템/기타/이상근   최초 생성
*/
Ext.define('BNK.view.HumanResource.hwm.HwmMthEmpe01M', {
    extend: 'Ext.Container',
    alias: 'widget.HwmMthEmpe01M',

    alternateClassName: [
        'HwmMthEmpe01M'
    ],
    requires: [
        'BNK.view.HumanResource.hwm.HwmMthEmpe01MViewModel',
        'BNK.view.HumanResource.hwm.HwmMthEmpe01MViewController',
        'Ext.field.Date',
        'Ext.picker.Date',
        'Ext.tab.Panel',
        'Ext.calendar.panel.Panel',
        'Ext.calendar.panel.Month',
        'Ext.Label',
        'Ext.grid.Grid',
        'Ext.grid.column.Column'
    ],

    controller: 'humanresource.hwm.hwmmthempe01m',
    viewModel: {
        type: 'humanresource.hwm.hwmmthempe01m'
    },
    itemId: 'budget.exp.expnteaply01m1',
    scrollable: true,
    layout: 'vbox',

    items: [
        {
            xtype: 'container',
            height: 60,
            docked: 'top',
            scrollable: true,
            layout: {
                type: 'vbox',
                align: 'center',
                pack: 'center'
            },
            items: [
                {
                    xtype: 'datefield',
                    reference: 'dtpStDt',
                    width: 200,
                    editable: false,
                    textAlign: 'center',
                    dateFormat: 'Y년 m월',
                    picker: {
                        xtype: 'datepicker',
                        hideOnMaskTap: true,
                        header: false,
                        title: '',
                        dayText: '일',
                        monthText: '월',
                        slotOrder: [
                            'year',
                            'month'
                        ],
                        yearText: '년'
                    },
                    listeners: {
                        change: 'onDatefieldChange'
                    }
                }
            ]
        },
        {
            xtype: 'container',
            reference: 'allCntCheckScreen',
            height: 100,
            hidden: false,
            docked: 'top',
            scrollable: true,
            layout: {
                type: 'vbox',
                align: 'center',
                pack: 'center'
            }
        },
        {
            xtype: 'tabpanel',
            flex: 1,
            reference: 'tab',
            width: '100%',
            autoSize: false,
            layout: {
                type: 'card',
                animation: 'slide'
            },
            items: [
                {
                    xtype: 'container',
                    title: '월별(달력)',
                    scrollable: true,
                    layout: 'fit',
                    items: [
                        {
                            xtype: 'calendar',
                            reference: 'cal',
                            disabled: false,
                            width: '100%',
                            scrollable: true,
                            minButtonWidth: 100,
                            bind: {
                                calendarList: 'false',
                                sideBar: 'false'
                            },
                            views: {
                                month: {
                                    xtype: 'calendar-month',
                                    editForm: false,
                                    disabled: false,
                                    label: 'Month',
                                    listeners: {
                                        valuechange: 'onCalendarmonthValueChange'
                                    }
                                }
                            }
                        }
                    ]
                },
                {
                    xtype: 'container',
                    title: '일별',
                    height: '100%',
                    hidden: false,
                    scrollable: false,
                    layout: {
                        type: 'vbox',
                        align: 'stretchmax'
                    },
                    items: [
                        {
                            xtype: 'container',
                            reference: 'inputInfo',
                            height: '100%',
                            docked: 'top',
                            scrollable: true,
                            layout: 'vbox',
                            items: [
                                {
                                    xtype: 'container',
                                    layout: 'hbox',
                                    items: [
                                        {
                                            xtype: 'container',
                                            flex: 3,
                                            padding: '10px',
                                            layout: 'vbox',
                                            items: [
                                                {
                                                    xtype: 'label',
                                                    style: 'font-size:30px',
                                                    html: '1일'
                                                },
                                                {
                                                    xtype: 'label',
                                                    html: '(목)'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'container',
                                            flex: 7,
                                            padding: '10px'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'grid',
                                    flex: 1,
                                    reference: 'empeInfoGrid',
                                    height: '100%',
                                    hidden: true,
                                    hideMode: 'visibility',
                                    width: '100%',
                                    autoSize: false,
                                    deselectOnContainerClick: false,
                                    bufferSize: 100,
                                    variableHeights: true,
                                    hideHeaders: true,
                                    bind: {
                                        store: '{empeStore}'
                                    },
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            renderer: function(value, record, dataIndex, cell, column) {
                                                var week = new Array('일','월','화','수','목','금','토');
                                                var data =record.data ;

                                                var nowDate = new Date();
                                                nowDate.setYear(data.wrkDt.substr(0,4));
                                                nowDate.setMonth(data.wrkDt.substr(4,2)*1 -1);
                                                nowDate.setDate( data.wrkDt.substr(6,2));

                                                var day = nowDate.getDay();
                                                var color = (day === 0 ? 'red' : (day == 6 ? 'blue' : 'black'));
                                                color = (data.hldYn == 1 && data.rmrkCntn !== null ? 'red' : color );

                                                var result = '<div style="width: 30%; height : 100%; display:table-cell;padding:0px;" ><div style="font-size:30px">'+nowDate.getDate()+'일</div>' +
                                                '<span><font color="'+color+'">('+week[nowDate.getDay()] +')</font>' +
                                                ((data.rmrkCntn !== null && data.rmrkCntn !== undefined) ? '<font color="'+color+'">' +data.rmrkCntn +'</font></span></div>':"" )+'</span></div>';

                                                // var result = '<div style="float:left;width: 30%; height : 100%;" ><span style="font-size:30px">'+nowDate.getDate()+'일</span>' +
                                                //              ' <br><span><font color="'+color+'">('+week[nowDate.getDay()] +')</font>' +
                                                //             ((data.rmrkCntn !== null && data.rmrkCntn !== undefined) ? '<font color="'+color+'">' +data.rmrkCntn +'</font>':"" )+'</span></div>';
                                                var chulgun = (data.wrkStrtm === null ? "" : "출근 : " + data.wrkStrtm.substring(0,2) + "시 " + data.wrkStrtm.substring(2,4) + "분");
                                                // var tueGun = (data.wrkEdtm === null ? "" : "퇴근 : " + data.wrkEdtm.substring(0,2) + "시 " + data.wrkEdtm.substring(2,4) + "분");

                                                var ovtChk = (Ext.isEmpty(data.ovtChk) ? "" : "<span style='height:100%;'>근무확인 : </span><br><span>" + data.ovtChk + "</span>");

                                                // 근무지 정보 추가
                                                var wkplcNm = (data.wkplcNm == null) ? "" : "근무지 : " + data.wkplcNm;

                                                // result += '<div style="width: 40%;"><span>'+chulgun+'</span> ' + '<br><span>'+tueGun+'&nbsp </span>' + '<br><span>'+ wkplcNm + '</span></div>';
                                                result += '<div style="height:100%;display:table-cell;padding:0px;"><div>'+chulgun+'</div><div>' + ovtChk + '</div><div>'+ wkplcNm + '</div>';

                                                var workData = {'outYn' : '외근',
                                                        'btrYn' : '출장',
                                                        'lateYn' : '지각',
                                                        'elvYn' : '조퇴',
                                                        'absnYn' : '결근',
                                                        'vctYn' : '휴가',
                                                        'ovtYn' : '연장근무',
                                                    'hodYn' : '휴일근무'};

                                                var styleColumn = 'float:left; margin : 0 5px 0 0;';

                                                var styleValue =  'font-size:13px;'+
                                                'font-weight:bold;'+
                                                'width:100%;'+
                                                'overflow: hidden;'+
                                                'white-space:nowrap;'+
                                                'text-overflow:ellipsis;'+
                                                'text-align:center;'+
                                                'display:inline-block;';

                                                var emptyChk = true;

                                                var etcInfo = '<div style="width: 100%;">';
                                                for(var key in workData){
                                                    if(data[key] != "0"){
                                                        emptyChk = false;
                                                        etcInfo += '		<div style="'+styleColumn+'">';
                                                        etcInfo += '			<span style="'+styleValue+'">'+ workData[key] +"&nbsp;</span>";
                                                        etcInfo += '		</div>';
                                                    }
                                                }

                                                etcInfo += '</div>';
                                                if(!emptyChk){
                                                    result += etcInfo;
                                                }

                                                result += '</div>';

                                                return '<div style="display:table; width : 100%;"><div style="display:table-row; width : 100%;">' + result + '</div></div>';

                                            },
                                            flex: '1',
                                            hidden: false,
                                            minHeight: '75px',
                                            cell: {
                                                xtype: 'gridcell',
                                                encodeHtml: false
                                            },
                                            dataIndex: 'hrHrpmEmpId'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ],
    listeners: {
        initialize: 'initialize'
    }

});