/*
 * File: app/view/HumanResource/hwm/HwmVctAply71M.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

/*
    모바일 시스템 근태관리 :: 휴가신청 결재함 상세 - 화면

    @author BNK시스템/파트너/서무성
    @since 2022.02.03
    @version 1.0
    @see

    << 개정이력(Modification Information) >>

    수정일		  수정자                  수정내용
    ----------	------------------     --------------------------
    2022.02.03	BNK시스템/파트너/서무성   최초 생성
*/
Ext.define('BNK.view.HumanResource.hwm.HwmVctAply71M', {
    extend: 'Ext.window.Window',
    alias: 'widget.HwmVctAply71M',

    alternateClassName: [
        'HwmVctAply71M'
    ],
    requires: [
        'BNK.view.HumanResource.hwm.HwmVctAply71MViewModel',
        'BNK.view.HumanResource.hwm.HwmVctAply71MViewController',
        'BNK.view.HumanResource.hwm.HwmVctAply71MContainer',
        'BNK.view.common.ApprovalLineGrid',
        'BNK.view.common.EdocButtonContainer',
        'Ext.Label',
        'Ext.Spacer',
        'Ext.grid.Grid'
    ],

    controller: 'HwmVctAply71MViewController',
    viewModel: {
        type: 'HwmVctAply71MViewModel'
    },
    height: '98%',
    width: '98%',
    layout: 'vbox',

    items: [
        {
            xtype: 'container',
            flex: 1,
            margin: 15,
            layout: 'vbox',
            items: [
                {
                    xtype: 'container',
                    margin: '0 0 7 0',
                    layout: 'hbox',
                    items: [
                        {
                            xtype: 'label',
                            style: 'font-size : 20px',
                            html: '구분'
                        },
                        {
                            xtype: 'spacer',
                            flex: 1
                        },
                        {
                            xtype: 'label',
                            reference: 'headTitle',
                            style: 'font-size : 20px; color : red;',
                            html: '휴가 신청서'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    margin: '0 0 7 0',
                    layout: 'hbox',
                    items: [
                        {
                            xtype: 'label',
                            style: 'font-size : 20px',
                            html: '상신일'
                        },
                        {
                            xtype: 'spacer',
                            flex: 1
                        },
                        {
                            xtype: 'label',
                            reference: 'rgdt',
                            style: 'font-size : 20px; color : red;'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    flex: 1,
                    scrollable: 'vertical',
                    layout: 'vbox',
                    items: [
                        {
                            xtype: 'HwmVctAply71Mcontianer',
                            reference: 'applyInfo'
                        },
                        {
                            xtype: 'common.approvallinegrid',
                            height: 450
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'common.edocbuttoncontainer',
            docked: 'bottom'
        }
    ],
    listeners: {
        initialize: 'Initialize'
    }

});