/*
 * File: app/view/HumanResource/hwm/HwmWplMngr51MViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

/*
    모바일 시스템 근태관리 :: 근무지 조회 - 컨트롤러

    @author BNK시스템/계장/지민영
    @since 2020.04.17
    @version 1.0
    @see

    << 개정이력(Modification Information) >>

    수정일		  수정자                수정내용
    ----------	------------------   --------------------------
    2020.04.17	BNK시스템/계장/지민영   최초 생성
*/
Ext.define('BNK.view.HumanResource.hwm.HwmWplMngr51MViewController', {
    extend: 'BaseViewController',
    alias: 'controller.HwmWplMngr51MViewController',

    config: {
        viewId: 'HwmWplMngr51M'
    },

    onSelect: function(pageReset) {
        var me = this,
            vm = me.getViewModel(),
            refs = me.getReferences(),
            page = arguments[0] || 1, 	// 페이지 초기화
            grid = refs.wkplcInfoGrid,
            store = grid.getStore();

        var values = {
            stcd  : Constants.stcd.NORMAL,
            startDate : DateUtils.getDate(new Date()),
            filterHrWrkmWkplcId : vm.data.detail.record.data.filterHrWrkmWkplcId
        };

        store.getProxy().extraParams = values;

        if(pageReset){
             store.getProxy().extraParams.page = 1;
             var toolbar = grid.getPlugins()[0];
             toolbar.setCurrentPage(1);
        }

        store.removeAll();
        store.loadPage(1);
    },

    initialize: function(component, eOpts) {
        var me = this,
            refs = me.getReferences(),
            vm = me.getViewModel(),
            config = component.config;

        vm.set('detail.records',config.records);
        vm.set('detail.record',config.record);
        vm.set('detail.ctl',config.ctl);

        refs.wkplcInfoGrid.setStore(vm.storeInfo.WkplcInfoStore);

        me.onSelect(false);
    },

    onGridSelect: function(dataview, selected, eOpts) {
        var me = this,
            vm = me.getViewModel(),
            data = selected[0].data;

        me.getView().fireEvent('selected', data);
        me.onBtnCloseTap();
    },

    onBtnCloseTap: function(button, e, eOpts) {
        this.getReferences().wkplcInfoGrid.getStore().removeAll();
        this.getView().close();
    }

});