/*
 * File: app/view/HumanResource/hrd/HrdCrsRept71M.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

/*
    모바일 :: 연수과정/연수과정 보고 결재함 - 화면

    @author BNK시스템/파트너/지민영
    @since 2020.11.09
    @version 1.0
    @see

    << 개정이력(Modification Information) >>

    수정일		  수정자                  수정내용
    ----------	--------------------   --------------------------
    2020.11.09	BNK시스템/파트너/지민영   최초 생성
*/
Ext.define('BNK.view.HumanResource.hrd.HrdCrsRept71M', {
    extend: 'Ext.window.Window',
    alias: 'widget.HrdCrsRept71M',

    alternateClassName: [
        'HrdCrsRept71M'
    ],
    requires: [
        'BNK.view.HumanResource.hrd.HrdCrsRept71MViewModel',
        'BNK.view.HumanResource.hrd.HrdCrsRept71MViewController',
        'BNK.view.common.ApprovalLineGrid',
        'BNK.view.common.EdocButtonContainer',
        'Ext.Label',
        'Ext.form.Panel',
        'Ext.field.Display',
        'Ext.field.TextArea',
        'Ext.Button',
        'Ext.grid.Grid'
    ],

    controller: 'HrdCrsRept71MViewController',
    viewModel: {
        type: 'HrdCrsRept71MViewModel'
    },
    height: '98%',
    width: '98%',
    scrollable: 'both',
    layout: 'vbox',

    listeners: {
        initialize: 'onContainerInitialize'
    },
    items: [
        {
            xtype: 'container',
            height: '100%',
            scrollable: 'vertical',
            layout: 'vbox',
            items: [
                {
                    xtype: 'container',
                    flex: 2,
                    docked: 'top',
                    margin: 15,
                    layout: 'vbox',
                    items: [
                        {
                            xtype: 'container',
                            margin: '0 0 7 0',
                            layout: 'hbox',
                            items: [
                                {
                                    xtype: 'label',
                                    style: 'fontSize: 20px;',
                                    docked: 'left',
                                    html: '구분'
                                },
                                {
                                    xtype: 'label',
                                    reference: 'headTitle',
                                    style: 'color:red; fontSize: 20px;',
                                    docked: 'right',
                                    html: '연수보고서'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            layout: 'hbox',
                            items: [
                                {
                                    xtype: 'label',
                                    style: 'fontSize: 20px;',
                                    docked: 'left',
                                    html: '상신일'
                                },
                                {
                                    xtype: 'label',
                                    reference: 'rgdt',
                                    style: 'fontSize: 20px;',
                                    docked: 'right'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'formpanel',
                    reference: 'frmDetail',
                    items: [
                        {
                            xtype: 'container',
                            margin: '10 0 0 0',
                            layout: 'hbox',
                            items: [
                                {
                                    xtype: 'label',
                                    width: '25%',
                                    docked: 'left',
                                    html: '신청자',
                                    margin: '0 10 0 0'
                                },
                                {
                                    xtype: 'textfield',
                                    flex: 1,
                                    reference: 'rqpr',
                                    name: 'rqpr',
                                    readOnly: true,
                                    editable: false,
                                    bind: {
                                        value: '{detail.rqpr}'
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            margin: '10 0 0 0',
                            layout: 'hbox',
                            items: [
                                {
                                    xtype: 'label',
                                    width: '25%',
                                    docked: 'left',
                                    html: '신청구분',
                                    margin: '0 10 0 0'
                                },
                                {
                                    xtype: 'textfield',
                                    flex: 1,
                                    reference: 'aplDvcd',
                                    hidden: true,
                                    name: 'aplDvcd',
                                    required: true,
                                    readOnly: true,
                                    editable: false,
                                    bind: {
                                        value: '{detail.aplDvcd}'
                                    }
                                },
                                {
                                    xtype: 'textfield',
                                    flex: 1,
                                    reference: 'aplDvcdNm',
                                    name: 'aplDvcdNm',
                                    readOnly: true,
                                    editable: false,
                                    bind: {
                                        value: '{detail.aplDvcdNm}'
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            reference: 'hrHrdmStnApfForm',
                            hidden: true,
                            margin: '10 0 0 0',
                            layout: 'hbox',
                            items: [
                                {
                                    xtype: 'label',
                                    width: '25%',
                                    docked: 'left',
                                    html: '신청서',
                                    margin: '0 10 0 0'
                                },
                                {
                                    xtype: 'textfield',
                                    flex: 1,
                                    reference: 'hrHrdmStnApfName',
                                    name: 'hrHrdmStnApfName',
                                    required: true,
                                    readOnly: true,
                                    editable: false,
                                    bind: {
                                        value: '{stnApfInfo.hrHrdmStnApfName}'
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            hidden: true,
                            items: [
                                {
                                    xtype: 'textfield',
                                    reference: 'dpnm',
                                    name: 'dpnm',
                                    readOnly: true,
                                    editable: false,
                                    bind: {
                                        value: '{detail.dpnm}'
                                    }
                                },
                                {
                                    xtype: 'textfield',
                                    reference: 'empeNm',
                                    name: 'empeNm',
                                    readOnly: true,
                                    editable: false,
                                    bind: {
                                        value: '{detail.empeNm}'
                                    }
                                },
                                {
                                    xtype: 'textfield',
                                    reference: 'empeNo',
                                    name: 'empeNo',
                                    readOnly: true,
                                    editable: false,
                                    bind: {
                                        value: '{detail.empeNo}'
                                    }
                                },
                                {
                                    xtype: 'textfield',
                                    reference: 'empePsitNm',
                                    name: 'empePsitNm',
                                    readOnly: true,
                                    editable: false,
                                    bind: {
                                        value: '{detail.empePsitNm}'
                                    }
                                },
                                {
                                    xtype: 'textfield',
                                    reference: 'txtId',
                                    name: 'id',
                                    readOnly: true,
                                    editable: false,
                                    bind: {
                                        value: '{detail.id}'
                                    }
                                },
                                {
                                    xtype: 'textfield',
                                    reference: 'crud',
                                    name: 'crud',
                                    readOnly: true,
                                    editable: false,
                                    bind: {
                                        value: '{detail.crud}'
                                    }
                                },
                                {
                                    xtype: 'textfield',
                                    reference: 'stcd',
                                    name: 'stcd',
                                    required: true,
                                    readOnly: true,
                                    editable: false,
                                    bind: {
                                        value: '{detail.stcd}'
                                    }
                                },
                                {
                                    xtype: 'textfield',
                                    reference: 'stcdNm',
                                    name: 'stcdNm',
                                    readOnly: true,
                                    editable: false,
                                    bind: {
                                        value: '{detail.stcdNm}'
                                    }
                                },
                                {
                                    xtype: 'textfield',
                                    reference: 'hrHrpmCompId',
                                    name: 'hrHrpmCompId',
                                    required: true,
                                    readOnly: true,
                                    editable: false,
                                    bind: {
                                        value: '{detail.hrHrpmCompId}'
                                    }
                                },
                                {
                                    xtype: 'textfield',
                                    reference: 'hrHrpmEmpId',
                                    name: 'hrHrpmEmpId',
                                    required: true,
                                    readOnly: true,
                                    editable: false,
                                    bind: {
                                        value: '{detail.hrHrpmEmpId}'
                                    }
                                },
                                {
                                    xtype: 'textfield',
                                    reference: 'aplStcd',
                                    name: 'aplStcd',
                                    required: true,
                                    readOnly: true,
                                    editable: false,
                                    bind: {
                                        value: '{detail.aplStcd}'
                                    }
                                },
                                {
                                    xtype: 'textfield',
                                    reference: 'aplStcdNm',
                                    name: 'aplStcdNm',
                                    readOnly: true,
                                    editable: false,
                                    bind: {
                                        value: '{detail.aplStcdNm}'
                                    }
                                },
                                {
                                    xtype: 'textfield',
                                    reference: 'hrHrdmStnEmpCreptId',
                                    name: 'hrHrdmStnEmpCreptId',
                                    readOnly: true,
                                    editable: false
                                },
                                {
                                    xtype: 'textfield',
                                    reference: 'comAprHistApfId',
                                    name: 'comAprHistApfId',
                                    readOnly: true,
                                    editable: false,
                                    bind: {
                                        value: '{stnApfInfo.comAprHistApfId}'
                                    }
                                },
                                {
                                    xtype: 'textfield',
                                    reference: 'hrHrdmStnEmpId',
                                    name: 'hrHrdmStnEmpId',
                                    readOnly: true,
                                    editable: false,
                                    bind: {
                                        value: '{stnApfInfo.hrHrdmStnEmpId}'
                                    }
                                },
                                {
                                    xtype: 'textfield',
                                    reference: 'hrHrdmStnOrgtId',
                                    name: 'hrHrdmStnOrgtId',
                                    readOnly: true,
                                    editable: false,
                                    bind: {
                                        value: '{stnApfInfo.hrHrdmStnOrgtId}'
                                    }
                                },
                                {
                                    xtype: 'textfield',
                                    reference: 'hrHrdmStnCrsId',
                                    name: 'hrHrdmStnCrsId',
                                    readOnly: true,
                                    editable: false,
                                    bind: {
                                        value: '{stnApfInfo.hrHrdmStnCrsId}'
                                    }
                                },
                                {
                                    xtype: 'textfield',
                                    reference: 'sttnAplDt',
                                    name: 'sttnAplDt',
                                    readOnly: true,
                                    editable: false,
                                    bind: {
                                        value: '{stnApfInfo.sttnAplDt}'
                                    }
                                },
                                {
                                    xtype: 'textfield',
                                    reference: 'hrHromEmpPntId',
                                    name: 'hrHromEmpPntId',
                                    readOnly: true,
                                    editable: false,
                                    bind: {
                                        value: '{stnApfInfo.hrHromEmpPntId}'
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            margin: '10 0 0 0',
                            layout: 'hbox',
                            items: [
                                {
                                    xtype: 'label',
                                    width: '25%',
                                    docked: 'left',
                                    html: '과정명',
                                    margin: '0 10 0 0'
                                },
                                {
                                    xtype: 'displayfield',
                                    flex: 1,
                                    reference: 'sttnCrsNm',
                                    name: 'sttnCrsNm',
                                    style: 'border-bottom-style:solid;border-bottom-color:var(--divider-color);border-bottom-width:1px;',
                                    bind: {
                                        value: '{detail.sttnCrsNm}'
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            margin: '10 0 0 0',
                            layout: 'hbox',
                            items: [
                                {
                                    xtype: 'label',
                                    width: '25%',
                                    docked: 'left',
                                    html: '기관명',
                                    margin: '0 10 0 0'
                                },
                                {
                                    xtype: 'textfield',
                                    flex: 1,
                                    reference: 'stnOrgtNm',
                                    name: 'stnOrgtNm',
                                    readOnly: true,
                                    editable: false,
                                    bind: {
                                        value: '{stnApfInfo.stnOrgtNm}'
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            margin: '10 0 0 0',
                            layout: 'hbox',
                            items: [
                                {
                                    xtype: 'label',
                                    width: '25%',
                                    docked: 'left',
                                    html: '시작일자',
                                    margin: '0 10 0 0'
                                },
                                {
                                    xtype: 'textfield',
                                    flex: 1,
                                    reference: 'sttnStrdt',
                                    hidden: true,
                                    name: 'sttnStrdt',
                                    readOnly: true,
                                    editable: false,
                                    bind: {
                                        value: '{stnApfInfo.sttnStrdt}'
                                    }
                                },
                                {
                                    xtype: 'textfield',
                                    flex: 1,
                                    reference: 'sttnStrdtHiphone',
                                    name: 'sttnStrdtHiphone',
                                    readOnly: true,
                                    editable: false,
                                    bind: {
                                        value: '{stnApfInfo.sttnStrdtHiphone}'
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            margin: '10 0 0 0',
                            layout: 'hbox',
                            items: [
                                {
                                    xtype: 'label',
                                    width: '25%',
                                    docked: 'left',
                                    html: '종료일자',
                                    margin: '0 10 0 0'
                                },
                                {
                                    xtype: 'textfield',
                                    flex: 1,
                                    reference: 'sttnEdt',
                                    hidden: true,
                                    name: 'sttnEdt',
                                    readOnly: true,
                                    editable: false,
                                    bind: {
                                        value: '{stnApfInfo.sttnEdt}'
                                    }
                                },
                                {
                                    xtype: 'textfield',
                                    flex: 1,
                                    reference: 'sttnEdtHiphone',
                                    name: 'sttnEdtHiphone',
                                    readOnly: true,
                                    editable: false,
                                    bind: {
                                        value: '{stnApfInfo.sttnEdtHiphone}'
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            margin: '10 0 0 0',
                            layout: 'hbox',
                            items: [
                                {
                                    xtype: 'label',
                                    width: '25%',
                                    docked: 'left',
                                    html: '연수시간',
                                    margin: '0 10 0 0'
                                },
                                {
                                    xtype: 'textfield',
                                    flex: 1,
                                    reference: 'sttnCmpHr',
                                    name: 'sttnCmpHr',
                                    readOnly: true,
                                    editable: false,
                                    bind: {
                                        value: '{stnApfInfo.sttnCmpHr}'
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            margin: '10 0 0 0',
                            layout: 'hbox',
                            items: [
                                {
                                    xtype: 'label',
                                    width: '25%',
                                    docked: 'left',
                                    html: '포인트',
                                    margin: '0 10 0 0'
                                },
                                {
                                    xtype: 'textfield',
                                    flex: 1,
                                    reference: 'sttnCmpPnt',
                                    name: 'sttnCmpPnt',
                                    readOnly: true,
                                    editable: false,
                                    bind: {
                                        value: '{stnApfInfo.sttnCmpPnt}'
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            margin: '10 0 0 0',
                            layout: 'hbox',
                            items: [
                                {
                                    xtype: 'label',
                                    width: '25%',
                                    docked: 'left',
                                    html: '연수과정 <br> 주요내용',
                                    margin: '0 10 0 0'
                                },
                                {
                                    xtype: 'textareafield',
                                    reference: 'sttnMnCntn',
                                    height: 150,
                                    name: 'sttnMnCntn',
                                    width: '100%',
                                    required: true,
                                    value: '□ 연수목표: \n□ 연수내용: \n□ 연수과정평(보완점): \n'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            margin: '10 0 0 0',
                            layout: 'hbox',
                            items: [
                                {
                                    xtype: 'label',
                                    width: '25%',
                                    docked: 'left',
                                    html: '활용계획<br>(조직,직무 등)',
                                    margin: '0 10 0 0'
                                },
                                {
                                    xtype: 'textareafield',
                                    reference: 'sttnPusePln',
                                    height: 150,
                                    name: 'sttnPusePln',
                                    width: '100%',
                                    required: true,
                                    value: '□ 관련업무 연계성: \n□ 향후 활용방안: \n'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            reference: 'file',
                            itemId: 'atchFile',
                            width: '100%',
                            margin: '20 0 0 0',
                            items: [
                                {
                                    xtype: 'textfield',
                                    reference: 'atchFileParentId',
                                    hidden: true,
                                    itemId: 'atchFileParentId',
                                    name: 'atchFileParentId'
                                },
                                {
                                    xtype: 'textfield',
                                    reference: 'atchFileId',
                                    hidden: true,
                                    itemId: 'atchFileId',
                                    name: 'atchFileId'
                                },
                                {
                                    xtype: 'container',
                                    layout: 'hbox',
                                    items: [
                                        {
                                            xtype: 'label',
                                            width: '25%',
                                            docked: 'left',
                                            html: '첨부 파일',
                                            margin: '0 10 0 0'
                                        },
                                        {
                                            xtype: 'textfield',
                                            flex: 1,
                                            reference: 'atchFileNm',
                                            itemId: 'atchFileNm',
                                            name: 'atchFileNm',
                                            style: '',
                                            editable: false,
                                            triggers: {
                                                clear: {
                                                    // cls : 'x-form-clear-trigger',
                                                    iconCls: 'x-fa fa-close',
                                                    handler: function(view) {
                                                            view.up('#atchFile').down('#atchFileId').reset();
                                                            view.reset();
                                                            view.up('#atchFile').down('#downloadBtn').setDisabled(true);		// downloadBtn
                                                        }
                                                },
                                                search: {
                                                    weight: 1,
                                                    // cls : Ext.baseCSSPrefix + 'form-search-trigger',
                                                    iconCls: 'x-fa fa-search',
                                                    handler: function() {
                                                            var view = this.up('#atchFile');
                                                
                                                            var win = Ext.create('FileUploadPopupV1', { 
                                                                encrypt : false, // 2019.08.08 현재 기준 파일 암호화 에러 발생하여 , 다 false 처리함.
                                                                //                      comCmmFileId : view.down('#atchFileId').getValue()
                                                                comCmmFileId : view.down('#atchFileParentId').getValue()
                                                            });
                                                            this.mon(win, 'selected', function(record) {
                                                                var view = this.up('#atchFile');
                                                                view.down('#atchFileParentId').setValue(record.fileId);
                                                                view.down('#atchFileId').setValue(record.dtlFileId);
                                                                view.down('#atchFileNm').setValue(record.fileNm);
                                                                
                                                                //downloadBtn
                                                                if (record.fileId) {
                                                                    view.down('#downloadBtn').setDisabled(false);
                                                                }
                                                
                                                                // 팝업창 닫음
                                                                if (Ext.getCmp('FileUploadPopupV1')) {
                                                                    Ext.getCmp('FileUploadPopupV1').close();
                                                                }
                                                            }, this);
                                                
                                                            win.show();
                                                        },
                                                    scope: 'this'
                                                }
                                            }
                                        },
                                        {
                                            xtype: 'button',
                                            reference: 'downloadBtn',
                                            disabled: true,
                                            itemId: 'downloadBtn',
                                            name: 'downloadBtn',
                                            style: 'border:solid 1px var(--divider-color);',
                                            margin: '0 0 0 10',
                                            iconCls: 'x-fa fa-download',
                                            listeners: {
                                                tap: 'onBtnDownTap'
                                            }
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            margin: '10 0 0 0',
                            items: [
                                {
                                    xtype: 'label',
                                    html: '<font style="color:red"><p><strong>※ 작성 절차: (1)연수신청서 작성 (2)연수보고서 작성&nbsp;</strong></p><p><strong>※ 작성 방법: 100자 이상</strong></p><p></font>1. 연수과정 주요내용&nbsp;</p><p>- 가이드라인에 해당하는 내용 작성&nbsp;</p><p>2. 활용계획(조직,직무 등)</p><p>&nbsp;- 가이드라인에 해당하는 내용 작성</p><font style="color:red"><p><strong>※ 첨부 파일: 연수과정을 수료한 증빙 자료 첨부 </strong></p></font><p>1. KES DAY: 첨부 생략&nbsp;</p><p>2. 사이버 연수: 수료증, 수료증 발급 불가 시 진도화면 캡쳐본&nbsp;</p><p>3. 집합연수: 수료증, 수료증 발급 불가 시 첨부 생략</p>'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    disabled: true,
                    scrollable: 'both',
                    layout: 'vbox',
                    items: [
                        {
                            xtype: 'common.approvallinegrid',
                            height: 450
                        },
                        {
                            xtype: 'textfield',
                            hidden: true,
                            name: 'version',
                            label: 'version',
                            bind: {
                                value: '{formValues.version}'
                            }
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'common.edocbuttoncontainer',
            docked: 'bottom'
        }
    ]

});