/*
 * File: app/view/HumanResource/hrd/HrdCrsInfo71M.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

/*
    모바일 :: 연수과정/연수과정 신청취소 결재함 - 화면

    @author BNK시스템/파트너/지민영
    @since 2020.11.04
    @version 1.0
    @see

    << 개정이력(Modification Information) >>

    수정일		  수정자                  수정내용
    ----------	--------------------   --------------------------
    2020.11.04	BNK시스템/파트너/지민영   최초 생성
*/
Ext.define('BNK.view.HumanResource.hrd.HrdCrsInfo71M', {
    extend: 'Ext.window.Window',
    alias: 'widget.HrdCrsInfo71M',

    alternateClassName: [
        'HrdCrsInfo71M'
    ],
    requires: [
        'BNK.view.HumanResource.hrd.HrdCrsInfo71MViewModel',
        'BNK.view.HumanResource.hrd.HrdCrsInfo71MViewController',
        'BNK.view.common.ApprovalLineGrid',
        'BNK.view.common.EdocButtonContainer',
        'Ext.Label',
        'Ext.form.Panel',
        'Ext.field.Text',
        'Ext.field.Display',
        'Ext.grid.Grid',
        'Ext.Toolbar',
        'Ext.grid.column.Column',
        'Ext.grid.plugin.PagingToolbar'
    ],

    controller: 'HrdCrsInfo71MViewController',
    viewModel: {
        type: 'HrdCrsInfo71MViewModel'
    },
    height: '98%',
    width: '98%',
    scrollable: 'both',
    layout: 'vbox',

    listeners: {
        initialize: 'onContainerInitialize'
    },
    items: [
        {
            xtype: 'container',
            height: '100%',
            scrollable: 'vertical',
            layout: 'vbox',
            items: [
                {
                    xtype: 'container',
                    flex: 2,
                    docked: 'top',
                    margin: 15,
                    layout: 'vbox',
                    items: [
                        {
                            xtype: 'container',
                            margin: '0 0 7 0',
                            layout: 'hbox',
                            items: [
                                {
                                    xtype: 'label',
                                    style: 'fontSize: 20px;',
                                    docked: 'left',
                                    html: '구분'
                                },
                                {
                                    xtype: 'label',
                                    reference: 'headTitle',
                                    style: 'color:red; fontSize: 20px;',
                                    docked: 'right',
                                    html: '연수취소신청서'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            layout: 'hbox',
                            items: [
                                {
                                    xtype: 'label',
                                    style: 'fontSize: 20px;',
                                    docked: 'left',
                                    html: '상신일'
                                },
                                {
                                    xtype: 'label',
                                    reference: 'rgdt',
                                    style: 'fontSize: 20px;',
                                    docked: 'right'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'formpanel',
                    reference: 'detailForm',
                    padding: 5,
                    items: [
                        {
                            xtype: 'textfield',
                            reference: 'id',
                            hidden: true,
                            bind: {
                                value: '{detail.id}'
                            }
                        },
                        {
                            xtype: 'textfield',
                            reference: 'crud',
                            hidden: true,
                            bind: {
                                value: '{detail.crud}'
                            }
                        },
                        {
                            xtype: 'container',
                            margin: '10 0 0 0',
                            layout: 'hbox',
                            items: [
                                {
                                    xtype: 'label',
                                    width: '25%',
                                    docked: 'left',
                                    html: '과정명',
                                    margin: '0 10 0 0'
                                },
                                {
                                    xtype: 'displayfield',
                                    flex: 1,
                                    reference: 'sttnCrsNm',
                                    style: 'border-bottom-style:solid;border-bottom-color:var(--divider-color);border-bottom-width:1px;',
                                    bind: {
                                        value: '{detail.sttnCrsNm}'
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            margin: '10 0 0 0',
                            layout: 'hbox',
                            items: [
                                {
                                    xtype: 'label',
                                    width: '25%',
                                    docked: 'left',
                                    html: '구분',
                                    margin: '0 10 0 0'
                                },
                                {
                                    xtype: 'textfield',
                                    flex: 1,
                                    reference: 'crudNm',
                                    readOnly: true,
                                    editable: false
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            margin: '10 0 0 0',
                            layout: 'hbox',
                            items: [
                                {
                                    xtype: 'label',
                                    width: '25%',
                                    docked: 'left',
                                    html: '상태',
                                    margin: '0 10 0 0'
                                },
                                {
                                    xtype: 'textfield',
                                    flex: 1,
                                    reference: 'stcdNm',
                                    readOnly: true,
                                    editable: false
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            margin: '10 0 0 0',
                            layout: 'hbox',
                            items: [
                                {
                                    xtype: 'label',
                                    width: '25%',
                                    docked: 'left',
                                    html: '신청상태',
                                    margin: '0 10 0 0'
                                },
                                {
                                    xtype: 'textfield',
                                    flex: 1,
                                    reference: 'sttnAplStcdNm',
                                    hidden: false,
                                    style: 'background-color:pink;',
                                    readOnly: true,
                                    editable: false
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            margin: '10 0 0 0',
                            layout: 'hbox',
                            items: [
                                {
                                    xtype: 'label',
                                    width: '25%',
                                    docked: 'left',
                                    html: '연수기관',
                                    margin: '0 10 0 0'
                                },
                                {
                                    xtype: 'textfield',
                                    flex: 1,
                                    reference: 'stnOrgtNm',
                                    readOnly: true,
                                    editable: false,
                                    bind: {
                                        value: '{detail.stnOrgtNm}'
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            margin: '10 0 0 0',
                            layout: 'hbox',
                            items: [
                                {
                                    xtype: 'label',
                                    width: '25%',
                                    docked: 'left',
                                    html: '교육구분',
                                    margin: '0 10 0 0'
                                },
                                {
                                    xtype: 'textfield',
                                    flex: 1,
                                    reference: 'sttnEduDvcdNm',
                                    readOnly: true,
                                    editable: false
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            margin: '10 0 0 0',
                            layout: 'hbox',
                            items: [
                                {
                                    xtype: 'label',
                                    width: '25%',
                                    docked: 'left',
                                    html: '신청일자',
                                    margin: '0 10 0 0'
                                },
                                {
                                    xtype: 'textfield',
                                    flex: 1,
                                    reference: 'sttnAplDtHiphone',
                                    readOnly: true,
                                    editable: false
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            margin: '10 0 0 0',
                            layout: 'hbox',
                            items: [
                                {
                                    xtype: 'label',
                                    width: '25%',
                                    docked: 'left',
                                    html: '연수시작',
                                    margin: '0 10 0 0'
                                },
                                {
                                    xtype: 'textfield',
                                    flex: 1,
                                    reference: 'sttnStrdt',
                                    readOnly: true,
                                    editable: false,
                                    bind: {
                                        value: '{detail.sttnStrdtHiphone}'
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            margin: '10 0 0 0',
                            layout: 'hbox',
                            items: [
                                {
                                    xtype: 'label',
                                    width: '25%',
                                    docked: 'left',
                                    html: '연수종료',
                                    margin: '0 10 0 0'
                                },
                                {
                                    xtype: 'textfield',
                                    flex: 1,
                                    reference: 'sttnEnd',
                                    readOnly: true,
                                    editable: false,
                                    bind: {
                                        value: '{detail.sttnEdtHiphone}'
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            margin: '10 0 0 0',
                            layout: 'hbox',
                            items: [
                                {
                                    xtype: 'label',
                                    width: '25%',
                                    docked: 'left',
                                    html: '연수기간',
                                    margin: '0 10 0 0'
                                },
                                {
                                    xtype: 'textfield',
                                    flex: 1,
                                    reference: 'sttnPridCntNm',
                                    readOnly: true,
                                    editable: false,
                                    bind: {
                                        value: '{detail.sttnPridCntNm}'
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            margin: '10 0 0 0',
                            layout: 'hbox',
                            items: [
                                {
                                    xtype: 'label',
                                    width: '25%',
                                    docked: 'left',
                                    html: '이수여부',
                                    margin: '0 10 0 0'
                                },
                                {
                                    xtype: 'textfield',
                                    flex: 1,
                                    reference: 'sttnCmpYnNm',
                                    readOnly: true,
                                    editable: false
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            margin: '10 0 0 0',
                            layout: 'hbox',
                            items: [
                                {
                                    xtype: 'label',
                                    width: '25%',
                                    docked: 'left',
                                    html: '포인트',
                                    margin: '0 10 0 0'
                                },
                                {
                                    xtype: 'textfield',
                                    flex: 1,
                                    reference: 'empPnt',
                                    readOnly: true,
                                    editable: false,
                                    bind: {
                                        value: '{detail.empPnt}'
                                    }
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'grid',
                    reference: 'detailGrid',
                    style: 'border:solid 1px #ddd;',
                    margin: '20 5 5 5',
                    maxHeight: 350,
                    minHeight: 150,
                    pinHeaders: false,
                    variableHeights: true,
                    columnResize: false,
                    hideHeaders: true,
                    sortable: false,
                    items: [
                        {
                            xtype: 'toolbar',
                            reference: 'gridToolbar',
                            hidden: true,
                            docked: 'top',
                            html: '신청자'
                        }
                    ],
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            flex: '1',
                            hidden: false,
                            align: 'center',
                            dataIndex: 'hrHrpmEmpId',
                            text: '사번'
                        },
                        {
                            xtype: 'gridcolumn',
                            flex: '1',
                            hidden: true,
                            align: 'center',
                            dataIndex: 'dpnm',
                            text: '부서명'
                        },
                        {
                            xtype: 'gridcolumn',
                            flex: '1',
                            align: 'center',
                            dataIndex: 'empeNm',
                            text: '신청자'
                        },
                        {
                            xtype: 'gridcolumn',
                            renderer: function(value, record, dataIndex, cell, column) {
                                return DateUtils.parseDate(value).substr(0,10);
                            },
                            flex: '1',
                            hidden: true,
                            align: 'center',
                            dataIndex: 'sttnAplDt',
                            text: '신청일자'
                        }
                    ],
                    plugins: [
                        {
                            type: 'gridpagingtoolbar'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    disabled: true,
                    scrollable: 'both',
                    layout: 'vbox',
                    items: [
                        {
                            xtype: 'common.approvallinegrid',
                            height: 450
                        },
                        {
                            xtype: 'textfield',
                            hidden: true,
                            name: 'version',
                            label: 'version',
                            bind: {
                                value: '{formValues.version}'
                            }
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'common.edocbuttoncontainer',
            docked: 'bottom'
        }
    ]

});