/*
 * File: app/view/HumanResource/hrd/HrdScyAply01MViewController.js
 *
 * This file was generated by Sencha Architect version 4.2.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.6.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.6.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

/*
    모바일 :: 사회공헌활동/사회공헌활동 - 컨트롤러

    @author BNK시스템/파트너/김면길
    @since 2024.03.11
    @version 1.0
    @see

    << 개정이력(Modification Information) >>

    수정일		  수정자                  수정내용
    ----------	--------------------   --------------------------
    2020.03.11	BNK시스템/파트너/김면길   최초 생성
*/
Ext.define('BNK.view.HumanResource.hrd.HrdScyAply01MViewController', {
    extend: 'BaseViewController',
    alias: 'controller.humanresource.hrd.hrdscyaply01m',

    config: {
        viewId: 'HrdScyAply01M'
    },

    /* 사회공헌활동 신청 리스트 조회 */
    onScyAplSelect: function() {
        var me = this,
            vm = me.getViewModel(),
            refs = me.getReferences(),
            grid = refs.gridScyApl,
            store = vm.storeInfo.Store,
            startDate = DateUtils.getFormatValue(new Date(),'Y-m-d'),
            endDate = DateUtils.parseDate(vm.get('year') + "-12-31"),
            params = {
                dateBefore : startDate,
                dateAfter : endDate
            };

            store.getProxy().extraParams = params;
            store.removeAll();
            store.loadPage(1);


    },

    /* 사회공헌활동 내역 리스트 조회 */
    onScyInfoSelect: function() {
        var me = this,
            vm = me.getViewModel(),
            refs = me.getReferences(),
            grid = refs.gridScyInfo,
            store = vm.storeInfo.Store2,
            startDate = DateUtils.parseDate(vm.get('year') + "-01-01"),
            endDate = DateUtils.parseDate(vm.get('year') + "-12-31"),
            principal = SecurityUtils.getPrincipal(),
            params = {
                dateBefore : startDate,
                dateAfter : endDate,
                hrHrpmDeptId : principal.hrHrpmDeptId,
                hrHrpmEmpId : principal.hrHrpmEmpId,
                hdqDeptId : principal.hdqDeptId
            };

            store.getProxy().extraParams = params;
            store.removeAll();
            store.loadPage(1);

    },

    /* 나의활동 지수 데이터 조회 */
    onDashbrdSelect: function() {
         var me = this,
             vm = me.getViewModel(),
             refs = me.getReferences(),
             year = vm.get('year'),
             params = {
                 schYear : year
             };

        // Service 호출
        Ext.Ajax.request({
            headers : {
                viewId : this.getView().xtype, 					// userAlias
                serviceId : 'HrdScySvc.findAllHrdScyCtrb' 	// 나의활동지수
            },
            jsonData : params,
            scope : me,
            success : function(response, opts) {
                var result = Ext.JSON.decode(response.responseText); // 서버응답결과 JSON 변환

                // 나의 활동지수
                if (result) {
                    var scyMyInfo = result.scyMyInfo;
                    // 직급별 순위
                    var scyMyRank = result.scyMyRank;
                    // 직급별 총 인원수
                    var scyTotalRank = result.scyTotalRank;

                    vm.set('scyMyInfo', scyMyInfo);
                    vm.set('scyMyRank', scyMyRank);
                    vm.set('scyTotalRank', scyTotalRank);

                    refs.stnInfo.setTitle('나의활동지수(' + '<span style="color:#CB2B11">' + year + '</span>' + ')');

                    // 활동횟수
                    refs.actCnt.setHtml(scyMyInfo[0].actCnt);
                    // 봉사시간
                    if(Ext.isEmpty(scyMyInfo[0].admtTm)){
                        scyMyInfo[0].admtTm = 0;
                    }
                    refs.admtTm.setHtml(scyMyInfo[0].admtTm);
                    // 직급별 순위/총 인원수
                    refs.rank.setHtml(scyMyRank[0].rank);
                    refs.total.setHtml(scyTotalRank);

                }

            },
            failure : function(response, opts){
                // Service 실패 했을 경우 기능
                Ext.Msg.show({
                    title : '실패',
                    message : '나의활동지수 데이터 조회 도중 에러가 발생했습니다.',
                    buttons : Ext.MessageBox.YES,
                    fn: function(btn){}
                });
            }
        });
    },

    dateTo8Char: function(utc) {
         if(utc){
             if (utc.toString().length > 8 && typeof (utc) != 'string') {
                 var yy = utc.getFullYear().toString();
                 var mm = (utc.getMonth() + 1).toString();
                 if (mm.length < 2) {
                     mm = '0' + mm;
                 }
                 var dd = utc.getDate().toString();
                 if (dd.length < 2) {
                     dd = '0' + dd;
                 }
                 return yy + mm + dd;
             }else if(utc.toString().length > 8){
                 return utc.replace('-', '').replace('-', '').substr(0, 8);
             }else {
                 return utc;
             }
         }
    },

    /* 이전년도로 이동 버튼 클릭 이벤트 */
    onPreButtonTap: function(button, e, eOpts) {
        var me = this,
            refs = me.getReferences(),
            vm = me.getViewModel(),
            year = vm.get('year'),
            activeTab = vm.get('activeTab'),
            principal = SecurityUtils.getPrincipal(),
            etcoDt = principal.etcoDt;


        // 입사년도
        var etcoYear = etcoDt.substring(0, 4);

        // 입사년도보다 이전으로 가려고 한다면
        if(Number(etcoYear) > year - 1){
            Ext.Msg.show({
                title : '조회불가',
                message : '입사년도보다 이전 데이터는 조회할 수 없습니다.',
                buttons : Ext.MessageBox.YES,
                fn: function(btn){}
            });
            return;
        }

        vm.set('year', year - 1);

        /* 뷰 새로고침 */
        me.onDashbrdSelect();

        if(activeTab == 'tabScyApl'){ // 사회공헌활동 신청 리스트 탭
            me.onScyAplSelect();
        }else{ // 사회공헌활동 내역 리스트 탭
            me.onScyInfoSelect();
        }
    },

    /* 다음년도로 이동 버튼 클릭 이벤트 */
    onNextButtonTap: function(button, e, eOpts) {
        var me = this,
            refs = me.getReferences(),
            vm = me.getViewModel(),
            year = vm.get('year'),
            activeTab = vm.get('activeTab'),
            principal = SecurityUtils.getPrincipal(),
            etcoDt = principal.etcoDt;


        // 입사년도
        var nowYear = new Date().getFullYear();

        // 입사년도보다 이전으로 가려고 한다면
        if(Number(nowYear) < year + 1){
            Ext.Msg.show({
                title : '조회불가',
                message : '현재년도보다 다음 데이터는 조회할 수 없습니다.',
                buttons : Ext.MessageBox.YES,
                fn: function(btn){}
            });
            return;
        }

        vm.set('year', year + 1);

        /* 뷰 새로고침 */
        me.onDashbrdSelect();

        if(activeTab == 'tabScyApl'){ // 사회공헌활동 신청 리스트 탭
            me.onScyAplSelect();
        }else{ // 사회공헌활동 내역 리스트 탭
            me.onScyInfoSelect();
        }
    },

    /* 그리드 행 선택 */
    onGridSelect: function(dataview, selected, eOpts) {
        var me = this,
            vm = me.getViewModel(),
            refs = me.getReferences(),
            grid = refs.gridScyApl,
            records = grid.getStore().data.items,
            trueRecords = selected, // 선택한 row 들
            naviView = me.getView().up('navigationview');

        // 하나만 선택되었는지 체크
        if(trueRecords.length > 1){
            Ext.Msg.show({
                title : '알림',
                message : '하나만 선택할 수 있습니다.',
                buttons : Ext.MessageBox.YES,
                fn: function(btn){}
            });
            return;
        }

        // 추가 가공 데이터 추가
        var strDt = trueRecords[0].data.cltStrdt; 			// 모집시작일자
        var eDt = trueRecords[0].data.cltEdt; 				// 모집종료일자
        var csrDt = trueRecords[0].data.csrDt;				// 모집일자
        var csrStrtm = trueRecords[0].data.csrStrtm;		// 활동 시작시간
        var csrEtm = trueRecords[0].data.csrEtm;			// 활동 종료시간
        var csrAmt = trueRecords[0].data.csrAmt;			// 교통비

        var period = DateUtils.parseDate(strDt) + " ~ " + DateUtils.parseDate(eDt); // 모집기간
        var csrDtFmt = DateUtils.parseDate(csrDt); 									// 모집일시 포매팅(yyyy-MM-dd)
        var csrStrtmFmt = DateUtils.parseTime(csrStrtm); 							// 시작시간 포매팅(HH:mm)
        var csrEtmFmt = DateUtils.parseTime(csrEtm); 								// 종료시간 포매팅(HH:mm)
        var csrDttm = csrDtFmt + " / " + csrStrtmFmt + " ~ " + csrEtmFmt; 			// 모집일시

        var csrAmtFmt = "0"; // 교통비 포매팅(천단위 처리)
        if(csrAmtFmt != null && csrAmtFmt != undefined){
            csrAmtFmt = csrAmt.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",") + '원';
        }

        trueRecords[0].data.period = period;
        trueRecords[0].data.csrDttm = csrDttm;
        trueRecords[0].data.csrAmtFmt = csrAmtFmt;

        // 현재 grid 탭명 저장
        trueRecords[0].data.preView = vm.get('activeTab');


        /* 화면이동 */
        if (trueRecords[0].data.stcd == '01') {
            me.PUSH_VIEW(naviView, {
                menuId  : 'HrdScyAply02M',
                title   : '사회공헌활동',
                records : trueRecords,
                isSubView : true,
                parentView : me.getView()
            });
        }
    },

    /* 그리드 행 선택 */
    onGridSelect1: function(dataview, selected, eOpts) {
        var me = this,
            vm = me.getViewModel(),
            refs = me.getReferences(),
            grid = refs.gridScyInfo,
            records = grid.getStore().data.items,
            trueRecords = selected, // 선택한 row 들
            naviView = me.getView().up('navigationview');

        // 하나만 선택되었는지 체크
        if(trueRecords.length > 1){
            Ext.Msg.show({
                title : '알림',
                message : '하나만 선택할 수 있습니다.',
                buttons : Ext.MessageBox.YES,
                fn: function(btn){}
            });
            return;
        }

        // 추가 가공 데이터 추가
        var strDt = trueRecords[0].data.cltStrdt; 			// 모집시작일자
        var eDt = trueRecords[0].data.cltEdt; 				// 모집종료일자
        var csrDt = trueRecords[0].data.csrDt;				// 모집일자
        var csrStrtm = trueRecords[0].data.csrStrtm;		// 활동 시작시간
        var csrEtm = trueRecords[0].data.csrEtm;			// 활동 종료시간
        var csrAmt = trueRecords[0].data.csrAmt;			// 교통비

        var period = DateUtils.parseDate(strDt) + " ~ " + DateUtils.parseDate(eDt); // 모집기간
        var csrDtFmt = DateUtils.parseDate(csrDt); 									// 모집일시 포매팅(yyyy-MM-dd)
        var csrStrtmFmt = DateUtils.parseTime(csrStrtm); 							// 시작시간 포매팅(HH:mm)
        var csrEtmFmt = DateUtils.parseTime(csrEtm); 								// 종료시간 포매팅(HH:mm)
        var csrDttm = csrDtFmt + " / " + csrStrtmFmt + " ~ " + csrEtmFmt; 			// 모집일시

        var csrAmtFmt = "0"; // 교통비 포매팅(천단위 처리)
        if(csrAmt != null && csrAmt != undefined){
            csrAmtFmt = csrAmt.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",") + '원';
        }

        trueRecords[0].data.period = period;
        trueRecords[0].data.csrDttm = csrDttm;
        trueRecords[0].data.csrAmtFmt = csrAmtFmt;

        // 현재 grid 탭명 저장
        trueRecords[0].data.preView = vm.get('activeTab');


        /* 화면이동 */
        if (trueRecords[0].data.stcd == '01') {
            me.PUSH_VIEW(naviView, {
                menuId  : 'HrdScyAply02M',
                title   : '사회공헌활동',
                records : trueRecords,
                isSubView : true,
                parentView : me.getView()
            });
        }
    },

    /* 탭 패널 아이템 클릭시 이벤트 */
    onMytabpanelActiveItemChange: function(sender, value, oldValue, eOpts) {
        var me = this,
            refs = me.getReferences(),
            vm = me.getViewModel();

        if(value.reference == 'tabScyApl'){ // 사회공헌활동 신청 탭 클릭시
            vm.set('activeTab', 'tabScyApl');
            me.onScyAplSelect();
        }else if(value.reference == 'tabScyInfo'){	// 사회공헌활동 내역 탭 클릭시
            vm.set('activeTab', 'tabScyInfo');
            me.onScyInfoSelect();
        }
    },

    /* 초기화 */
    onContainerInitialize: function(component, eOpts) {
        var me = this,
            vm = me.getViewModel(),
            refs = me.getReferences(),
            gridScyApl = refs.gridScyApl,
            stDt = refs.startDate,
            edDt = refs.endDate;

        // 초기 조회일자 설정하기
        var dateMinus1 = new Date();
        var year = dateMinus1.getFullYear();

        vm.set('year', year);

        // 현재 활성화된 탭 ref 저장 : 사회공헌활동 신청 리스트 탭 기본값
        vm.set('activeTab', 'tabScyApl');
    },

    /* 뷰 초기화 */
    onContainerPainted: function(sender, element, eOpts) {
        var me = this,
            vm = this.getViewModel(),
            activeTab = vm.get('activeTab');
        me.onDashbrdSelect();

        if(activeTab == 'tabScyApl'){ // 사회공헌활동 신청 리스트 탭
            me.onScyAplSelect();
        }else{ // 사회공헌활동 내역 리스트 탭
            me.onScyInfoSelect();
        }
    },

    onStoreLoad: function(store, records, successful, operation, eOpts) {
        var me = this,
            refs = me.getReferences();

        if(records.length == 0){
            refs.gridScyApl.setHidden(true);
            refs.noAplCtn.setHidden(false);
        }else{
            refs.gridScyApl.setHidden(false);
            refs.noAplCtn.setHidden(true);
        }

        // 그리드 헤더가 숨겨지지않는 오류가 발생하여 오류현상 개선
        refs.gridScyApl.setHideHeaders(false);
        refs.gridScyApl.setHideHeaders(true);

    },

    onStoreLoad1: function(store, records, successful, operation, eOpts) {
        var me = this,
            refs = me.getReferences();

        if(records.length == 0){
            refs.gridScyInfo.setHidden(true);
            refs.noInfoCtn.setHidden(false);
        }else{
            refs.gridScyInfo.setHidden(false);
            refs.noInfoCtn.setHidden(true);
        }

    }

});